### ISSUE TITLE
Lazy email validation

### ISSUE THREAD

**Issue by tremby** [omab/python-social-auth#1000]
Is there a way to validate email addresses but without pausing the pipeline? That is, to still allow the user to finish registering but with a flag on the user record to say their email address is not yet verified, and to change that flag once they have verified the address?

Thanks.

**Comment by omab** [comment]
Yeah, you need your own pipeline method that does such flag setting and avoids the pausing of the auth pipeline.

**Comment by tremby** [comment]
Would I then need to reimplement some of the other related functionality python-social-auth provides, or would I be able to hook back into it somehow? For example to complete the validation.

**Comment by omab** [comment]
Depends on your needs, but if you need email-validation you need to implement such feature at some point. PSA doesn't do much on this matter, it just sends an email with a link to complete the authentication in a way that we can trust that the user validated the address.

**Comment by tremby** [comment]
Well that's what I was hoping to repurpose, just without the delay and setting the flag. Doesn't matter -- the project I used this for is over now, but next time I use this module I'll have another shot.
