### ISSUE TITLE
Django 1.9 RemovedInDjango20Warning: Usage of field.rel has been deprecated. Use field.remote_field instead.

### ISSUE THREAD

**Issue by RevolutionTech** [omab/python-social-auth#1014]
Line 61 of `social/apps/django_app/default/models.py` uses `field.rel`:
https://github.com/omab/python-social-auth/blob/aa907384636a8ea87b86db3d5ab1580440e71665/social/apps/django_app/default/models.py#L61

This causes a warning in Django 1.9, but in Django 2.0 this code will cease to work.

On a related note, `ForeignObjectRel.to` was deprecated in favour of the model attribute.
Original exception message: `Usage of ForeignObjectRel.to attribute has been deprecated. Use the model attribute instead.`

Ref: https://docs.djangoproject.com/en/1.9/releases/1.9/#field-rel-changes

**Comment by omab** [comment]
Fix for this got merged in the new split components [python-social-auth](https://github.com/python-social-auth).

**Comment by RevolutionTech** [comment]
It doesn't look like this was fixed in `social-app-django`:
https://github.com/python-social-auth/social-app-django/blob/e368f5305ecb469ae0908b0fa24b8c1797d3d22c/social_django/models.py#L62

I suppose the more relevant issue for this now would be https://github.com/python-social-auth/social-app-django/issues/6 though.
