### ISSUE TITLE
Allow for per provider pipelines

### ISSUE THREAD

**Issue by keattang** [omab/python-social-auth#1016]
Hi, 

I'm looking to customise my pipeline such that each provider has a slightly different pipeline. Rather than throwing in a bunch of `if` statements everywhere I thought it would be much better to be able to define a pipeline per provider.

For example `SOCIAL_AUTH_PIPELINE` would be the default pipeline which could be overridden by `SOCIAL_AUTH_GOOGLE_OAUTH2_PIPELINE`.

I'm happy to make a pull request for this if it is something that you would consider merging? Ideally I'd like to see it released fairly soon so that I can take advantage of it in my current project.

**Comment by omab** [comment]
This got merged.

**Comment by keattang** [comment]
Thanks!
