### ISSUE TITLE
user_details Boolean fields

### ISSUE THREAD

**Issue by lklabs** [omab/python-social-auth#1017]
**Type: Bug**

**Version**: 0.2.21
**Django**: 1.9.2

**File**: social/pipeline/user.py
**Function**: user_details

**Description**: 
Sometimes user model can store boolean flags obtained from checkbox.
In this case _details_ dict will contain boolean variable (which could be equal to _False_)
In this case the code
`if value and hasattr(user, name):`
will never let the field _name_ to update, because _value_ == _False_

**Comment by omab** [comment]
I've added a fix for this on [social-core](https://github.com/python-social-auth/social-core/commit/f1a66542b4972486ee8c0130efb8365534d9a7af). Only `None` values will be ignored.
