### ISSUE TITLE
Using associate_user pipeline for Oauth2

### ISSUE THREAD

**Issue by Ajeetlakhani** [omab/python-social-auth#1020]
I am using [Signup by OAuth access_token](http://python-social-auth.readthedocs.io/en/latest/use_cases.html#signup-by-oauth-access-token) along with django-oauth-toolkit for OAuth2 authentication.

I used 'associate_user' pipeline to connect multiple backend with Session auth. How to use the same pipeline to connect multiple backend using OAuth2.

**Comment by omab** [comment]
The pipeline is backend agnostic, doesn't differentiate between OAuth2, OAuth1, OpenId or legacy, the same rules are applied to all.
