### ISSUE TITLE
flask_peewee_example seems doesn't work well in peewee 2.8.3

### ISSUE THREAD

**Issue by ChateauXiao** [omab/python-social-auth#1025]
alexpantyukhin  add support peewee for flask
https://github.com/omab/python-social-auth/pull/932

but the code above can not work  on my env:

my requirements.txt is this:
$ pip freeze
click==6.6
Flask==0.11.1
Flask-Login==0.3.2
Flask-Script==2.0.5
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
oauthlib==2.0.0
**peewee==2.8.3**
PyJWT==1.4.2
pysqlite==2.8.3
python-openid==2.2.5
python-social-auth==0.2.21
requests==2.11.1
requests-oauthlib==0.7.0
six==1.10.0
Werkzeug==0.11.11

when i run the command manage.py, i got the error message like this:

/flask_peewee_example$ python manage.py runserver
/home/testing/env_login_test/local/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing **flask.ext.script** is deprecated, use flask_script instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from flask_example import app, database
  File "../flask_example/**init**.py", line 3, in <module>
    from sqlalchemy import create_engine
**ImportError: No module named sqlalchemy**

**Comment by ChateauXiao** [comment]
we already use peewee, why do we have to install sqlalchemy also?

**Comment by alexpantyukhin** [comment]
Yes.. it looks like and error. I will look on it.

**Comment by omab** [comment]
This got fixed in the new [examples component](https://github.com/python-social-auth/social-examples/blob/master/example-flask-peewee).
