### ISSUE TITLE
MIGRATION

### ISSUE THREAD

**Issue by omab** [omab/python-social-auth#1029]
Python-social-auth is getting migrated to http://github.com/python-social-auth where it's getting split on several smaller modules with their own dependencies properly specified (no more flask and django apps in the same repo), it's also an opportunity to renew the development process with a defined contribution guidelines, better versioning (semver).

Items to complete the migration:
- [x] Split python-social-auth in smaller modules per responsibility
- [x] ~Migrate omab/python-social-auth to python-social-auth org~
- [x] Port examples
- [x] Apply patches from PRs on their corresponding modules
- [x] Port issues to their corresponding modules
- [x] Update this lib to depend on the new modules and ensure it's functionality
- [x] Update README noticing the deprecation of this monolithic library
- [x] Write a migration document ([MIGRATING_TO_SOCIAL](https://github.com/omab/python-social-auth/blob/master/MIGRATING_TO_SOCIAL.md))

**Comment by adamchainz** [comment]
Hi, at work we're looking to upgrade to Django 1.10 and python-social-auth is one of dependencies that needs to upgrade. Is there anything I can do to help with the migration? 😸

**Comment by omab** [comment]
TODO: port the merged #1031

**Comment by alexandcote** [comment]
@omab Can I help you with something ? It's a huge job alone !

**Comment by alexpantyukhin** [comment]
+1 @alexandcote . Also want to help.

**Comment by alexpantyukhin** [comment]
@omab  I have added PR https://github.com/python-social-auth/social-app-django/pull/1 which is migration of https://github.com/omab/python-social-auth/pull/1031 on new repos.

**Comment by omab** [comment]
Thank you all, the migration is going well, migrating PRs is going to be the more tedious part, but luckily many are straightforward and don't spread across components.

**Comment by omab** [comment]
Small update, as you might noted, things keeps moving, I've updated this lib to depend on the new split packages, tests are all green. Now I'll start on migrating the different PRs/Issues to the new organization.

**Comment by omab** [comment]
All relevant PRs got ported to their corresponding components.

**Comment by omab** [comment]
Migration complete! :tada:

**Comment by dcmoore-gd** [comment]
Thanks for all your work on `python-social-auth` and now its dependencies, @omab!
