### ISSUE TITLE
Please make social-auth work with Django 1.10

### ISSUE THREAD

**Issue by PolywickStudio** [omab/python-social-auth#1032]
I keep getting this error

LookupError at /admin/Movies/movietitles/65/change/
No installed app with label 'Social Nonce'.
Request Method: GET
Request URL:    http://127.0.0.1:8000/admin/Movies/movietitles/65/change/
Django Version: 1.10.2
Exception Type: LookupError
Exception Value:  
No installed app with label 'Social Nonce'.
Exception Location: C:\Python27\lib\site-packages\django\apps\registry.py in get_app_config, line 155
Python Executable:  C:\Python27\Scripts\python.exe
Python Version: 2.7.12
Python Path:  
['C:\Users\sallyp\prjamh2\poptvpynew',
 'C:\Users\sallyp\prjamh2\poptvpynew',
 'C:\Windows\SYSTEM32\python27.zip',
 'C:\Python27\DLLs',
 'C:\Python27\lib',
 'C:\Python27\lib\plat-win',
 'C:\Python27\lib\lib-tk',
 'C:\Python27\Scripts',
 'C:\Python27',
 'C:\Python27\lib\site-packages',
 'c:\users\sallyp\prjamh2\turbogear\myproj',
 'C:\Python27\lib\site-packages\win32',
 'C:\Python27\lib\site-packages\win32\lib',
 'C:\Python27\lib\site-packages\Pythonwin']
Server time:    Wed, 5 Oct 2016 15:57:12 +0800

**Comment by cleder** [comment]
more details please, it works fine for me on django 1.10.2 on linux

**Comment by omab** [comment]
The app works fine with Django 1.10, the new split of the app ensured that the warnings were placated.
