### ISSUE TITLE
Multiple apps integration for the same provider

### ISSUE THREAD

**Issue by santhoshraju18** [omab/python-social-auth#1041]
Hi Guys,

Is there a way to use multiple social apps to integrate with each backend? Like I have two apps for Facebook and I want to dynamically use those app credentials to authenticate social users instead of specifying them in Django settings. Can this be done @omab ?

Thanks.

**Comment by omab** [comment]
By itself, the app won't support that schema, but you can override it simply by defining your own Facebook backend that overrides the `get_key_and_secret()` method:

```python
from social.backends.facebook import FacebookOAuth2

class CustomFacebook(FacebookOAuth2):
    def get_key_and_secret(self):
        key = get_facebook_app_key_based_on_some_rule()
        secret = get_facebook_app_secret_based_on_some_rule()
        return key, secret
```

Then use that backend by replacing `social.backends.facebook.FacebookOAuth2` in the `AUTHENTICATION_BACKENDS` setting with the import path to your `CustomFacebook` one.

**Comment by santhoshraju18** [comment]
Okay thanks for helping with the workaround @omab. But the real problem for us is to pass instance id as an argument to the get_key_and_secret() method so as to obtain the auth_key and auth_secret from a different model.

**Comment by omab** [comment]
Depends on your application, you can do it by:

1. Overriding the python-social-auth views in order to specify the needed option
2. Adding a parameter to the links querystring (which can then be retrieved in the backends by doing `self.strategy.request_data()`)
3. Adding a parameter to the session (which can be accessed in the backends with `this.strategy.session`

**Comment by santhoshraju18** [comment]
Thanks @omab it really works using both steps 2 and 3 combined together. Closing this now.

**Comment by fthuin** [comment]
@santhoshraju18 Hi, I'm trying to do the same for 4 differents Facebook apps, could you share some code to reproduce the solution ?
