### ISSUE TITLE
https://www.googleapis.com/plus/v1/people/me deprecated

### ISSUE THREAD

**Issue by niuguoning** [omab/python-social-auth#1043]
It seems like the google plus sign in has been deprecated in favor of google sign in and that we should be using https://www.googleapis.com/oauth2/v3/tokeninfo?id_token to verify the token instead of using https://www.googleapis.com/plus/v1/people/me.

**Comment by omab** [comment]
That doesn't seem correct, `tokeninfo` just returns information about the token (app, granted scopes, user id, lifetime), but no user details like `people/me`.
