### ISSUE TITLE
Facebook2OAuth2 is using a deprecated endpoint

### ISSUE THREAD

**Issue by browniebroke** [omab/python-social-auth#1045]
I received a notification from Facebook saying I was using a deprecated endpoint that is going to be shut down soon. When I dug, I realised I was using `Facebook2OAuth2` back-end instead of the more up-to-date `FacebookOAuth2`.

It looks like `Facebook2OAuth2` was added when `FacebookOAuth2` was still using v1 of the open graph, and Facebook2 could now be removed, as it's using [unavailable endpoints](https://developers.facebook.com/docs/apps/changelog/).

I suggest to either:
- Change `Facebook2OAuth2` to be same as `FacebookOAuth2` with a deprecation warning logged in the `__init__()`.
- New release without forgetting to mention the breaking change in the release notes

**Comment by omab** [comment]
This got ported to [python-social-auth](https://github.com/python-social-auth). Thanks!
