### ISSUE TITLE
Import error in django_example

### ISSUE THREAD

**Issue by shivamMg** [omab/python-social-auth#1058]
The following error occurs when running the [django_example](https://github.com/omab/python-social-auth/tree/master/examples/django_example):

 ```
ImportError: cannot import name 'patterns'
```

This occurs because requirements specify `django>=1.4` and it installs the latest version of django (1.10.x).  `patterns` are not available after 1.8. The django version in [requirements.txt](https://github.com/omab/python-social-auth/blob/master/examples/django_example/requirements.txt) must be freezed to `django>=1.4,<1.8`, where it installs `django-1.7.11`, and patterns are available. 

Or, we can alter the code to be compatible with `django-1.10.x`. If someone gives a go ahead i would like to work on this.

https://docs.djangoproject.com/en/1.10/releases/1.8/#django-conf-urls-patterns

**Comment by WGierke** [comment]
Go ahead! :)

**Comment by omab** [comment]
This got fixed already.
