### ISSUE TITLE
ImportError: No module named 'social_django'

### ISSUE THREAD

**Issue by divonelnc** [omab/python-social-auth#1070]
When getting version 0.3.0, I get the following error:

`ImportError: No module named 'social_django'`

Anybody had a similar issue?

**Comment by omab** [comment]
You need to install `social-auth-app-django` too. Check the details in the [migration file](https://github.com/omab/python-social-auth/blob/master/MIGRATING_TO_SOCIAL.md#django).

**Comment by yeago** [comment]
....requirements.txt....?

**Comment by omab** [comment]
Sorry?

**Comment by coleclayman** [comment]
shouldn't that be included in the requirements.txt ? so that when you install python-social-auth, pip will download and install social-auth-app-django as well?

**Comment by omab** [comment]
@coleclayman, no, because somebody using `Flask` will end with a lot of dependencies related to `Django` that's undesired, so I've opted to document the needed dependency instead.

**Comment by sils** [comment]
@omab how about using setuptools extras?

**Comment by omab** [comment]
@sis, I can explore that option.

**Comment by omab** [comment]
@sis, I've added the `extras` in [setup.py](https://github.com/omab/python-social-auth/blob/master/setup.py#L85-L95) also documented them in the [migration doc](https://github.com/omab/python-social-auth/blob/master/MIGRATING_TO_SOCIAL.md).

**Comment by tolsoft32** [comment]
thanks, this help out, but i am now having issue with my django url back end, it display the following after login in with the superuser credential i created


Request Method: | POST
-- | --
http://127.0.0.1:8000/admin/login/?next=/admin/
1.8.6
ImportError
Module "social.backends.facebook" does not define a "Facebook2OAuth2" attribute/class
C:\Users\TIPGRI~1\book_env\env\BOOKSM~1\lib\site-packages\django\utils\module_loading.py in import_string, line 29
C:\Users\TIPGRI~1\book_env\env\BOOKSM~1\Scripts\python.exe
3.6.2
['C:\\Users\\Tipgridcom Services\\book_env\\bookmarks',  'C:\\Users\\TIPGRI~1\\book_env\\env\\BOOKSM~1\\Scripts\\python36.zip',  'C:\\Users\\TIPGRI~1\\book_env\\env\\BOOKSM~1\\DLLs',  'C:\\Users\\TIPGRI~1\\book_env\\env\\BOOKSM~1\\lib',  'C:\\Users\\TIPGRI~1\\book_env\\env\\BOOKSM~1\\Scripts',  'c:\\users\\tipgridcom '  'services\\appdata\\local\\programs\\python\\python36\\Lib',  'c:\\users\\tipgridcom '  'services\\appdata\\local\\programs\\python\\python36\\DLLs',  'C:\\Users\\TIPGRI~1\\book_env\\env\\BOOKSM~1',  'C:\\Users\\TIPGRI~1\\book_env\\env\\BOOKSM~1\\lib\\site-packages']
Sat, 9 Dec 2017 22:07:53 +0100

does anyone have the idea of what i need to do and how to go about this.

Regards
