### ISSUE TITLE
Cannot import name engines

### ISSUE THREAD

**Issue by fendyh** [omab/python-social-auth#1078]
I'm now encountering an error, it says ImportError at /
cannot import name engines
it traced back to /lib/python2.7/site-packages/social_django/strategy.py in this line
from django.template import TemplateDoesNotExist, RequestContext, loader, engines

please help

**Comment by omab** [comment]
Roll back to python-social-auth `0.2.21`, anything `>= 0.3.0` is not compatible with Django 1.7.

**Comment by 16116073** [comment]
I tried with the mention version but it still did nt fix.. what shud i do?
