### ISSUE TITLE
'QuerySet' object has no attribute 'social_auth'

### ISSUE THREAD

**Issue by joshlsullivan** [omab/python-social-auth#1084]
I am following the example:

import requests

user = User.objects.get(...)
social = user.social_auth.get(provider='google-oauth2')
response = requests.get(
    'https://www.googleapis.com/plus/v1/people/me/people/visible',
    params={'access_token': social.extra_data['access_token']}
)
friends = response.json()['items']

found [here](http://psa.matiasaguirre.net/docs/use_cases.html). I get the error `AttributeError: 'QuerySet' object has no attribute 'social_auth'`. Any ideas?

**Comment by omab** [comment]
Ensure that the `user` is indeed a user instance and not a queryset.
