### ISSUE TITLE
Too bad, casually abandoned

### ISSUE THREAD

**Issue by ghost** [omab/python-social-auth#1105]
huhuhu

**Comment by BojanKogoj** [comment]
Not abandoned, moved to https://github.com/python-social-auth/social-core

**Comment by omab** [comment]
@ziming2018, as pointed, not abandoned, it was moved to an organization (I'll look into bring more people to the project at some point), and split the application on logical modules, no need to have Django and Flask stuff all in the same place where dependencies cannot be defined without conflicts.
