### ISSUE TITLE
Support for tokens / secrets in database

### ISSUE THREAD

**Issue by liquidscorpio** [omab/python-social-auth#1109]
Is it possible to store tokens in database instead of `settings.py`? By tokens,  I mean back-end specific configuration variables like:
```
// Similarly for others too
SOCIAL_AUTH_FACEBOOK_KEY
SOCIAL_AUTH_FACEBOOK_SECRET
```

I am trying to support a use case where these values are specific to each tenant in a multi-tenant environment.

**Comment by dblado** [comment]
Did you figure this out?
