### ISSUE TITLE
Twitter backend error with Python 3.3

### ISSUE THREAD

**Issue by fajran** [omab/python-social-auth#139]
(Perhaps this also affects all OAuth1 based backends)

I got the following error

```
b'oauth_token=TOKEN&oauth_token_secret=SECRET&oauth_callback_confirmed=true' is not JSON serializable
```

The error arises when Django saves the session data (encoded in JSON) that contains that unauthorized token from Twitter. The type of the token is byte so the `json` module refuses to encode it. I see that the token value is retrieved from the `requests` module.

Other libs that are also installed in my setup:

```
$ pip list
Django (1.6)
geojson (1.0.5)
ipython (1.1.0)
lxml (3.2.4)
oauthlib (0.6.0)
pip (1.4.1)
psycopg2 (2.5.1)
pykml (0.1.0)
python-social-auth (0.1.17)
python3-openid (3.0.3)
raven (3.5.2)
requests (2.1.0)
requests-oauthlib (0.3.1)
setuptools (0.9.8)
Shapely (1.2.18)
six (1.4.1)
South (0.8.4)
virtualenv (1.10.1)
```

**Comment by JordanReiter** [comment]
I'm getting the same error on Master now, with the Facebook OAuth backend.
