### ISSUE TITLE
usage as a library; improve documentation?

### ISSUE THREAD

**Issue by jandob** [omab/python-social-auth#206]
I don't use any of the supported frameworks.
Are there any docs/examples how to use the module as a library?

I looked a bit at the code and from what i understand one has to do something like:
- write a strategy class
- write a storage class 
- use the auth/login/disconnect methods in social.actions

But to do that, i think i have to reverse engineer one of the supported framework in social.apps..
.

**Comment by dcmoore-gd** [comment]
@jandob Did you end up pursuing this further?  I'm considering a similar usage.  Thanks!

**Comment by jandob** [comment]
@dcmoore-gd 
No sorry, not much more than the gist i posted, but i think you could build on that.

**Comment by dcmoore-gd** [comment]
Incidentally, if anyone comes across this thread, I did end up using it like a library as well, though a bit differently than the gist above.  I identified a few minor changes to python-social-auth that would make this easier for us and others to do, so will try to contribute some of that as time allows.

**Comment by omab** [comment]
The recent [split into smaller components](https://github.com/python-social-auth) should make the support for this more straightforward and clean, I'm sure it's not 100% ready to do so, but in it should be possible.
