### ISSUE TITLE
HTTPError at /complete/facebook/ when trying to connect to Facebook.

### ISSUE THREAD

**Issue by psych0der** [omab/python-social-auth#207]
I am keep getting this 400 Client Error: Bad Request whenever I try to connect to Facebook through python social auth. I have entered correct parameter in Facebook app settings ( localhost:8000 as site URL).

Here's the exception stack : 

HTTPError at /complete/facebook/
400 Client Error: Bad Request
Request Method: GET
Request URL:    http://localhost:8000/complete/facebook/?redirect_state=znj2c5EEL42tSm7bteQF2HtgOFyDKEDD&code=AQBeVfYEcNM6ehAVgfOLx3B1GHEu48-V8zRh8l-pLvo8Kn43_x85XvFwVDsXsG1i7UWoA56zgbPNKmCMS7veZV85aamR_unPH1lTGmI3H18tf_CiAuLP9kMyDdeumIPtQeIkOnSO6BCivIVfp1TwezoQlpR8Dwksh8aZ389GzEcXeAhf28fzWU9YYs52sIg8zbJ-CQjFk18igGrpj0Iz4Agzxe1LyaiYtOAB8wxkzbfgVYm7s9FBYSKZ-Y0O5OiNTx5-8t0fEcYs2tu2YwssP9A6nXyM58bLWZmVyFZqmbILJxI8yP-dbJ_SkWn0sVFUVxc&state=znj2c5EEL42tSm7bteQF2HtgOFyDKEDD
Django Version: 1.5.5
Exception Type: HTTPError
Exception Value:  
400 Client Error: Bad Request
Exception Location: /Users/mayankbhola/nobles0ul_progr/venvs/resumizr/lib/python2.7/site-packages/requests/models.py in raise_for_status, line 773
Python Executable:  /Users/mayankbhola/nobles0ul_progr/venvs/resumizr/bin/python
Python Version: 2.7.6
Python Path:  
['../..',
 '/Users/mayankbhola/Downloads/python-social-auth-master/examples/django_example',
 '/Users/mayankbhola/nobles0ul_progr/venvs/resumizr/lib/python2.7/site-packages/mongoengine-0.8.7-py2.7.egg',
 '/Users/mayankbhola/nobles0ul_progr/venvs/resumizr/lib/python2.7/site-packages/pymongo-2.6.3-py2.7-macosx-10.9-x86_64.egg',
 '/Users/mayankbhola/nobles0ul_progr/venvs/resumizr/lib/python27.zip',
 '/Users/mayankbhola/nobles0ul_progr/venvs/resumizr/lib/python2.7',
 '/Users/mayankbhola/nobles0ul_progr/venvs/resumizr/lib/python2.7/plat-darwin',
 '/Users/mayankbhola/nobles0ul_progr/venvs/resumizr/lib/python2.7/plat-mac',
 '/Users/mayankbhola/nobles0ul_progr/venvs/resumizr/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/mayankbhola/nobles0ul_progr/venvs/resumizr/lib/python2.7/lib-tk',
 '/Users/mayankbhola/nobles0ul_progr/venvs/resumizr/lib/python2.7/lib-old',
 '/Users/mayankbhola/nobles0ul_progr/venvs/resumizr/lib/python2.7/lib-dynload',
 '/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/mayankbhola/nobles0ul_progr/venvs/resumizr/lib/python2.7/site-packages']
Server time:    Wed, 5 Mar 2014 08:00:44 -0200

**Comment by alexche8** [comment]
I got same issue  with steam .
