### ISSUE TITLE
No module named apps.django_app.default.models in custom pipeline

### ISSUE THREAD

**Issue by faxioman** [omab/python-social-auth#213]
I'm trying to create a custom pipeline in a Django 1.6 project with a custom user model.
I am able to import, using a django shell, the UserSocialAuth model:

```
from social.apps.django_app.default.models import UserSocialAuth
```

But, when I try to import the same class inside the custom pipeline module, I get this error:

No module named apps.django_app.default.models

**Comment by Darwesh27** [comment]
@omab I've encountered a same kind of problem. The reason, I guess, is that I have an app named 'social'. What can I do about it.

**Comment by omab** [comment]
Don't name a module the same of a dependency (which is a good policy always), or use ``absolute_import`` (check https://www.python.org/dev/peps/pep-0328/).

**Comment by Darwesh27** [comment]
I didn't knew this problem would occur. Now I have a running local app with name social and my site is live. I think I can't change the name of my local app. Is there any way I can refer the python-social-auth's 'social' app with a different name in my whole project including INSTALLED_APPS

**Comment by Darwesh27** [comment]
And also 'social' is too common name. python-social-auth should have some prefix to social.

**Comment by omab** [comment]
If your ``social`` app is inside your project directory (the one with the ``settings.py``), then you can use ``project.social`` in ``INSTALLED_APPS``.

If ``social`` is too common, then you can rename your own version of it, or you can ask to the many python projects around to rename their apps because they are too common too.

**Comment by Darwesh27** [comment]
I'd definitely had renamed my app to something specific rather then just 'social' if it was going to be used by hundreds of developers around but since I will just be used by me so I am going to keep it that way and use another social auth app that will not conflict. :)

**Comment by omab** [comment]
Yeah, that works too.
