### ISSUE TITLE
Facebook: "Invalid App ID: None"

### ISSUE THREAD

**Issue by ckcollab** [omab/python-social-auth#252]
First of all: thanks so much for releasing, supporting and documenting this app! I am really pumped to use it, just a little problem in the way.

I am using Django and here are my settings:

``` python
TEMPLATE_CONTEXT_PROCESSORS = (
    ...
    'social.apps.django_app.context_processors.backends',
    'social.apps.django_app.context_processors.login_redirect',
)

MIDDLEWARE_CLASSES = (
    ...
    'social.apps.django_app.middleware.SocialAuthExceptionMiddleware',
)

BASE_AND_LIBRARY_APPS = (
    ...
    'social.apps.django_app.default',
    ...
)

AUTHENTICATION_BACKENDS = (
   'social.backends.facebook.FacebookOAuth2',
   'social.backends.google.GoogleOAuth2',
   'social.backends.twitter.TwitterOAuth',
   'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_FACEBOOK_KEY = os.environ.get("SOCIAL_AUTH_FACEBOOK_KEY ", None)
SOCIAL_AUTH_FACEBOOK_SECRET = os.environ.get("SOCIAL_AUTH_FACEBOOK_SECRET", None)
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY", None)
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET", None)

SOCIAL_AUTH_TWITTER_KEY = os.environ.get("SOCIAL_AUTH_TWITTER_KEY", None)
SOCIAL_AUTH_TWITTER_SECRET = os.environ.get("SOCIAL_AUTH_TWITTER_SECRET", None)

LOGIN_REDIRECT_URL = '/'

AUTH_USER_MODEL = "user_profile.UserProfile"
```

And my link like such:

```
<a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">Login with Facebook</a>
```

I must have fudged something up, I've looked at all the resources I could find and it seems like I am doing this right. I am positive the key is actually set:

```
(venv) > heroku run echo $SOCIAL_AUTH_FACEBOOK_KEY
Running `echo $SOCIAL_AUTH_FACEBOOK_KEY` attached to terminal... up, run.4085
62342344525454353453452739
```

but when I look at the url:
![image](https://cloud.githubusercontent.com/assets/2185159/2748334/6e8338d6-c7bb-11e3-88fd-68b2f3e2e1b3.png)

`?client_id=None`

Again, thanks for the lib and I appreciate any help!

**Comment by zhangoose** [comment]
@ckcollab Hi! I know this is old, but do you remember what you did in this issue to solve it?

**Comment by ckcollab** [comment]
I think it may have been that I wasn't using https or something? Can you give me some more details and I'll try to dig up what I did?

**Comment by zhangoose** [comment]
@ckcollab Thanks for the reply! Actually I just figured it out, heh. I was using a virtualenv and I just didn't export the environment variables I set in my `.env`. :disappointed:
