### ISSUE TITLE
Google+ Sign-in problem

### ISSUE THREAD

**Issue by kamikaze** [omab/python-social-auth#285]
When trying to login, I'm getting this from google:
1. That’s an error.

Error: invalid_scope

Some requested scopes were invalid. {valid=[https://www.googleapis.com/auth/userinfo.email], invalid=[plus.login]}

**Comment by avibrazil** [comment]
Me too... I had to enable Google+ API even if not needed by my app.

**Comment by vahedq** [comment]
Are you guys still able to use this fine? I have it set up, and Google+ API is enabled, but am getting this error:

Traceback (most recent call last):
  File "/storage/client/repo1/server/eagle/views.py", line 56, in register_by_access_token
    user = backend.do_auth(access_token)
  File "/usr/local/lib/python2.7/dist-packages/social/backends/oauth.py", line 383, in do_auth
    data = self.user_data(access_token, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/social/backends/google.py", line 74, in user_data
    'alt': 'json'
  File "/usr/local/lib/python2.7/dist-packages/social/backends/base.py", line 229, in get_json
    return self.request(url, *args, **kwargs).json()
  File "/usr/local/lib/python2.7/dist-packages/social/backends/base.py", line 225, in request
    response.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: Forbidden

**Comment by divestrato** [comment]
I have the same problem as @vahedq as well. Any pointers will be much appreciated!

**Comment by omab** [comment]
Yesterday I've updated the Google+ Sign-In docs and fixed some issues in the backend, take a look to the docs here http://psa.matiasaguirre.net/docs/backends/google.html?_=123#google-sign-in it might help.

**Comment by morninj** [comment]
I had the same issue. I solved it by enabling the Google+ API from `console.developers.google.com`.

**Comment by sureshvv** [comment]
+1 to bettsmatt & morninj

**Comment by chandrunitk** [comment]
bettsmatt's solution did it for me!

**Comment by rajeeshnair** [comment]
I still struggling with the same problem as @vahedq Project created, Google+ API enabled. My UI (angularjs) is able to let user login by google and pass the access_token. When psa's backend.do_auth is invoked with token, 403 is raised. Testing is done localhost and an AWS client.

**Comment by naveen319** [comment]
Hi I am struggling with this issue,

TypeError at /social-auth/complete/google-oauth2/
unsupported operand type(s) for +: 'NoneType' and 'int'

I am getting this error even for Twitter and Facebook. Can any one please help me on this,

![error](https://user-images.githubusercontent.com/22286945/27614402-1219156e-5b67-11e7-8b50-7eea07660656.JPG)

**Comment by lucasvazq** [comment]
For all those people that have the same issue, one alternative to solve it is to update the package. I have the problem in v1 and enabling Google+ doesn't solve it, but upgrading to v4 does.
