### ISSUE TITLE
Facebook SOCIAL_AUTH_FACEBOOK_SCOPE not working as expected

### ISSUE THREAD

**Issue by imns** [omab/python-social-auth#294]
I have 

```
SOCIAL_AUTH_SCOPE = SOCIAL_AUTH_FACEBOOK_SCOPE = [
    'email',
    'manage_pages',
    'publish_stream'
]
```

In my settings file, but Facebook always returns `{"error":{"message":"(#200) The user hasn't authorized the application to perform this action","type":"OAuthException","code":200}}` with a status code of 403 when I try to modify a page.

**Comment by arahman17** [comment]
This do the expected result for me. Hope it helps...

SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'locale': 'ru_RU',
    'fields': 'id, name, email, age_range'
}
