### ISSUE TITLE
email as the username_field

### ISSUE THREAD

**Issue by pcompassion** [omab/python-social-auth#303]
From [django doc](https://docs.djangoproject.com/en/dev/topics/auth/customizing/#django.contrib.auth.models.CustomUser.USERNAME_FIELD): 

A string describing the name of the field on the User model that is used as the unique identifier. This will usually be a username of some kind, but it can also be an email address, or any other unique identifier. The field must be unique (i.e., have unique=True set in its definition).

Basically it says `USERNAME_FIELD` is a field to uniquely identify a user.

I'd like to use `username` field to hold real name or a nickname (duplicable)
`email` field as the `USERNAME_FIELD`
and it is hard to achieve with python-social-auth. 

For example, google oauth2 gives me 
username: eugene
email: a@gmail.com

I'd like to use the data to create (username: eugene, unique email: a@gmail.com) user.  
Following two functions are responsible for the username/email field.

(pipeline.user.py)

```
def get_username(strategy, details, user=None, *args, **kwargs):
....
    if email_as_username and details.get('email'):
        username = details['email']
    elif details.get('username'):
        username = details['username']
```

(storage.django.orm.py)

```
@classmethod
def create_user(cls, *args, **kwargs):
    if 'username' in kwargs:

        kwargs[cls.username_field()] = kwargs.pop('username')
   return cls.user_model().objects.create_user(*args, **kwargs)
```

They allow 
1. email: a@gmail.com (email_as_username = True, USERNAME_FIELD=email)
2. username: eugene email: a@gmail.com (USERNAME_FIELD=username)
3. username: a@gmail.com (email_as_username = True, USERNAME_FIELD=username)
4. email: eugene (USERNAME_FIELD=email)

How do I get
username: eugene email: a@gmail.com while USERNAME_FIELD=email ?

Should I override either of the above two functions or individual oauth2 backend class code?

**Comment by omab** [comment]
`SOCIAL_AUTH_USER_FIELDS` can be used to override the default fields used to create the user instance, there's also `SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL` to accomplish an email-as-username setup.
