### ISSUE TITLE
Cannot log out from GooglePlus Auth. Homepage keeps calling its GooglePlus callback

### ISSUE THREAD

**Issue by epetxepe** [omab/python-social-auth#316]
Hi all,

    I've correctly implemented the login with GooglePlus, but once I signed up with an account, I'm not able to logout / disconnect correctly, and use local or other Google accounts.

   I'm using the login from the example:

```
            <script type="text/javascript">                    
                     var signInCallback = function (result) {
                    if (result['error']) {
                      alert('An error happened:', result['error']);
                    } else {
                      $('#code').attr('value', result['code']);
                      $('#at').attr('value', result['access_token']);
                      $('#google-plus').submit();
                    }
                };                    
               </script>
                  <script type="text/javascript">
                   (function () {
                       var po = document.createElement('script');
                       po.type = 'text/javascript';
                       po.async = true;
                       po.src = 'https://plus.google.com/js/client:plusone.js?onload=start';
                       var s = document.getElementsByTagName('script')[0];
                       s.parentNode.insertBefore(po, s);
                   })();
                    </script>
                  <li role="presentation">
                 <form id="google-plus" method="post" action="{% url "social:complete" backend="google-plus" %}">{% csrf_token %}
                    <input id="at" type="hidden" name="access_token" value="" />
                    <input id="code" type="hidden" name="code" value="" />
              
                    <div id="signinButton">
                      <span class="g-signin" data-scope="{{ plus_scope }}"
                                             data-clientid="{{ plus_id }}"
                                             data-redirecturi="postmessage"
                                             data-accesstype="offline"
                                             data-cookiepolicy="single_host_origin"
                                             data-callback="signInCallback">
                      </span>
                    </div>
               </form>
               </li>`
```

I've tried for logout both  
```
url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'},  name='logout'),
```
and my own view
```
def logout(request):
    """Logs out user"""
    auth_logout(request)
    return redirect('/')
    #url(r'^logout', 'siteLogic.views.logout', name='logout'),
```
Regarding disconnect, it seems it works well since no association is found in the following code once executed the following
```
   <div class="social">
        {% for sublist in available_backends|social_backends %}
          <div class="row">
            {% for name, backend in sublist %}
              {% associated backend %}
              {% if association %}
                <form class="disconnect-form" action="{% url "social:disconnect_individual" backend=association.provider association_id=association.id %}" method="post">{% csrf_token %}
                  <button type="submit" name="{{ backend|backend_class }}" class="btn btn-danger">Disconnect {{ backend|backend_name }}</button>           
                </form>
              <!--{% else %}-->
              <!--  <a class="col-md-2 btn btn-default" name="{{ backend|backend_class }}" href="{% url "social:begin" backend=name %}">-->
              <!--    <i class="fa fa-{{ name|icon_name }}"></i>-->
              <!--    {{ backend|backend_name }}-->
              <!--  </a>-->
              <!--{% endif %}-->
            {% endfor %}
          </div>
        {% endfor %}
```

But once I load the homepage with the login code, it automatically signs in with the initial Google account, without letting me use local accounts or another Google account.

I've tried googling and stackoverflow without much luck and I'm stuck, so help is appreciated.

**Comment by Menda** [comment]
I'm having the same problem. I tried also all posibilities, and I have no clue how can this being solved. Maybe @omab knows the reason.

**Comment by omab** [comment]
The problem here is that the auth mechanism is done by the Google SDK and loggin out of your application, doesn't mean logging out of your Google account, which is then verified by the SDK when the page is reloaded, and the user is authenticated again.

This https://developers.google.com/+/web/signin/sign-out seems to be the fix to the problem.

**Comment by Menda** [comment]
Yes, this JS call function is exactly what I tried, but didn't work, but I think it's because some people are reporting that the logout function doesn't work on localhost. When I have it tested, I will update the Google README file on how to procedure for this functionality.

**Comment by epetxepe** [comment]
I've opted for an approach to show Logout for local users and Disconnect for python-social-auth, and to revoke the token given by Google plus, so when I try to login next time, it does not log in automatically and I can either log with local accounts or python-social-auth (having to give permission again).

I had to set the following in the settings.py file to revoke the given token:
SOCIAL_AUTH_REVOKE_TOKENS_ON_DISCONNECT = True
and 
To make the changes I suggest at https://github.com/omab/python-social-auth/issues/484

The sign-out procedure reported above seems the most natural way.

**Comment by omab** [comment]
@epetxepe, disconnect will remove the association between the google account and the user in your db, you will need ``association by email`` to reconnect that account later.

**Comment by omab** [comment]
@Menda, maybe it's broken for ``localhost``, but what happens if you setup an entry ``/etc/hosts`` to point to your local IP?

**Comment by epetxepe** [comment]
Dear @Menda @omab, 

   I've tried to use the SDK sign out solution (https://developers.google.com/+/web/signin/sign-out), and I've not been able to make the solution work. I've tried testing locally and from remote machines. 

  I've implemented the following:

  <script>
      function signOut() {
        var auth2 = gapi.auth2.getAuthInstance();
        auth2.signOut().then(function () {
          console.log('User signed out.');
          window.location ="https://127.0.0.1:8000/logout";     
        });
      }
      function onLoad() {
         gapi.load('auth2', function() {
           gapi.auth2.init();
         });
       }
    </script>
    <script src="https://plus.google.com/js/client:plusone.js?onload=onLoad" async defer></script>
    ...
    <a href="#" onclick="signOut();">Sign out</a>

I receive the console.log('User signed out.'); message and logout executes but it is automatically logged again.

Any pointers / example how you have implemented this?
How can I check at debug level if the user has been signed out?

**Comment by Menda** [comment]
Hi @epetxepe . In my case I also have the same problem as you, because after using the sign out also the users sign in again. This is not only happening in localhost, but in all servers. Let's see if anybody comes with a solution and document it.

**Comment by omab** [comment]
@epetxepe, @Menda, I've updated the docs (http://psa.matiasaguirre.net/docs/backends/google.html#google-sign-in) and the example application (https://github.com/omab/python-social-auth/blob/master/examples/django_example/example/templates/home.html#L331-L376) to an up-to-date SDK usage.

**Comment by epetxepe** [comment]
@omab Thanks for the updates, but I've not been able to get it working correctly.
I've tried:
    1.- Updated example. I'm receiving the following error from Google: 

400. That’s an error.
Error: invalid_request
Application: Si elegans web platform
You can email the developer of this application at: ------------@gmail.com
Permission denied to generate login hint for target domain.
Request Details
openid.realm=
scope=email profile openid https://www.googleapis.com/auth/plus.login
response_type=permission
redirect_uri=storagerelay://http/127.0.0.1:8000?id=auth720879
ss_domain=http://127.0.0.1:8000
client_id=--------------------------
fetch_basic_profile=true

I've tried it with 127.0.0.1 and localhost. Updated Google Developer Console with http://127.0.0.1/* to match redirect_uri following http://stackoverflow.com/questions/29201763/google-sign-in-is-not-working 

No luck.

    2.- Updated my original code with updated documentation http://psa.matiasaguirre.net/docs/backends/google.html#google-sign-in, but the same automatically sign-in after sign-out is repeated. Is there a way to see the changes is your documentation html? 


The documentation does not reflect sign out usage and the updated example makes a SDK usage not introduced in the documentation. The example makes a more clear use of the Google's JS SDK objects, while documentation reflects the callback way, which keeps calling complete/google_plus when the https://apis.google.com/js/client:plusone.js is loaded.

**Comment by omab** [comment]
@epetxepe, there's an explicit logout example in the docs now, maybe you see a cached version of the page? The changes to the docs are in the repo, this is the particular commit https://github.com/omab/python-social-auth/commit/a4918af20e09642b8ee47724a023899ef93fd22b

**Comment by epetxepe** [comment]
@omab yes my browser was rendering a cached version. Sorry for that.

I've tried both the example and the documentation on my dev having to change the following:
**1.- To fix the error:**

 Error: invalid_request Application: Si elegans web platform You can email the developer of this application at: ------------@gmail.com Permission denied to generate login hint for target domain. Request Details openid.realm= scope=email profile openid https://www.googleapis.com/auth/plus.login response_type=permission redirect_uri=storagerelay://http/127.0.0.1:8000?id=auth720879 ss_domain=http://127.0.0.1:8000 client_id=-------------------------- fetch_basic_profile=true

**Change:** Updated Google Developer Console with `http://127.0.0.1:8000/*` & `http://localhost:8000/*` .  **It only works for localhost:8000**
**2.- To fix the error:**
Internal Server Error: /complete/google-plus
Traceback (most recent call last):
  File "C:\Users\gepelde\.virtualenvs\sielegans\lib\site-packages\django\core\handlers\base.py", line 87, in get_response
    response = middleware_method(request)
  File "C:\Users\gepelde\.virtualenvs\sielegans\lib\site-packages\django\middleware\common.py", line 82, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/complete/google-plus/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.

**Change:** Added an extra slash at the of  $form.attr("action", "/complete/google-plus"); --- from documentation or substitute with the line from example $form.attr("action", "{% url "social:complete" backend="google-plus" %}"); 
     I've proposed a change in github

**I'm stuck at error:**(On both example and my own dev)
Missing needed parameter access_token or **code**
Request Method:	POST
Request URL:	https://localhost:8000/complete/google-plus/
Django Version:	1.7.1
Exception Type:	AuthMissingParameter
Exception Value:	
Missing needed parameter access_token or **code**

I've updated your javascript to fill the code value, but I don't know where to get the **code** from the authResponse object. In the old version it was coming from the callback. 

```
 $form = $("<form>");
$form.attr("action", "{% url "social:complete" backend="google-plus" %}");
$form.attr("method", "post");
$input_access_token = $("<input>");
$input_access_token.attr("name", "access_token");
$input_access_token.attr("value", authResponse.access_token);
$form.append($input_access_token);
**$input_code = $("<input>");**
**$input_code.attr("name", "code");**
**$input_code.attr("value", authResponse.code);**
$form.append($input_code);
// Add csrf-token if needed
$(document.body).append($form);
$form.submit();
```

Checking the /complete/google-plus/ request I've seen that code is being sent empty, while in the old version, there is a string filled.

**As a results I'm stuck in the error**:

AuthCanceled at /complete/google-plus/
Authentication process canceled
Request Method:	POST
Request URL:	https://localhost:8000/complete/google-plus/
Django Version:	1.7.1
Exception Type:	AuthCanceled
Exception Value:	
Authentication process canceled

I've checked the AuthResponse object at https://developers.google.com/identity/sign-in/web/reference , but not sure if any of its properties is the old version's **code** value. 

Could you please provide advice on this?

**Comment by omab** [comment]
There's no ``code`` anymore for this authentication mechanism and a change was introduced to take that into account properly in the backend, you need to pull the changes from the repository since it's not released yet.

**Comment by epetxepe** [comment]
Thanks @omab, got both sign-in and log-out working with the latest version and no auto-login.
