### ISSUE TITLE
Pyramid Authentication Policies

### ISSUE THREAD

**Issue by marinewater** [omab/python-social-auth#321]
Is there a reason why python-social-auth doesn't use the [Authentication Policies of Pyramid](http://docs.pylonsproject.org/projects/pyramid/en/1.5-branch/api/authentication.html)? The random session cookie is kind of pointless if you have permissions set up.

**Comment by cjltsod** [comment]
With this pull request, Pyramid Authentication Policies could run smoothly. 

I'm able to write an example with Pyramid Authentication Policies, but I'm not sure what directory name should I use.

**Comment by omab** [comment]
Issue ported to https://github.com/python-social-auth/social-app-pyramid/issues/1
