### ISSUE TITLE
/complete/google-oauth2/ produces timeout error.

### ISSUE THREAD

**Issue by jenia** [omab/python-social-auth#324]
When I try to login using google, I get redirected (after i filled in the form) here:

```
/complete/google-oauth2/
```

And then the connection times out.

```
504 Gateway Time-out
```

I tried to see if the server can connect to google's api. I don't know if this means it can't or can.

```
wget https://accounts.google.com/o/oauth2/token

--2014-07-10 15:20:59--  https://accounts.google.com/o/oauth2/token

Resolving accounts.google.com (accounts.google.com)... xxxx:xxxx:xxxx:xxx::xx, xx.xxx.xxx.xx

Connecting to accounts.google.com (accounts.google.com)|xxxx:xxxx:xxxx:xxx::xx|:xxx... failed: Connection timed out.

Connecting to accounts.google.com (accounts.google.com)|xx.xxx.xxx.xx|:xxx... connected.
HTTP request sent, awaiting response... 405 Method Not Allowed
2014-07-10 15:23:06 ERROR 405: Method Not Allowed
```

I just want to say that doing the same wget from my home produces the 405 ERROR, but not the time out error. So i think it's possible that there might be something wrong with the network.

The time on my server was first the default, and then i switched it to the one you see there which is the one in my home.
.

If anyone could help, that would be great. 

Thanks in advance.
jenia

**Comment by scuml** [comment]
Ran into the same error using Google Auth with Celery Flower on Safari 8.0.2.  Auth redirect worked fine in Chrome, but 504'd in Safari.

**Comment by domino14** [comment]
I'm seeing this as well with Facebook.

**Comment by domino14** [comment]
@scuml @jenia have any of you figured out what caused this?

**Comment by scuml** [comment]
No - have yet to find a solution.  Ended up just using Chrome as a workaround.

**Comment by domino14** [comment]
My issue was that I had no Internet connectivity from inside my Docker container on prod - not related to this. FWIW Safari and my Google social auth work fine on prod... Thanks for letting me know.
