### ISSUE TITLE
remove incomplete partial pipeline data from session

### ISSUE THREAD

**Issue by omat** [omab/python-social-auth#325]
When for example email address is submitted and a validation mail is sent, if the user decides to login with another email address, the session data is not updated thus still the first email address is taken into account.

I think when a partial pipeline is started, existing one should be checked and removed from the session. 

Thanks for the efforts...

**Comment by omab** [comment]
The values are needed in the session to continue any type of partial pipeline, sending a mail validation is a partial pipeline too.

**Comment by omat** [comment]
Sure, but for example when a new email validation is started, any existing partial pipeline session data should be invalidated and the newly started pipeline data should be used. In the current situation, the old one persists, never letting a new validation to be started. Thus, if you enter a wrong email address, there is no way you can correct it, without cleaning the session data explicitly.

**Comment by omab** [comment]
I've added code to invalidate the pipeline when a new login/signup process is started, I can't do any cleanup on a pipeline, because at the time it's called data was already loaded and the whole process might be wrong.
