### ISSUE TITLE
south migration for django app?

### ISSUE THREAD

**Issue by pcompassion** [omab/python-social-auth#331]
I got an error with google:

    DataError at /auth/complete/google-oauth2/
    value too long for type character varying(16)

No where in django model source code (of python social auth) has 16 length, and looked at postgresql DB, and UID of social_auth_usersocialauth has 16 length!

I can fix this by manually altering postgresql schema.  

It would be good for django users to have a documentation about DB schema change.  
Especially since "syncdb" database is different from the python social auth model code. (wonder why!)

**Comment by omab** [comment]
There are migrations for django and south in the app.
