### ISSUE TITLE
Django - Google Authentication - Create Account

### ISSUE THREAD

**Issue by spirit2343** [omab/python-social-auth#362]
When a users authenticates using google account an account is created on the local database where the user name is his first name. That is a problem for two reasons: 1. I ve had legit users making account where the first name is 2 words in which case the user name has spaces. 2. its pretty common 2 people to have the same first name. What happens in this case?

Thank you!

**Comment by omab** [comment]
The lib avoids username collisions by appending a hash if one is detected. It's possible to "slugify" usernames to remove spaces (and other characters), just set ``SOCIAL_AUTH_SLUGIFY_USERNAMES = True``.
