### ISSUE TITLE
Google OAuth2 gives 400 error, FB 500 error

### ISSUE THREAD

**Issue by rca** [omab/python-social-auth#364]
"Everything was working fine" and all of a sudden both the authentication backends I have setup error out.  The following Google URL errors out with 400:

```
https://accounts.google.com/o/oauth2/auth?scope=email+profile&state=xxxx&redirect_uri=http://localhost:8000/complete/google-oauth2/&response_type=code&client_id=xxxx.apps.googleusercontent.com
```

And the following FB URL errors out with a blank 500 screen:

```
https://www.facebook.com/dialog/oauth?scope=email&state=xxxx&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fcomplete%2Ffacebook%2F%3Fredirect_state%3Dxxxx&client_id=xxxx
```

The key and secret are both set using the variables:

```
SOCIAL_AUTH_FACEBOOK_KEY
SOCIAL_AUTH_FACEBOOK_SECRET
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
```

The redirects to the backends work fine, just that the backend itself, i.e. Google and FB, blow up.  Any ideas?

Thanks!

**Comment by omab** [comment]
It's been a while and this didn't happened again, I'm closing he issue, reopen if needed.
