### ISSUE TITLE
Shopify Backend

### ISSUE THREAD

**Issue by gmehta-personal** [omab/python-social-auth#368]
The Shopify Oauth2 flow fails and complains of:

'NoneType' object has no attribute 'strip' here --> self.data.get('shop').strip(). 

Also, there are no clear notes on how to setup Shopify Oauth2 with python-social-auth. Are there any new settings that are required in a django app? 

Have added:
"'social.backends.shopify.ShopifyOAuth2' --> to AUTHENTICATION_BACKENDS
and,
SHOPIFY_APP_API_KEY, SHOPIFY_SHARED_SECRET,SHOPIFY_API_SCOPE.

Am I missing anything?

**Comment by webjunkie** [comment]
The Shopify backend is broken for me as well. Looking at the code, `self.data` is never populated, so the Shopify client has no way to tell which store I have. I solved this by adding a `SOCIAL_AUTH_SHOPIFY_SHOP` setting. There also appears an error later where it is looking for a dict which isn't there. Should I submit a PR?

**Comment by webjunkie** [comment]
Mhm, well, `SOCIAL_AUTH_SHOPIFY_SHOP` does not make sense if you want any random shop to sign in, of course.

I now figured out that it works by going to `/login/shopify/?shop=testshop`. Is this documented somewhere?

**Comment by m-misseri** [comment]
Hi there,

I have the same problem. 

If I go to http://127.0.0.1:8000/login/shopify/
I got this error:

```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/login/shopify/

Django Version: 1.8.5
Python Version: 2.7.14
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django.contrib.admin',
 'main',
 'main.templatetags',
 'users',
 'questions',
 'dashboard',
 'tinytests',
 'common',
 'spike',
 'adm',
 'social.apps.django_app.default',
 'compressor',
 'django.contrib.sitemaps',
 'djcelery',
 'redactor',
 'corsheaders')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.cache.UpdateCacheMiddleware',
 'htmlmin.middleware.HtmlMinifyMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'main.middleware.AccountNotConfirmedMiddleware',
 'main.middleware.NoMailMiddleware',
 'main.middleware.UpdateLastActivityMiddleware',
 'social.apps.django_app.middleware.SocialAuthExceptionMiddleware',
 'django.middleware.cache.FetchFromCacheMiddleware',
 'htmlmin.middleware.MarkRequestMiddleware',
 'main.middleware.UserUidMiddleware',
 'main.middleware.UserHistoryInfo',
 'main.middleware.UserReferredMiddleware',
 'main.middleware.UserCouponMiddleware')


Traceback:
File "/Users/fraf9/Sites/saldd/ve/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/fraf9/Sites/saldd/ve/lib/python2.7/site-packages/social/apps/django_app/utils.py" in wrapper
  45.             return func(request, backend, *args, **kwargs)
File "/Users/fraf9/Sites/saldd/ve/lib/python2.7/site-packages/social/apps/django_app/views.py" in auth
  12.     return do_auth(request.social_strategy, redirect_name=REDIRECT_FIELD_NAME)
File "/Users/fraf9/Sites/saldd/ve/lib/python2.7/site-packages/social/actions.py" in do_auth
  25.     return strategy.start()
File "/Users/fraf9/Sites/saldd/ve/lib/python2.7/site-packages/social/strategies/base.py" in start
  66.             return self.redirect(self.backend.auth_url())
File "/Users/fraf9/Sites/saldd/ve/lib/python2.7/site-packages/social/backends/shopify.py" in auth_url
  50.             self.data.get('shop').strip(),

Exception Type: AttributeError at /login/shopify/
Exception Value: 'NoneType' object has no attribute 'strip'
```

If I go to http://127.0.0.1:8000/login/shopify/?shop=myshourl.myshopify.com

`unbound method create_permission_url() must be called with Session instance as first argument (got unicode instance instead)`
--

Any ideas?
Let me know,
Thank you very much.

**Comment by m-misseri** [comment]
@webjunkie do you solve in some way?

**Comment by m-misseri** [comment]
Solved by updating the shopify.py file with the last version.

Still some problem with this:
https://www.evernote.com/l/AOYJgsn_qX9Jm6G8541I50hgoTpI0ch29XU

(I've already added 127.0.0.1:8000/complete/shopify/ to shopify app settings, of course.)

**Comment by m-misseri** [comment]
This happen because python social app is generating a "http://127.0.0.1:8000/complete/shopify/ ?redirect_state=RandXXXXX" and this does not match with http://127.0.0.1:8000/complete/shopify/ inserted into shopify settings.

Any ideas on how to solve this matter?

**Comment by webjunkie** [comment]
I tried to remember what issue that was, and found this here:

https://github.com/omab/python-social-auth/commit/97d006bd9377e1db078a3e1c8f51b1f584dc3b8b

But now since this library changed so much, I don't know if the change is still in.
