### ISSUE TITLE
Users must have an email address

### ISSUE THREAD

**Issue by wadewilliams** [omab/python-social-auth#375]
Seeing a problem with Facebook integration. Using Django. Here is our Social Auth config:

```
SOCIAL_AUTH_USER_MODEL = AUTH_USER_MODEL
SOCIAL_AUTH_CREATE_USERS = True
SOCIAL_AUTH_UUID_LENGTH = 2
SOCIAL_AUTH_BACKEND_ERROR_URL = LOGIN_URL

SOCIAL_AUTH_CHANGE_SIGNAL_ONLY = True

SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    'social.pipeline.social_auth.associate_by_email',
    'social.pipeline.user.create_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'authentication.services.authentication.socialSendActivationEmail', # Custom
    'social.pipeline.user.user_details',
)

SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/auth/loggedin/'
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/auth/loggedin/'
SOCIAL_AUTH_SLUGIFY_USERNAMES = True
SOCIAL_AUTH_RAISE_EXCEPTIONS = False
```

![valueerror__users_must_have_an_email_address___lm_production___sentry](https://cloud.githubusercontent.com/assets/1676891/4137573/65f2982c-3388-11e4-8f02-a689207a1d91.png)

The strange thing is, that the email field is just coming across as blank.

![valueerror__users_must_have_an_email_address___lm_production___sentry](https://cloud.githubusercontent.com/assets/1676891/4137592/8fe9eedc-3388-11e4-81f4-76521f47d5d6.png)

@omab Any help here would be much appreciated, this is a production bug we are chasing down at this point :(

**Comment by harshmaur** [comment]
Dont you think this could happen when a user registers with a phone number on facebook instead of an email id.
