### ISSUE TITLE
Any plans to support SAML?

### ISSUE THREAD

**Issue by jacobg** [omab/python-social-auth#388]
http://en.wikipedia.org/wiki/SAML_2.0
https://github.com/rohe/pysaml2

**Comment by pitbulk** [comment]
Other python library:  https://github.com/onelogin/python-saml

**Comment by jacobg** [comment]
As a general mission for this project, do you think it would be worthwhile to incorporate the corporate login providers such as OneLogin and Okta into python-social-auth? I think the standard for corporate space is to use SAML, so perhaps integrating SAML would then give this project more corporate value.

**Comment by bradenmacdonald** [comment]
@omab I am likely going to be implementing a python-social-auth SAML backend in the near future as part of bringing Shibboleth support to the software I work on (edX). It will depend on python-saml (linked two comments up), which in turn has a few other requirements and is only compatible with Python 2.7. Would you be willing to include that backend in python-social-auth, given the extra requirements and lack of Python 3 support? We'd love to contribute it so others can use it, if possible.

**Comment by pitbulk** [comment]
@omab @bradenmacdonald I'm working on a python3 version of the python-saml.
https://github.com/pitbulk/python3-saml

Other alternative is to use [pysaml2](https://github.com/rohe/pysaml2)

**Comment by bradenmacdonald** [comment]
@pitbulk Glad to hear that; I wasn't sure of the status of that fork and if it was going to be made "official" at some point.

**Comment by pitbulk** [comment]
Yes, I plan to publish it soon, now is in testing phase. Feedback welcome ;)

**Comment by ashchristopher** [comment]
@bradenmacdonald I am looking at creating a SAML backend for python-social-auth as well - would you be interested in collaborating?

**Comment by bradenmacdonald** [comment]
@ashchristopher I have already more or less finished an implementation: https://github.com/omab/python-social-auth/pull/616 . Just waiting for review and feedback. Check it out and I'd be curious to know if it works for your use case or not.

**Comment by vsobolmaven** [comment]
Apparently a few of abstract methods are still not implement in pyramid_strategy.py to make saml work with pyramid. They are request_post(), request_get(), request_path(), request_is_secure(). Would be great to see this fixed. Thanks.

**Comment by bradenmacdonald** [comment]
@vsobolmaven Those should be quite simple to implement - I recommend you implement that yourself and open a pull request here to contribute it to the project.

**Comment by pdurbin** [comment]
I was wondering why @omab closed this issue but from reading https://github.com/omab/python-social-auth/issues/778#issuecomment-269242569 it sounds like SAML is supported these days. Sure enough, pull request #616 by @bradenmacdonald was merged a while back. Great! Thanks!
