### ISSUE TITLE
Django: Google+ disconnect does not actually disconnect

### ISSUE THREAD

**Issue by robert-osborne** [omab/python-social-auth#394]
If I disconnect Google+ from an account and return to my account management page, Google Plus sign-in automatically triggers and re-connects itself.

This is because the token remains in the users account and has not been removed.

**Comment by Menda** [comment]
Same as here: https://github.com/omab/python-social-auth/issues/316

**Comment by omab** [comment]
That's becuase Google JS API triggers back the login and doesn't remember that the user requested to be logged out or disconnected. Upon disconnect you need to call this https://developers.google.com/+/web/signin/sign-out.
