### ISSUE TITLE
Import error: no module named google_auth

### ISSUE THREAD

**Issue by DataSwede** [omab/python-social-auth#423]
I have previously been successful at implementing Google OAuth2 authentication with python social auth after following along this tutorial: http://www.artandlogic.com/blog/2014/04/tutorial-adding-facebooktwittergoogle-authentication-to-a-django-application/

Now, I'm getting an ImportError, no module named google_auth that is a result of an error arising during template rendering, specifically pointing at this line:

<a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">Login</a>

Looking through the traceback, it looks like django is either not using social's template context processors, or there is an issue with a reference within social.

**Comment by omab** [comment]
There's no such import in the app, probably something you copied from some other place?

Closing, reopen if needed.
