### ISSUE TITLE
Django 1.7 warning - You have unapplied migrations

### ISSUE THREAD

**Issue by mtirsel** [omab/python-social-auth#426]
Current migration for Django 1.7 is missing related_name argument for the UserSocialAuth.user field. If calling makemigrations command, this creates migration 0002 in social default app. AFAIK related_name shouldn't do any changes in database, so it should be safe to just add related_name=b'social_auth' argument to the CreateModel fields in 0001_initial.py.

**Comment by mtirsel** [comment]
Any progress? This is causing a lot of problems in automated builds/deployments and is easy to fix.

**Comment by stevejalim** [comment]
@mtirsel Have you tried my fork, above? If it works for you in your automated builds, too, I'll issue a pull request to @omab

**Comment by bendavis78** [comment]
See above pull request. The fix was to remove the `b` prefix on the default_value for the `extra_data` field. This bug appears to have been introduced by 587da255.
