### ISSUE TITLE
AuthAlreadyAssociated at /complete/google-oauth2/

### ISSUE THREAD

**Issue by crobertsbmw** [omab/python-social-auth#437]
Basically, if I login via google, then I logout, and then create an account manually (using a signup form), and then try try again to login via google (without first logging out, basically connecting the two accounts, one of which is already connected). Then it throws an error during the authentication pipeline. And I don't see any way to properly deal with the exception.  Is there a way to catch exceptions from the auth pipeline? I'm not finding any.

**Comment by ghost** [comment]
I solved it by inserting below code in settings
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.user.user_details',
)

**Comment by fercreek** [comment]
^ This worked for me
