### ISSUE TITLE
Bugs in tornado_strategy.py

### ISSUE THREAD

**Issue by artemmus** [omab/python-social-auth#445]
There are bugs in tornado strategy (tornado_strategy.py) which does not allow using ?next=/foo in login redirect. To fix them it is necessary to replace with these functions: 

    def request_data(self, merge=True):
        return {k: v[0] for k, v in self.request.arguments.iteritems()}

    def session_get(self, name, default=None):
        val = self.request_handler.get_secure_cookie(name)
        return val or default

P.S.
Why it so, see in tornado documentation.

**Comment by omab** [comment]
I've pushed the changes, could you give it a try?

**Comment by artemmus** [comment]
Yes, it works.
