### ISSUE TITLE
Provide integration with Django REST Framework (authentication and permissions)

### ISSUE THREAD

**Issue by jeverling** [omab/python-social-auth#448]
First of all thanks a lot for this great project! It's amazing how many providers are supported and how well everything works. Something I'm missing is authentication that is not session based like API calls. There are a lot of questions and posts regarding authenticating accounts created by python-social-auth when working with an API created with Django REST Framework. Some examples:

http://stackoverflow.com/questions/26658130/how-to-authenticate-by-access-token-in-code-using-python-social-auth
https://groups.google.com/forum/#!topic/django-rest-framework/ACKx1kY7kZM
http://blog.wizer.fr/2013/11/angularjs-facebook-with-a-django-rest-api/

However, all these questions and posts suggest to use something like the use-case from the docs (http://psa.matiasaguirre.net/docs/use_cases.html#signup-by-oauth-access-token) and maybe an additional auth_by_token endpoint which allows to check if a token is valid. But if you want to do stateless API calls, that is not enough, since you don't have sessions in this case. So it is necessary to check access_tokens against the DB, like it is done by e.g. http://www.django-rest-framework.org/api-guide/authentication#django-oauth-toolkit (there are more options for DRF, but this seems to be the most active project and supports Python 3).
django-oauth-toolkit provides an AUTHENTICATION_CLASS and Permission classes to check for scopes.
It would be great if python-social-auth had the same, to be able to make requests with bearer tokens and authenticate users that way.

**Comment by hugocore** [comment]
Hi @jeverling!

You can now authenticate your users with bearer tokens from any python-social-auth backend using this library https://github.com/PhilipGarnero/django-rest-framework-social-oauth2

Best regards

**Comment by X17** [comment]
@hugocore 

Hey does it support client apps such as AngularJS, iOS, Android where the authentication of social network is done by native sdk in return which gives "Access token" and then sent to server side for authentication.

For instance,  Mobile app using Facebook login which authenticates within app and returns Facebook access token which is used at server side to retrieve user data.

if not, any suggestion to implement
