### ISSUE TITLE
StravaOAuth - Strava authentication backend not working.

### ISSUE THREAD

**Issue by filonik** [omab/python-social-auth#455]
It appears that the Strava backend is not working properly. I am getting the following response:

HTTPError at /complete/strava/
401 Client Error: Unauthorized

The other authentication backends I have tried are working fine. I would not rule out that it's a configuration issue, but I have double checked all the settings and they seem correct to me.

**Comment by buddylindsey** [comment]
Have you gotten this to work? I recently just started using it and it seems to work for me. If it isn't working for you still can you show some code.

**Comment by filonik** [comment]
Yes, I would love to figure out what is going wrong. It is still the only backend that isn't working for me. The traceback contains the following, which sounds like the request for an authentication token comes back with a 401:

    '/app/src/python-social-auth/social/backends/base.py' in 'request'

    args ()
    url 'https://www.strava.com/oauth/token'
    method 'POST'
    kwargs {
        'data': {
            'client_id': <MY_CLIENT_ID>,
            'client_secret': <MY_CLIENT_SECRET>,
            'code': <CODE>,
            'grant_type': 'authorization_code',
            'redirect_uri': 'http://<MY_DOMAIN>/complete/strava/'},
        'headers': {
            'Accept': 'application/json',
            'Content-Type': 'application/x-www-form-urlencoded'
        },
        'timeout': None
    }
    response <Response [401]>
