### ISSUE TITLE
Docs for SOCIAL_AUTH_PROTECTED_USER_FIELDS misleading

### ISSUE THREAD

**Issue by SeanHayes** [omab/python-social-auth#459]
http://psa.matiasaguirre.net/docs/configuration/settings.html#miscellaneous-settings

"Set this to a list of fields you only want to set for newly created users and avoid updating on further logins."

Fields other than username and email specified in this setting don't get set on creation though.

**Comment by omab** [comment]
Docs updated, http://psa.matiasaguirre.net/docs/configuration/settings.html#miscellaneous-settings
