### ISSUE TITLE
Yahoo OAuth 2?

### ISSUE THREAD

**Issue by jacobg** [omab/python-social-auth#463]
Currently python-social-auth only has an OAuth1 implementation.

https://developer.yahoo.com/oauth2/guide/

**Comment by omab** [comment]
Yahoo OAuth2 was implemented a while back http://psa.matiasaguirre.net/docs/backends/yahoo.html#yahoo-oauth2

**Comment by jacobg** [comment]
Great, thanks so much @omab.
