### ISSUE TITLE
Trouble fetching access_code from authorizationCode

### ISSUE THREAD

**Issue by rchrd2** [omab/python-social-auth#465]
Hello, Ember Torii (http://vestorly.github.io/torii/demo.html) is a front-end library that supplies an "authorizationCode" which can be sent to a server. In my case I'm sending it to an API bulid with python.

I am trying to use this library to retrieve an `access_token` from that `code`. I tried various things, but it seems hard to piece out the part that would grab the access_token credentials. Python-social-auth seems to make the assumption that you're running within a framework and it is difficult to use in a minimal scripted manner.

I cannot find a way to fetch an `access_token` from a `code`.

```
>>> from social.backends import facebook
>>> f = facebook.Facebook2OAuth2()
>>> f.request_access_token('foobar')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/venv/local/lib/python2.7/site-packages/social/backends/oauth.py", line 344, in request_access_token
    return self.get_json(*args, **kwargs)
  File "/venv/local/lib/python2.7/site-packages/social/backends/base.py", line 226, in get_json
    return self.request(url, *args, **kwargs).json()
  File "/venv/local/lib/python2.7/site-packages/social/backends/base.py", line 212, in request
    kwargs.setdefault('timeout', self.setting('REQUESTS_TIMEOUT') or
  File "/venv/local/lib/python2.7/site-packages/social/backends/base.py", line 29, in setting
    return self.strategy.setting(name, default=default, backend=self)
AttributeError: 'NoneType' object has no attribute 'setting'
>>> 
```

I would suggest keeping things isolated so developers can cherrypick functions from this library. As it stands, it seems like my options are either"
1. Use the full stack that this provides, or 
2. Implement this on my own

Idea for usage:

```
>>> from social.backends import facebook
>>> f = facebook.Facebook2OAuth2()
>>> f.settings('KEY', 'FOO')
>>> f.settings('SECRET', 'BAR')
>>> f.request_access_token('foobar')
{'access_token': '123456789'}
```

If this is already possible, what is the necessary code? 

Thank you.

**Comment by MajorTal** [comment]
+1

**Comment by omab** [comment]
Using PSA isolated from a framework is not 100% supported (yet), the recent [split into smaller modules](https://github.com/python-social-auth) should make that possible in the future.
