### ISSUE TITLE
SOCIAL_AUTH_LINKEDIN_FIELD_OAUTH2_SELECTORS Not being used to populate user creation backend

### ISSUE THREAD

**Issue by sshadmand** [omab/python-social-auth#466]
I have set the SOCIAL_AUTH_LINKEDIN_FIELD_OAUTH2_SELECTORS field in my Django Settings. I know that it is being used becuase when I remove the field I get an error when accessing the backend. However when I use it and include the selectors I want it is not being merged into the default selectors listed.

The attached screenshot results in only the default selectors being printed to the screen:

![screen shot 2014-12-12 at 3 01 17 pm](https://cloud.githubusercontent.com/assets/68735/5420874/d2a278f4-820f-11e4-9add-910a6bbc73f9.png)

**Comment by omab** [comment]
That's because the setting name is ``SOCIAL_AUTH_LINKEDIN_OAUTH2_FIELD_SELECTORS``.
