### ISSUE TITLE
 How to take the user's address on facebook? This has already been implemented?

### ISSUE THREAD

**Issue by messias-physics** [omab/python-social-auth#470]
First, thank you!

My question is as follows:

The user name is saved in social_auth_usersocialauth as follows

username =First Name + Last Name or Last Name + First Name,

But I would like to get the real username (endereçousername) of facebook http://www.facebook.com/adreessusername.

  I can get this value indirectly, but there is an easier way to do this?

**Comment by yaniv14** [comment]
I don't think you can get it directly from facebook in the response.
Also not all profile pages are first and last name combined.
I am using this link to get redirect to the user page.
https://www.facebook.com/app_scoped_user_id/<user_id>/

<user_id> value you get with the response.

**Comment by omab** [comment]
You can hit ``http://graph.facebook.com/USER-ID``, it will return a JSON response with a ``link`` key with the profile URL. Also you can hit ``http://www.facebook.com/100000526626030`` and catch the redirect Location.
