### ISSUE TITLE
Spotify setting names are incorrect.

### ISSUE THREAD

**Issue by ctbarna** [omab/python-social-auth#475]
The "app key" and "app label" settings in the [Spotify docs](https://github.com/omab/python-social-auth/blob/master/docs/backends/spotify.rst) is incorrect based on the `name` attribute of the [`SpotifyOAuth2` class](https://github.com/omab/python-social-auth/blob/92219cf7f0aac3e3a2313372ecb3bf63f5ba0185/social/backends/spotify.py#L12). With the current `name` attribute, the settings should be:

```
SOCIAL_AUTH_SPOTIFY_KEY = ''
SOCIAL_AUTH_SPOTIFY_SECRET = ''
```

However, I think the "real" bug might just be that the `name` attribute is incorrect on that class.

**Comment by omab** [comment]
Fixed, thanks!
