### ISSUE TITLE
Support Facebook Graph API 2.2

### ISSUE THREAD

**Issue by Gromph** [omab/python-social-auth#480]
To support Graph API 2.2 I created a subclass, and updated the version in the urls. Is this all that should be needed? Everything seems to work ok for me so far.

class Facebook22OAuth2(Facebook2OAuth2):
    """Facebook OAuth2 authentication backend using Facebook Open Graph 2.2"""
    AUTHORIZATION_URL = 'https://www.facebook.com/v2.2/dialog/oauth'
    ACCESS_TOKEN_URL = 'https://graph.facebook.com/v2.2/oauth/access_token'
    REVOKE_TOKEN_URL = 'https://graph.facebook.com/v2.2/{uid}/permissions'
    USER_DATA_URL = 'https://graph.facebook.com/v2.2/me'

**Comment by gfranxman** [comment]
Same here, FYI.   Worked like a charm.

**Comment by omab** [comment]
Sorry about the delay, I've updated it to ``v2.3`` (which changed the message response from querystring to json).
