### ISSUE TITLE
Microsoft Live Oauth2  Error

### ISSUE THREAD

**Issue by wj1918** [omab/python-social-auth#483]
With "Enhanced redirection security:" always enabled now.  The redirect url has to be same as it is defined. Please set REDIRECT_STATE = False.

**Comment by wj1918** [comment]
Just saw a closed issue.
https://github.com/omab/python-social-auth/issues/218
This is still not working.

**Comment by wj1918** [comment]
We are appending redirect_state to the redirect_uri, This cause the failing.

redirect_uri=https://www.example.com/account/social/complete/live/?redirect_state=lmfVxeqIBCtugBWybBo3sGHtMdQh9UXu

We're unable to complete your request
Microsoft account is experiencing technical problems. Please try again later.

**Comment by dineshv** [comment]
I am also facing the same issue. Any idea why this is failing.

**Comment by alvarovelezgalvez** [comment]
Same for me. 2 weeks with no Live! login available.

It's seems to be a general problem, as their analytics URL (to check number of logins) does not work anymore: https://onedrive.live.com/dev/analytics.aspx?id=XXXXXXXXXXXX

**Comment by wj1918** [comment]
I created a pull request to set redirect_state to false.

**Comment by omab** [comment]
Closed by #563
