### ISSUE TITLE
revoke_token_params &  revoke_token_headers are missing for GooglePlusAuth

### ISSUE THREAD

**Issue by epetxepe** [omab/python-social-auth#484]
Disconnect with revoke (SOCIAL_AUTH_REVOKE_TOKENS_ON_DISCONNECT = True) is giving me errors because the params and headers for revoke are not being filled. 

In "backends/google.py" GooglePlusAuth is missing revoke_token_params &  revoke_token_headers, and it is taking the default ones which fills them with empty values. 

Filling with the Google Oauth2 values it works well:

def revoke_token_params(self, token, uid):
        return {'token': token}

def revoke_token_headers(self, token, uid):
        return {'Content-type': 'application/json'}

**Comment by omab** [comment]
Revoke methods moved to the base class.
