### ISSUE TITLE
Unique constraint on nonce missing

### ISSUE THREAD

**Issue by candlejack297** [omab/python-social-auth#490]
The docs say, 
`SOCIAL_AUTH_NONCE_SERVER_URL_LENGTH = <int>
Nonce model has a unique constraint over ('server_url', 'timestamp', 'salt'), salt has a max length of 40, so server_url length must be tweaked using this setting.`
but I don't actually see this being enforced anywhere nor any reference to it in the migration or model.

**Comment by omab** [comment]
Closed by #491
