### ISSUE TITLE
GooglePlus and OpenID

### ISSUE THREAD

**Issue by DavidHwu** [omab/python-social-auth#494]
Any plans on making a change to support GooglePlus via OpenID?
Looking at the sources, I see GooglePlus via Oauth2 is supported, just not OpenID.

Believe this is a straight forward and simple change. 
With Google deprecating Google and OpenID and moving to GooglePlus OpenID in 4/2015... it would be great to have this in place prior.
https://developers.google.com/+/api/auth-migration#oid2

Thanks
David

**Comment by cambonf** [comment]
Hey there,

I opened an issue some weeks ago : https://github.com/omab/python-social-auth/issues/477
And fixed Google OpenID on my fork https://github.com/cambonf/python-social-auth/tree/bug/google-openid-connect

I haven't opened a PR yet. Maybe there's a better solution (I'm quite new to this project) but it works for us.

**Comment by DavidHwu** [comment]
Thanks @cambonf 
Looked at your branch and its very straight forward and in line with the architecture principles of this package... though I am a newbie to this package.

Any chance I can encourage you to do a PR with the owner and merge?  In general I don't like working off branches.  Take a chance, the author seems like a nice fellow.

Thanks
David

**Comment by cambonf** [comment]
Hi sorry for the late answer,

Yup I'll do a PR and see with the owner :)

+
