### ISSUE TITLE
SQLAlchemy non-SQLLite route crashes

### ISSUE THREAD

**Issue by DavidHwu** [omab/python-social-auth#495]
Using the example found in flask_example, changed out the SQLALCHEMY_DATABASE_URI to reflect a PyMySQL connector.  A crash shortly followed as the init_social(app, db).
The reference to db.session is invalid.

I know you example supports both SQLLite (via SQLAlchemy) and Mongo.
Have you checked to see if other SQLAlchemy routes are supported (ie. PyMySQL for my case).
Should we assume a proper session contained with the db object?

Thanks

Ref:
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:@localhost:3306/test'
Screen shot attached:

![pymysql crash](https://cloud.githubusercontent.com/assets/5856387/5906608/d96c3362-a54d-11e4-84a4-082899fda8a4.png)

**Comment by asimcan** [comment]
This seems to be an older version, v0.2.12 works just fine with pymysql

```
def init_social(app, session):
    UID_LENGTH = app.config.get(setting_name('UID_LENGTH'), 255)
    User = module_member(app.config[setting_name('USER_MODEL')])
    _AppSession._set_session(session)
    UserSocialAuth.__table_args__ = (UniqueConstraint('provider', 'uid'),)
    UserSocialAuth.uid = Column(String(UID_LENGTH))
    UserSocialAuth.user_id = Column(Integer, ForeignKey(User.id),
                                    nullable=False, index=True)
    UserSocialAuth.user = relationship(User, backref=backref('social_auth',
                                                             lazy='dynamic'))
```
