### ISSUE TITLE
Jawbone backend problem, AuthCanceled exception.

### ISSUE THREAD

**Issue by rivf** [omab/python-social-auth#497]
Traceback:
http://pastebin.com/zqKCknCb

So everything is successful, I can see jawbone message 

![message]
(http://i.imgur.com/pb4zRat.png)

With this url:
https://jawbone.com/auth/oauth2/auth?scope=basic_read+extended_read+sleep_read+move_read&state=xPjRSrjw97UC7FS5Mi0Ocw2nuFWcItlK&redirect_uri=http://www.test1.com:8000/complete/jawbone/&response_type=code&client_id=7wlC_4ZiucI

Then I click agree (with or without this checkbox) and exception is raised. The traceback on pastebin link is above.

The problem is obviously somewhere in python-social-auth, because basically the jawbone's work is done (you can see url in traceback, it has &code=mGKV_178jYzP0rLxJmQz-DFgyTmy-xwRh7wBkytH1pT_tpMD-scm8s03UMN7dzyJyerH6h6H0l2-fL7a4wREe4eyzy0s7TLyCQDfEZZgjGTOLvajaxYQwT249X_514- ).

I tried with or without custom pipeline.

I also have working code for attaching twitter and facebook accounts to django user account. And they work perfectly.

**Comment by ericflo** [comment]
I've just run into this same problem. Did you ever figure out what it was, or a workaround?

**Comment by rivf** [comment]
Yep, I've fixed it.
Check this: https://github.com/omab/python-social-auth/pull/498
