### ISSUE TITLE
Don't require trailing slashes

### ISSUE THREAD

**Issue by thusoy** [omab/python-social-auth#505]
We run our site without trailing slashes, and has nginx redirect all URLs with a trailing slash to a non-trailing slash version. This however breaks social auth, since all the routes configured require a trailing slash. I've worked around it by not having nginx rewrite the social auth URLs, but is it possible to not require the trailing slash? Would be nice to be able to be consistent about this.

If the social auth apps allow both, you could let your web server redirect to the one you want to use, to avoid having content served on both. Or it could be defined in the social auth settings which version you prefer.

**Comment by pierreant-p** [comment]
+1 ! We have the same workaround in nginx :)

**Comment by DavidHwu** [comment]
+1

**Comment by omab** [comment]
I've flagged the trailing slashes to be optional for Django apps.

FYI, you can drop the built-in URLs and use your own version pointing to the same views, just don't include the built-in ``urls.py``.

**Comment by thusoy** [comment]
@omab Thanks a lot!

**Comment by nicksnell** [comment]
This hasn't really made it optional - it now means everyone using the URL template tag to generate social URLs will do so without a trailing slash. Obviously they can manually rewrite the urls, but it's not ideal as it breaks existing setups. Would this not be better made into a setting/something more flexible?

**Comment by omab** [comment]
@nicksnell, I've pushed a change for that, now the trailing slash is controlled by a setting ``SOCIAL_AUTH_TRAILING_SLASH``, set it to ``True`` (have trailing slashes in URLs) or ``False`` (don't have them). It defaults to ``True`` to keep it backward compatible.

**Comment by nicksnell** [comment]
@omab Wonderful - Thanks!
