### ISSUE TITLE
How To Get Facebook Profile Data

### ISSUE THREAD

**Issue by abdulgaffar** [omab/python-social-auth#506]
Hi all,

I am a new user of python-social-auth. I am not able to fetch facebook profile information. I tried to do lot of search on this topic but nothing seems to be working for me.

Following is my config.

settings.py

SOCIAL_AUTH_URL_NAMESPACE = 'social'
SOCIAL_AUTH_REDIRECT_IS_HTTPS = False
SOCIAL_AUTH_FACEBOOK_KEY = 'mykey'
SOCIAL_AUTH_FACEBOOK_SECRET = 'mytoken'
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email','user_friends','public_profile','user_interests','user_birthday','user_about_me','user_birthday','user_location']

AUTHENTICATION_BACKENDS = (
    'social.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    'social.pipeline.user.create_user',
    'myapp.pipeline.save_profile',  # pipeline to save user profile data.
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details'
)

But in response I am getting only "email", "gender", "birthday" and "location". 
I want other information like "Number of friends", "Intrestes", "Hobbies" etc

**Comment by thomasyates** [comment]
I'm having the same issue as abdulgaffar with facebook scope, while using almost identical settings. If I paste the access token generated into "https://graph.facebook.com/me/permissions?access_token=" I get the following output, and so it seems that no extra permissions are being asked for. How can we use the extra permissions?

{
   "data": [
      {
         "permission": "installed",
         "status": "granted"
      },
      {
         "permission": "public_profile",
         "status": "granted"
      },
      {
         "permission": "email",
         "status": "granted"
      }
   ]
}

**Comment by thomasyates** [comment]
Can anyone reading this please post a link to a repo that uses the extended facebook permissions, so we can compare our settings and see what might be the problem? Thanks

**Comment by yaniv14** [comment]
Hi Thomas,

Did you facebook app approved for all the extra scopes?
You can ask for as many scopes as you want with python social auth request, but you will get with the response only the scopes that approved by your facebook app.

Check your approved items in Status & Reviews tab in facebook developers panel.

**Comment by omab** [comment]
Recently facebook introduced an approval mechanism for scopes, the only ones that don't require approval are ``public_profile``, ``email`` and ``user_friends``, anything else will require Facebook to review your app (you need to submit a request to review it).

Also, many of the scopes don't mean that the data will be available during the auth process automatically, you need to call the Facebook APIs to retrieve it (python-social-auth will only care about the basic data needed to authenticate the user and nothing else).

**Comment by ranjansaga** [comment]
In order to access user's "gender", "birthday" and "location" ,should i get my app reviewed by facebook ?

**Comment by yaniv14** [comment]
Birthday belong to user_birthday scope and it requires facebook review.
Location belong to user_location scope and it also requires review.
Gender is part of public_profile which doesn't need review
