### ISSUE TITLE
Login user with Email address instead of Username

### ISSUE THREAD

**Issue by sarfrajimpinge** [omab/python-social-auth#513]
In my django app I am using email field for user authentication instead of username field. I am using linkedin, facebook and google authentication in this application. when i register or login using facebook or linkedin a oauth token is created and stored in database but user doesn't get login. Does python social-auth allows to get login using email instead of username ? or i have to use pipline to get oauth token and register the user somehow ?

**Comment by abdulgaffar** [comment]
add the following pipline
<code>'social.pipeline.social_auth.associate_by_email',</code>

just above the pipeline <code>'social.pipeline.user.create_user',</code>

The overall pipeline should look like this.

<code>
SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    'social.pipeline.social_auth.associate_by_email',  # <--- enable this one
    'social.pipeline.user.create_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details'
)
</code>

Then for multiple social backend only one user account will be created.

**Comment by omab** [comment]
Python social auth supports loging by email/username, docs are here http://psa.matiasaguirre.net/docs/backends/email.html
