### ISSUE TITLE
Missing migration

### ISSUE THREAD

**Issue by andreipetre** [omab/python-social-auth#516]
I believe you're missing a migration for `social/apps/django_app/default`.

Installing `python-social-auth` and then doing `python manage.py makemigrations` creates another migration for the above mentioned app that looks like this:

```python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocialauth',
            name='user',
            field=models.ForeignKey(related_name='social_auth', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
    ]
```

This may have been missed because unlike South, Django 1.7 treats *any* change to the models as a migration - even adding a `related_name` attribute.

**Comment by omab** [comment]
Thanks for tracking this and posting a pull-request.
