### ISSUE TITLE
Update PyPI

### ISSUE THREAD

**Issue by clintonb** [omab/python-social-auth#523]
@omab would you update the release on PyPI? The latest release, 0.2.1, is 5 months out of date.

**Comment by omab** [comment]
@clintonb, I'll do it shortly

**Comment by rlucioni** [comment]
@omab, any progress here?

**Comment by omab** [comment]
Hi, ``v0.2.2`` was just released to pypi.

**Comment by rlucioni** [comment]
Thank you very much!

**Comment by clintonb** [comment]
Thanks!
