### ISSUE TITLE
upstream sent too big header while reading response header from upstream

### ISSUE THREAD

**Issue by adilroot** [omab/python-social-auth#527]
Hi,

we use django+nginx and third nginx reverse proxy in the front.

Google auth2 fails because of the too big header sending from reverse proxy to the nginx+django layer.

Could you help please

**Comment by ahmedouvic** [comment]
This is fixed here https://github.com/omab/python-social-auth/commit/f138221b12df275a4ddcece83f212998c30428dc

**Comment by adilroot** [comment]
If you have nginx error 502,  try to add to nginx config file the following buffer setup:

```nginx
http {
     
        .....
        .....

        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;

        .....
```

**Comment by omab** [comment]
This doesn't seem to be a problem with python-social-auth but just something with your setup, right?
