### ISSUE TITLE
Change PyJWT dependency version in setup.py from PyJWT==0.4.1 to PyJWT>=0.4.1

### ISSUE THREAD

**Issue by troygrosfield** [omab/python-social-auth#531]
In the [setup.py](https://github.com/omab/python-social-auth/blob/master/setup.py#L49), the PyJWT dependency is listed as only allowing version ``0.4.1``:

```
requires = ['requests>=1.1.0', 'oauthlib>=0.3.8', 'six>=1.2.0', 'PyJWT==0.4.1']
```
Which replaces the install of the latest version of PyJWT which is at 0.4.3.  Can this instead be changed to:

```
requires = ['requests>=1.1.0', 'oauthlib>=0.3.8', 'six>=1.2.0', 'PyJWT>=0.4.1']
```

**Comment by troygrosfield** [comment]
The requests-oathlib has the same problem.  The setup.py is restricting it to version ``0.3`` to ``0.3.1``:
```
if PY3:
    requires += ['python3-openid>=3.0.1',
                 'requests-oauthlib>=0.3.0,<0.3.2']
```
When the latest version of requests-oauthlib is 0.4.2.  Why is this only allowing those two versions of requests-oauthlib?  It seems to run find with the latest version of requests-oauthlib installed.  Can this be changed to work with the latest version as well?
```
if PY3:
    requires += ['python3-openid>=3.0.1',
                 'requests-oauthlib>=0.3.0']
```

**Comment by omab** [comment]
Fixed, thanks.
