### ISSUE TITLE
weibo access_token ajax auth fail

### ISSUE THREAD

**Issue by littlezz** [omab/python-social-auth#532]
KeyError

.....

/usr/lib/python3.3/site-packages/social/backends/oauth.py in do_auth
        data = self.user_data(access_token, *args, **kwargs) ...
▶ Local vars
/usr/lib/python3.3/site-packages/social/backends/weibo.py in user_data
                                     'uid': kwargs['response']['uid']}) ...
▶ Local vars

**Comment by omab** [comment]
Already fixed.
