### ISSUE TITLE
async interface for models in tornado

### ISSUE THREAD

**Issue by jettify** [omab/python-social-auth#535]
From example I see that Tornado uses sync sqlalchemy connection to communicate with database. Is any way to utilize storage api in async way, with say momoko (async postgresql driver) or motor (async mongodb driver) ??

**Comment by omab** [comment]
Frankly I don't know, Tornado support was an experiment wrote in a night when preparing for a talk for PyCon Uruguay, it's worth checking tho.

**Comment by jettify** [comment]
Thanks. That is why no tornado  entry in documentation. I'll try to write something in async way)
