### ISSUE TITLE
Reduce coupling

### ISSUE THREAD

**Issue by omab** [omab/python-social-auth#54]
There's a lot of coupling in the classes, specially strategy and backend, this needs to be reduced.

**Comment by trojanware** [comment]
+1
@omab Noob here. Is there a plan regarding this that I can build up on / implement? I would like to take a stab at this.

**Comment by kahnjw** [comment]
Not sure about the whole installable, but it seems like the code I linked has been cleaned up. I did not look any further than that.

In retrospect I should have pressed the "y" key before copying the source lines link to get the commit hash in the URL. It would have been much easier to see the cleanup.

**Comment by omab** [comment]
Done https://github.com/python-social-auth
