### ISSUE TITLE
Development/debug option to stub backend while developing

### ISSUE THREAD

**Issue by pvdvreede** [omab/python-social-auth#546]
Hi there,

Just wondering if there is a way to setup a backend, eg google-oauth2 but in development just stub the workflow so that it presents a page where you can put in the username you want to fake, rather than actually going to google. Or perhaps it can be done in the pipeline?

The main thing is I would like to have my template present the correct backend with the same url eg `{% url 'social:begin' backend='google-oauth2' %}` as it would appear in production, but not actually talk to google when I am developing and testing app. This way there is no dependency on the backend to be up and available while developing.

Thanks.

**Comment by omab** [comment]
Take a look to the tests suite, it uses [HTTPretty](https://github.com/gabrielfalcao/HTTPretty) to mock the auth flow, you can define a similar setup in your site to mimic the authentication process.
