### ISSUE TITLE
Make it easier to disable social_details pipeline step

### ISSUE THREAD

**Issue by johtso** [omab/python-social-auth#555]
Sometimes you don't want to have any user fields automatically populated, and want to handle all of that explicitly, and the obvious way to achieve that is to disable the pipeline step that fills `details` with info from the social account.

The trouble is that currently the second default pipeline step expects a details argument that the previous pipeline step is supposed to supply.

How about feeding in a default empty details argument to the first pipeline step so that every pipeline step can expect it to be there?

**Comment by johtso** [comment]
How does the pull request look? I think it's definitely an improvement to add this consistency to the signature of the pipeline functions.

**Comment by omab** [comment]
Looks great, merged.

Thanks!
