### ISSUE TITLE
Login pipeline trying to create new user when user exists

### ISSUE THREAD

**Issue by MikeHibbert** [omab/python-social-auth#562]
Hi All

I'm having a problem that when I login occationally the pipeline will attempt to create a new user even though I've already got a previously created and authenticated user stored.

Is there some steps I'm missing when doing this?

Here is my pipeline:

SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    'social.pipeline.user.create_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details',
    'custom_user.twitter_pipeline.get_auths',
)

the last stage is only to get the oauth_secret etc for posting to twitter etc.

Thanks in advance!

**Comment by tclancy** [comment]
Did you upgrade from the `django-social-auth` app? I'm doing that for an application that's new to me and seeing the same issue, but now I notice the migration for this app [contains an additional table](https://github.com/omab/python-social-auth/blob/master/social/apps/django_app/default/south_migrations/0001_initial.py#L45) `social_auth_code` that may do the connections.

**Comment by omab** [comment]
I need more details to debug this one, what social site are you using? Could you define steps to reproduce?

**Comment by tclancy** [comment]
This was the item you helped me with. Just needed to define:

```
SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    'social.pipeline.social_auth.associate_by_email',
    'social.pipeline.user.create_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details'
)
```

for Google+ anyway.
