### ISSUE TITLE
next parameter containing get parameters

### ISSUE THREAD

**Issue by dblado** [omab/python-social-auth#565]
Using LinkedIn OAuth2 I'm trying to have users redirected to ?next=/my/redirect/path?code=abcd

Is this possible? I don't see anything about a redirect pipeline to get fields stored in sessions and add them to the redirect. I've tried urlencode on my next but that doesn't work.

**Comment by omab** [comment]
You need to escape your next parameter, it should look like ``?next=%2Fmy%2Fredirect%2Fpath%3Fcode%3Dabcd``.
