### ISSUE TITLE
logout without disconnect

### ISSUE THREAD

**Issue by pcompassion** [omab/python-social-auth#568]
Many SO questions assume `disconnect` is `logout`

There's no mention of logout in the doc, and I think it's common usage scenario to log out a user (for the social login) without disconnecting a user.

It would be good to show how to do the logout in the usage doc and clarify that disconnect is not logout.

**Comment by jeromelefeuvre** [comment]
Hi @pcompassion,

Disconnect is more "forget me". It remove a entry in the client app db which link your user just created with the server.
Logout could be done easily by removing sessions.

**Comment by omab** [comment]
Docs added, check here http://psa.matiasaguirre.net/docs/logging_out.html
