### ISSUE TITLE
New version ?

### ISSUE THREAD

**Issue by jeromelefeuvre** [omab/python-social-auth#571]
Do you think it will be possible to create a new version available soon ?

Thanks @omab

**Comment by rlucioni** [comment]
Seconding this. The PyJWT upgrade introduced in #557 would fix dependency conflicts with other projects which have upgraded.

**Comment by omab** [comment]
Version 0.2.3 released.

**Comment by rlucioni** [comment]
Thank you @omab!

**Comment by omab** [comment]
No problem!
