### ISSUE TITLE
sqlalchemy_orm: ImportError: No module named transaction

### ISSUE THREAD

**Issue by dmaze** [omab/python-social-auth#572]
With a very fresh python-social-auth==0.2.3:

```
>>> import social.storage.sqlalchemy_orm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dmaze/Python/vpy/lib/python2.7/site-packages/social/storage/sqlalchemy_orm.py", line 6, in <module>
    import transaction
ImportError: No module named transaction
```

Simply deleting the "import transaction" line from sqlalchemy_orm.py seems to make things work fine; it doesn't seem to correspond to a PyPI package that I know of.

**Comment by ddorian** [comment]
But it's still used further down on the file.

**Comment by omab** [comment]
I've added a condition import also updated the docs to mention the [transaction](https://pypi.python.org/pypi/transaction) package.
