### ISSUE TITLE
Issues while using Custom User model

### ISSUE THREAD

**Issue by neerajd-impinge** [omab/python-social-auth#575]
I am using Custom user model for usig email authentication.My model looks like : 

```
class User(AbstractBaseUser, PermissionsMixin):
    pk_user = UUIDField(auto=True, primary_key=True, serialize=True, hyphenate=True)
    email = models.EmailField(_('email address'), max_length=254, unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    is_staff = models.BooleanField(_('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.'))
    is_active = models.BooleanField(_('active'), default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

```
Now If I am using facebook then I am getting ` 'username' is an invalid keyword argument for this function ` error and for twitter ` email must be set ` error .

These error comes because I have removed usern ame field and email field is required . 

I have defined extra settings to overcome above issues but nothing works : 
```
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_USER_MODEL = 'accounts.User'
SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True
```

**Comment by omab** [comment]
Twitter doesn't disclose email address, so you won't be getting one when using that backend. About ``username``, that's because the user creation is calling your user manager ``create_user()`` method, by default it will pass the ``username`` parameter, but you can avoid that by defining ``SOCIAL_AUTH_USER_FIELDS = ['email']`` (set any parameter name that your ``create_user()`` method expects).

**Comment by neerajd-impinge** [comment]
SOCIAL_AUTH_USER_FIELDS  helps to resolve my error , and when I click on login with fb my app asks for the email but still my create user manager gets blank email.
My custom manager : 
```

class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        now = timezone.now()
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, False,
                                 **extra_fields)
    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True,
                                 **extra_fields)

```

If facebook is asking for email permission then python-social auth must getting the email in response but why my create user getting blank email ? any idea ?

**Comment by ZuSe** [comment]
Same error for me,

is there any solution for the issue?
The email you get within create_user is just blank. All we know is the username that is provided within kwargs (extra_fields above)
