### ISSUE TITLE
Using twitter backend with mongoengine

### ISSUE THREAD

**Issue by dchaplinsky** [omab/python-social-auth#576]
I've got a problem with twitter.

For some reason it's response doesn't contain email address ({"email": ""}), so this is making mongoengine validation for EmailField sick.

Quick solution to this would be changing EmailField in demo app to StringField.

**Comment by omab** [comment]
Hi Dima. I've updated the mongoengine example using the other example as base, in this new version the missing email is taken into account by a pipeline function and it's requested as part of the process.
