### ISSUE TITLE
Email validation needs an email parameter (docs)

### ISSUE THREAD

**Issue by dmaze** [omab/python-social-auth#577]
The documentation [recommends](http://psa.matiasaguirre.net/docs/pipeline.html#email-validation) creating a completion URL for email validation with

```python
from flask import url_for
url = url_for('social.complete', backend=strategy.backend_name,
              _external=True) + '?verification_code=' + code
```

but you get a vague exception if the link isn't clicked within the same session.  Adding an email query parameter fixes this.  My working code looks like

```python
from flask import url_for
url = url_for('social.complete', backend=strategy.backend_name,
              verification_code=code.code, email=code.email,
              _external=True)
```

**Comment by omab** [comment]
What's the vague exception?

**Comment by maxsocl** [comment]
Exception Type:	AuthMissingParameter
Exception Value:	Missing needed parameter email

This exception is raised when we validate email within different session.
Step to reproduce:
1. Send email to validate.
2. logout
3. Click to link in email.

**Comment by omab** [comment]
If that's the error, it won't only fail the validation because email is "missing", it will also break the whole authentication process since the pipeline information is empty, the whole authentication process will fail.

**Comment by maxsocl** [comment]
@omab The whole authentication process is not fail - it will start as new login/register process...
And there is a problem because if user click to associate Email and confirm email from another PC (for example from Phone) it will fall in new login process but not into Email association process...

**Comment by craig-hacklaunch** [comment]
@omab as @maxsocl mention above I don't think the current implementation is how most users expect things to work. There should not be a dependency on the session for the mail validation partial. There is no guarantee the user will continue the process using the same device or even browser. Any state information should be retrievable from the validation link and not depend on the session.

**Comment by maxsocl** [comment]
UPD: I got around this issue by creating custom Strategy, Storage and Code. In Code a have user_id field. And when user click confirmation link on different PC I can see exactly what user want to confirm an email.

**Comment by omab** [comment]
@maxsocl, @craig-hacklaunch, I see the problem now, and even if I think that this could be solved with a re-write of the email validation pipeline, this affects all the pipeline functions that use the partial mechanism, so, I'm already working on a restructure of the pipeline serialization functionality that will improve this behavior. Basically the pipeline data will be dumped to a DB table and a hash code will be used to identify the processes which can be stopped and continue later, removing the dependency of the session.

**Comment by craig-hacklaunch** [comment]
@omab thanks for your contribution to the community :). Your fix sounds like a good approach, I guess this will fix the problem for all partial pipelines that were using the session to dump their data to before.

**Comment by maxsocl** [comment]
@omab it is a good news for everyone :smile: thank you for contribution!

**Comment by a1Gupta** [comment]
@omab Is it fixed now ?

**Comment by annshress** [comment]
Any updates for MissingParameterEmail?

**Comment by annshress** [comment]
@dmaze your fix still gives me: 
> "error_messages": ["Password is None"]
