### ISSUE TITLE
sdist tarball is missing some files and dirs

### ISSUE THREAD

**Issue by abompard** [omab/python-social-auth#578]
The tarball uploaded to PyPI via the setup.py sdist command is missing some of the content in the repo because there's no `MANIFEST.in` file. This content includes the `docs` and `examples` subfolders, the `LICENSE` and `Changelog` files and the `requirement-*.txt` files.
Here's the `MANIFEST.in` file that you can add to include them:
```
include *.txt Changelog LICENSE Makefile
include docs/conf.py
recursive-include docs *.rst
graft examples
```
This will make packager's life much easier as the tarball will contain all we need.

**Comment by omab** [comment]
File added. Thanks!
