### ISSUE TITLE
LinkedIn OAuth2 bad request.

### ISSUE THREAD

**Issue by guyf** [omab/python-social-auth#58]
I have a working django LinkedIn OAuth1 setup. I have tried to switch to OAuth2 by updating all my settings from SOCIAL_AUTH_LINKEDIN_\* to SOCIAL_AUTH_LINKEDIN_OAUTH2_\* and switching the backend to social.backends.linkedin.LinkedinOAuth2

I get an AuthCancelled Exception. Triggered I think by by HTTPError('400 Client Error: Bad Request',)

The inbound URL looks like:

http://bbm-dev.local:8000/complete/linkedin-oauth2/?redirect_state=c230xy4n04oSAG9x3xwcbEUgudTewZA1&code=AQShEKzGzz2n8lcfl7n9IxLwzWKs2R2g3kwFl5skR04z6Bk_LxYFQF3nrKSalI7Jk3mRGbFZAs60Csd2SW9yNwKZmPY39Iz7fx-E7T_2d2JIRvI7A-c&state=c230xy4n04oSAG9x3xwcbEUgudTewZA1

Have I missed anything in my setup changes? Any other ideas? Thanks.

**Comment by d3prof3t** [comment]
@omab What exactly do we need to specify in the redirect uri in the django app as well as the linkedin app?
My current django app config is:
SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = 'xxxxxxxxxx'
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = 'xxxxxxx'

# Add email to requested authorizations.
SOCIAL_AUTH_LINKEDIN_OAUTH2_SCOPE = [ 
    'r_basicprofile', 'r_emailaddress', 'rw_company_admin', 'w_share']

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'

Am I missing something in my config file, and exactly what should be the redirect uri in cas of OAuth2?
