### ISSUE TITLE
Django 1.9 Warnings

### ISSUE THREAD

**Issue by JJZolper** [omab/python-social-auth#581]
I just thought I should leave some warnings I got from Django because of moving to 1.8:

/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/site-packages/social/apps/django_app/default/models.py:29: RemovedInDjango19Warning: Model class social.apps.django_app.default.models.UserSocialAuth doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class UserSocialAuth(models.Model, DjangoUserMixin):

/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/site-packages/social/apps/django_app/default/models.py:67: RemovedInDjango19Warning: Model class social.apps.django_app.default.models.Nonce doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Nonce(models.Model, DjangoNonceMixin):

/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/site-packages/social/apps/django_app/default/models.py:78: RemovedInDjango19Warning: Model class social.apps.django_app.default.models.Association doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Association(models.Model, DjangoAssociationMixin):

/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/site-packages/social/apps/django_app/default/models.py:91: RemovedInDjango19Warning: Model class social.apps.django_app.default.models.Code doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Code(models.Model, DjangoCodeMixin):

/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  return f(*args, **kwds)

/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead.
  return f(*args, **kwds)

/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  return f(*args, **kwds)

/Users/JJZ/Dropbox/AU/AUrepo/athletesunited/athletesunited/comments/models.py:19: RemovedInDjango19Warning: Model class athletesunited.comments.models.Comment doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Comment(models.Model):

/Users/JJZ/Dropbox/AU/AUrepo/athletesunited/athletesunited/comments/models.py:134: RemovedInDjango19Warning: Model class athletesunited.comments.models.CommentFlag doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class CommentFlag(models.Model):

/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
  return f(*args, **kwds)

/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/site-packages/social/apps/django_app/default/models.py:29: RemovedInDjango19Warning: Model class social.apps.django_app.default.models.UserSocialAuth doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class UserSocialAuth(models.Model, DjangoUserMixin):

/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/site-packages/social/apps/django_app/default/models.py:67: RemovedInDjango19Warning: Model class social.apps.django_app.default.models.Nonce doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Nonce(models.Model, DjangoNonceMixin):

/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/site-packages/social/apps/django_app/default/models.py:78: RemovedInDjango19Warning: Model class social.apps.django_app.default.models.Association doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Association(models.Model, DjangoAssociationMixin):

/Users/JJZ/.virtualenvs/athletesunited/lib/python3.4/site-packages/social/apps/django_app/default/models.py:91: RemovedInDjango19Warning: Model class social.apps.django_app.default.models.Code doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Code(models.Model, DjangoCodeMixin):

I assume contributers are already aware because it's just a natural shift to Django 1.8 that caused these Django 1.9 warnings.

Thanks for your consideration.

JJ

**Comment by mattrobenolt** [comment]
See #551 which has been fixed.

**Comment by omab** [comment]
These are already solved by #550

**Comment by JJZolper** [comment]
Oh that's weird, I will have to try to update my PSA again because I was pretty sure I made sure to update the package for this exact reason and I saw those warnings after I had updated. Maybe it's just a rookie mistake on my end in terms of missing something in terms of updating the package and it not fully updating but I was pretty sure I did it right. I will dig into this again and try again and see if all is good and report back any findings.

**Comment by omab** [comment]
The change is not released into pypi yet.

**Comment by JJZolper** [comment]
Oh that must be it because I see that the versioning was updated to 0.2.4 but I only have 0.2.3 so yeah when the next release comes out like you already know and have said I think I'll be in good shape.

**Comment by JJZolper** [comment]
btw is there a timetable for when it would be released to the pypi? sorry if i don't know where i should be looking because i don't haha.

**Comment by omab** [comment]
I do releases mostly by demand or when I feel the amount of changes are worthy a release. I've released ``v0.2.4`` a few minutes ago.
