### ISSUE TITLE
Setting user.is_active to false at end of pipeline logs out user

### ISSUE THREAD

**Issue by urlsangel** [omab/python-social-auth#586]
Hi 

I'm trying to implement custom email validation at the end of the pipeline with Django 1.7.4, using the same logic as for regular non-social user registrations:

* Set user.is_active to false
* Generate and send an email with an activation link
* Redirect to success page where the user is logged in but not active, so the context can display the user email that has been captured.

At the end of the pipeline I have a validate partial function that does this:

    @partial
    def validate(strategy, details, user=None, is_new=False, *args, **kwargs):
	if user and is_new:

		user.is_active = False
		user.save()

		username = user.username
		email = user.email
		salt = hashlib.sha1(str(random.random()).encode('utf-8')).hexdigest()[:5]            
		activation_key = hashlib.sha1(str(salt + email).encode('utf-8')).hexdigest()            
		key_expires = datetime.datetime.today() + datetime.timedelta(2)

		new_profile = UserProfile(user=user, activation_key=activation_key, key_expires=key_expires)
		new_profile.save()

		email_subject = 'Account confirmation'
		email_body = "Hey %s, thanks for signing up. To activate your account, click this link within 48 hours %s%s" % (username, site(strategy.request)['site_root'], reverse('users:confirm', args=[activation_key]))
		send_mail(email_subject, email_body, settings.DEFAULT_FROM_EMAIL, [email], fail_silently=False)
		return
	
	return

And in settings I have this:

    SOCIAL_AUTH_INACTIVE_USER_LOGIN = True
    INACTIVE_USER_URL = '/signup/success/'

The `INACTIVE_USER_URL` is being picked up, but the user is not logged in.

Any idea why this wouldn't work as expected?

Thanks!

Russell.

**Comment by omab** [comment]
What version of psa are you using?

**Comment by urlsangel** [comment]
Hi Matías

Thanks for responding :-)

I'm using psa 0.2.3.

Cheers,

Russell.

**Comment by urlsangel** [comment]
Hi Matías

I'm using pip to install from pypi - I've just had a look at the code from there, and it looks like the inactive login part isn't in there, so maybe that's the problem?

Any chance pypi could be updated to include the latest from github?

Thanks

Russell.

**Comment by omab** [comment]
I've released ``v0.2.4`` a few minutes ago, that should fix your issue.

**Comment by urlsangel** [comment]
Hi Matías

Thanks for doing that, much appreciated.

I'm running python 3.4, but it looks like the psa requirements aren't picking that up, as they grab `python-openid` instead of `python3-openid` - any idea what might be the cause?

`Downloading/unpacking python-openid>=2.2 (from python-social-auth==0.2.4->-r requirements.txt (line 21))`

Thanks again,

Russell.

**Comment by urlsangel** [comment]
Hi Matías

Any idea if the above python 3 bug is fixable?

Thanks,

Russell.

**Comment by omab** [comment]
That's already fixed (was released a couple days ago).

**Comment by urlsangel** [comment]
Brilliant, thank you :-)
