### ISSUE TITLE
Token error: Missing unauthorized token

### ISSUE THREAD

**Issue by hinnocence** [omab/python-social-auth#589]
I'm new to python social auth and am using django 1.6.6 and python social auth to provide login function.

I use CustomUser to save the twitter user information and set

>SOCIAL_AUTH_USER_MODEL = 'webservice.CustomUser'

It works fine when I login my website via twitter account,and I check the database,it saves the user information to both

>default.user social auth Table

and

>webservice.CustomUser Table

but when I deploy it with apache, I cannot login with twitter account and it stays at the login page and then returns a error

>AuthFailed at /login/twitter/

>Authentication failed: ('Connection aborted.', error(110, 'Connection timed out'))

>Request Method: GET

>Request URL: www.demodemo.com/login/twitter/?next=/ Django Version: 1.6.6

>Exception Type: AuthFailed

>Exception Value:

>Authentication failed: ('Connection aborted.', error(110, 'Connection timed out'))

>Exception Location: /usr/local/lib/python2.7/site-packages/social/backends/base.py in request, line 223

>Python Executable: /usr/bin/python

>Python Version: 2.7.8

I did configure the .conf file well and when I test it locally I found that though I can login with twitter account successfully when I check the "Network" in the browser I still find a request hasn't been handled properly

>http://test3.com:8000/complete/twitter/?redirect_state=eGnxBZnn1l4TTk5jUlqBy0BPZCZmL9sJ&oauth_token=una3ULjfWwDByegbn4qoKsxpHRCyGDdM&oauth_verifier=6SXp7uLxj7QhD29GP7LkuQt71xKmXZ4n

>status 302

When I click the link the following error is returned

actually I try to set the

>MIDDLEWARE_CLASSES = (
'myapp.middleware.SocialAuthExceptionMiddleware',
)
>DEBUG = False

but I can ignore the error locally but when I deploy it with apache, it still doesn't work.

Anyone know why those happened and how to solve this? Did I forget some configuration or do i need to add extra code to handle that?

>AuthTokenError at /complete/twitter/

>Token error: Missing unauthorized token

>Request Method: GET

>Request URL: http://test3.com:8000/complete/twitter/?redirect_state=XoB4wH5a6EyJYTxywGYyYgMufR4W2pX8&oauth_token=dixi6oAsfMCBUGqP4KApQHe22h5vVBLz&oauth_verifier=0KSFg7WRocPpGNR3iwODA1pAwQZ88vbn

>Django Version: 1.6.6

>Exception Type: AuthTokenError

>Exception Value:

>Token error: Missing unauthorized token

>Exception Location: /usr/local/lib/python2.7/dist-packages/social/backends/oauth.py in get_unauthorized_token, line 202

>Python Executable: /usr/bin/python

>Python Version: 2.7.6
>Environment:

>Request Method: GET
>Request URL:  test3.com:8000/complete/twitter/?redirect_state=XoB4wH5a6EyJYTxywGYyYgMufR4W2pX8&oauth_token=dixi6oAsfMCBUGqP4KApQHe22h5vVBLz&oauth_verifier=0KSFg7WRocPpGNR3iwODA1pAwQZ88vbn

>Django Version: 1.6.6
>Python Version: 2.7.6
>Installed Applications:
>('twython',
> 'djcelery',
> 'rest_framework',
> 'corsheaders',
> 'oauth2_provider',
>'webservice',
> 'suit',
>'south',
> 'social.apps.django_app.default',
> 'django.contrib.admin',
> 'django.contrib.auth',
> 'django.contrib.contenttypes',
>'django.contrib.sessions',
> 'django.contrib.messages',
 >'django.contrib.staticfiles')
>Installed Middleware:
>('django.contrib.sessions.middleware.SessionMiddleware',
 >'corsheaders.middleware.CorsMiddleware',
> 'django.middleware.common.CommonMiddleware',
> 'django.middleware.csrf.CsrfViewMiddleware',
> 'django.contrib.auth.middleware.AuthenticationMiddleware',
 >'django.contrib.messages.middleware.MessageMiddleware',
> 'django.middleware.clickjacking.XFrameOptionsMiddleware',
> 'social.apps.django_app.middleware.SocialAuthExceptionMiddleware')

>Traceback:
>File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
>  112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py" in _wrapped_view_func
>  52.         response = view_func(request, *args, **kwargs)
>File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py" in wrapped_view
 > 57.         return view_func(*args, **kwargs)
>File "/usr/local/lib/python2.7/dist-packages/social/apps/django_app/utils.py" in wrapper
>  52.             return func(request, backend, *args, **kwargs)
>File "/usr/local/lib/python2.7/dist-packages/social/apps/django_app/views.py" in complete
>  29.                        redirect_name=REDIRECT_FIELD_NAME, *args, **kwargs)
>File "/usr/local/lib/python2.7/dist-packages/social/actions.py" in do_complete
>  44.         user = backend.complete(user=user, *args, **kwargs)
>File "/usr/local/lib/python2.7/dist-packages/social/backends/base.py" in complete
>  40.         return self.auth_complete(*args, **kwargs)
>File "/usr/local/lib/python2.7/dist-packages/social/backends/oauth.py" in auth_complete
>  178.         token = self.get_unauthorized_token()
>File "/usr/local/lib/python2.7/dist-packages/social/backends/oauth.py" in get_unauthorized_token
>  202.             raise AuthTokenError(self, 'Missing unauthorized token')

>Exception Type: AuthTokenError at /complete/twitter/
>Exception Value: Token error: Missing unauthorized token

**Comment by omab** [comment]
The ``302`` response is not an error, that's OK, clicking that link again raises an error because it's trying to get a value from the session that's not there anymore (because the URL was already visited during the complete process).

No, regarding the problem in your server, do you have the full traceback? Also check if you have access to Twitter API from your server (try wget or similar tools to hit it). It looks like your server is experiencing issues accessing the twitter API (maybe because it's over ``https``, which is not the first time something similar is reported).

How's the server datetime defined? Do you have ``ntpd`` or similar installed (highly recommended)?

**Comment by hinnocence** [comment]
thank you for replying

when I deploy it with apache the error returned is 

>AuthFailed at /login/twitter/
>Authentication failed: ('Connection aborted.', error(110, 'Connection timed out'))

the full traceback is as follows

Environment:


>Request Method: GET
>Request URL: http://demodemo.com/login/twitter/?next=/

>Django Version: 1.6.6
>Python Version: 2.7.8
>Installed Applications:
>('south',
 'twython',
 'djcelery',
 'rest_framework',
 'corsheaders',
 'corsheaders',
 'oauth2_provider',
 'webservice',
 'suit',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'social.apps.django_app.default')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'webservice.middleware.ErrorToJSONMiddleware',
 'social.apps.django_app.middleware.SocialAuthExceptionMiddleware')


>Traceback:
>File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  52.         response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/social/apps/django_app/utils.py" in wrapper
  52.             return func(request, backend, *args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/social/apps/django_app/views.py" in auth
  19.     return do_auth(request.backend, redirect_name=REDIRECT_FIELD_NAME)
File "/usr/local/lib/python2.7/site-packages/social/actions.py" in do_auth
  25.     return backend.start()
File "/usr/local/lib/python2.7/site-packages/social/backends/base.py" in start
  35.             return self.strategy.redirect(self.auth_url())
File "/usr/local/lib/python2.7/site-packages/social/backends/oauth.py" in auth_url
  164.         token = self.set_unauthorized_token()
File "/usr/local/lib/python2.7/site-packages/social/backends/oauth.py" in set_unauthorized_token
  224.         token = self.unauthorized_token()
File "/usr/local/lib/python2.7/site-packages/social/backends/oauth.py" in unauthorized_token
  244.             method=self.REQUEST_TOKEN_METHOD
File "/usr/local/lib/python2.7/site-packages/social/backends/base.py" in request
  223.             raise AuthFailed(self, str(err))

>Exception Type: AuthFailed at /login/twitter/
>Exception Value: Authentication failed: ('Connection aborted.', error(110, 'Connection timed out'))

actually the server can access the twitter API , because when I start the server by the command "manage.py runserver" ,and login with the twitter account it works fine. 

What do you mean by "maybe it's over https"?  you mean the authentication through twitter is over https? do I also need to set the return url to https address?

**Comment by omab** [comment]
What I meant is that your server (the machine that you are using where the app is deployed, the one with Apache), might have some limitations accessing third-party sites or protocols or ports, so you need to check if that serve is killing your connection to twitter, try this in that machine ``wget https://api.twitter.com/oauth/request_token``, it should drop a 400 bad request (because it lacks some parameters).

**Comment by hinnocence** [comment]
yes. the response is 400. I'll enable the ssl for apache. thank you !

**Comment by hinnocence** [comment]
I check the configuration and i found my server can support https, and then I found the parameter SOCIAL_AUTH_REDIRECT_IS_HTTPS, and I set it  "True" , is it the parameter to force the twitter api return to a url via 'https', but it still not work..... I am blocked here....

**Comment by omab** [comment]
I think you are not following me, I didn't meant that your server should be running over SSL, I meant that it looks like your server doesn't have a correct access to SSL APIs. Do you have ``nptd`` running on that machine?

**Comment by hinnocence** [comment]
it works fine ntpd 0:off 1:off 2:on 3:on 5:on 6:off

**Comment by omab** [comment]
Could you try installing ``python-social-auth`` from github and try again? You can install it with pip like this:

```shell
$ pip install -e "git+https://github.com/omab/python-social-auth.git#egg=python-social-auth"
```
