### ISSUE TITLE
pypi package version 0.2.5 is missing requirements.txt from tests

### ISSUE THREAD

**Issue by squamous** [omab/python-social-auth#590]
Hello,

the latest packages uploaded to pypi.org as of 2015-04-13 is missing requirements.txt from the 'social/tests' directory which for some versions of pip means a failed package build.

Sorry if this isn't the most appropriate place to bring this up but the support link on the package page went nowhere useful.

Thanks for such a useful lib :)

**Comment by taxido** [comment]
Older releases are also affected by this issue

**Comment by omab** [comment]
``v0.2.6`` (just released) includes the requirements files.
