### ISSUE TITLE
CLEAN_USERNAME_REGEX  error

### ISSUE THREAD

**Issue by littlezz** [omab/python-social-auth#594]
In https://github.com/omab/python-social-auth/blob/master/social/storage/base.py,  the `CLEAN_USERNAME_REGEX` maybe error.  

```
CLEAN_USERNAME_REGEX = re.compile(r'[^\w.@+-_]+', re.UNICODE)
```

The `-` in `[]` means range of characters, if we want to match literal `-`, we can escape it or put it in the end.

The correct expression is

```
CLEAN_USERNAME_REGEX = re.compile(r'[^\w.@+_-]+', re.UNICODE)
```

or

`CLEAN_USERNAME_REGEX = re.compile(r'[^\w.@+\-_]+', re.UNICODE)`

ref: https://docs.python.org/3.4/library/re.html#regular-expression-syntax

**Comment by omab** [comment]
Fixed, thanks!
