### ISSUE TITLE
uncompleted extra_data for access_token, code, and expires in Google+

### ISSUE THREAD

**Issue by zetahernandez** [omab/python-social-auth#596]
Hi, I'm trying to authenticate in my web server from a SPA application using google+. I only have one problem when the user is authenticated. I don't get the extra data in social_auth_usersocialauth table, I mean I'm getting in the extra_data field
```javascript
{"code": null, "access_token": "", "expires": null, "user_id": "10181231375248323"}.
```
the way i'm doing it is the next. 
#### In my SPA i'm doing 

```javascript
 gapi.auth.signIn({
      "clientid" : "872066331548-m61m12384ii2gs5b82tbb2qlipesum6ee.apps.googleusercontent.com",
      "cookiepolicy" : "single_host_origin",
      "callback" : this.statusChangeCallback,
      "scope": "https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.profile.emails.read"
    }); 
```
#### In my web server
the endpoint receive the access_token in the request that was giving by spa and do authentication

```python
api_view(['GET'])
@permission_classes((permissions.AllowAny, ))
@psa('social:complete')
def register_by_access_token(request, backend):

    token = request.GET.get('access_token')
    user = request.backend.do_auth(access_token=token, backend=backend)
    if user:
        login(request, user)
        serialize = UserSerializer(user, context={'request': request})

        return Response(serialize.data)
    else:
        return Response('ERROR')
```
#### and the settings are 

```python

AUTHENTICATION_BACKENDS = (

    'social.backends.facebook.FacebookAppOAuth2',
    'social.backends.facebook.FacebookOAuth2',
    'social.backends.google.GooglePlusAuth'
    'django.contrib.auth.backends.ModelBackend',
)
SOCIAL_AUTH_GOOGLE_PLUS_KEY = '872066331548-###################.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_PLUS_SECRET = '######################'

SOCIAL_AUTH_GOOGLE_PLUS_AUTH_EXTRA_ARGUMENTS = {
      'access_type': 'offline',
      'approval_prompt': 'auto'
}
SOCIAL_AUTH_GOOGLE_PLUS_SCOPE = [
    'https://www.googleapis.com/auth/plus.login',
    'https://www.googleapis.com/auth/plus.emails.read'
]
SOCIAL_AUTH_GOOGLE_PLUS_USE_UNIQUE_USER_ID = True

SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    # 'social.pipeline.mail.mail_validation',
    'social.pipeline.social_auth.associate_by_email',
    'social.pipeline.user.create_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details',

    'social.pipeline.debug.debug'
)
```

What i'm doing wrong??  i'm using the similar code to authenticate with facebook and the extra_data is completed. Some help is welcome. Thanks

**Comment by omab** [comment]
What version are you using? There was a fix related to access token storage when using AJAX authentication a few days ago.

**Comment by zetahernandez** [comment]
I'm using 0.2.6 the last

**Comment by zetahernandez** [comment]
The flow i need is based on [server-side-flow](https://developers.google.com/+/web/signin/server-side-flow) as i saw there the client send an "authorization code" to the server and use it to obtain credential. The code is a one-time code that the server can exchange with Google's servers for an access token. Maybe this approach isn't supported yet in psa.
![server-side-flow](https://developers.google.com/+/images/server_side_code_flow.png)

**Comment by omab** [comment]
This approach resembles the default server-side OAuth2 implementation, the user clicks the login button, get's redirected to the provider where it accepts, get's redirected back to the site with a ``code`` parameter, that's then exchanged for an ``access_token``.

In theory (this is not tested), you can call ``request.backend.auth_complete()`` in your view implementation.
