### ISSUE TITLE
Release apps.py for apps

### ISSUE THREAD

**Issue by Darwesh27** [omab/python-social-auth#601]
With the new django-version python-social-auth should release its latest version with apps.py and also please change the name 'social' to some things else. Social is too common name and people might have an app installed with that name in their project.

**Comment by omab** [comment]
``AppConfig`` is defined here https://github.com/omab/python-social-auth/blob/master/social/apps/django_app/default/config.py.

There's no need for a rename of an app that's over 2 years old, in active development and used by many developers that never complained about that.
