### ISSUE TITLE
Adding roles to new user

### ISSUE THREAD

**Issue by vyscond** [omab/python-social-auth#602]
By default the library creates a **django.contrib.auth.models.User** instance for every new user logged over the social flows, so what i need to do is to get this **User** and set some specific roles.

I was reading about the _pipelines_ and i think it's the way to achieve it, but i'am lost on how exactly because the **user** object passed through the args is not from the **auth.models** ! So how can i reach the **User** from the **auth.models** to change/add the roles?

**Comment by omab** [comment]
The ``user`` instance passed in the pipeline is from ``django.contrib.auth.models.User`` unless the user model was overridden by ``AUTH_USER_MODEL`` setting (https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#substituting-a-custom-user-model).

About ``roles``, it depends on how your application manages them, if you are referring to ``Groups`` (https://docs.djangoproject.com/en/1.8/topics/auth/default/#topic-authorization), then follow the Django docs about it.
