### ISSUE TITLE
Login with Amazon TLS requests

### ISSUE THREAD

**Issue by osroca** [omab/python-social-auth#603]
Today I have received an email from the support team of "Login with Amazon" with the warning about that on May 25 any request to the service have to use TLS instead of SSL.
Is python-social-auth ready for this?
I'm using django-social-auth v0.7.28 and I'd like to know if I have to do something to be compatible with this Amazon update.

Thanks!

**Comment by omab** [comment]
I've added TLSv1 support to Amazon backend. Now, regarding ``django-social-auth``, that lib is deprecated and support for this won't be added to it.
