### ISSUE TITLE
Two diferent user profiles

### ISSUE THREAD

**Issue by fproldan** [omab/python-social-auth#604]
Hi!, i have two diferent user types in my app and i want to create the user profile in a custom pipeline or overriding user_details for example, but i need to know what type of user is login, how can i archive this? 
Thanks!

**Comment by omab** [comment]
How do you track that? Different buttons?

**Comment by fproldan** [comment]
Thanks! i'ts works. 
Perdón por mi inglés, pero creo que sos de Uruguay, así que te agradezco en español!. Muy buena app!
