### ISSUE TITLE
Reverse with trailing slash in django urls is broken since 0.2.4 to 0.2.7

### ISSUE THREAD

**Issue by Winnerer** [omab/python-social-auth#609]
I got wrong resolved urls while using python social auth - they are without trailing slash in the end. I got realized, that it has already been fixed in master branch with ```SOCIAL_AUTH_TRAILING_SLASH``` parameter, but last stable version on pypi is broken. When those fixes would be on pypi?

**Comment by omab** [comment]
``v0.2.9`` released to pypi.
