### ISSUE TITLE
Proper changelog

### ISSUE THREAD

**Issue by thusoy** [omab/python-social-auth#613]
The changelog should give a short summary of what has happened feature-wise and bug-wise between versions, to assist upgrading. The current changelog is way too verbose and makes it way too tedious to figure out whether it's safe to upgrade or not. I was just wondering what major changes had occured between 0.1.24 and the latest version, that necessitated reading through 1071 lines of changelog, or ~300 commit messages, most of which doesn't contain any valuable information.

I get that it's a bit more work to actually write a proper changelog between releases, but it increases the usability of the library very much. 

Thank you for an otherwise excellent library!

**Comment by omab** [comment]
A Changelog is properly maintained now in the new library components at [python-social-auth](https;//github.com/python-social-auth).
