### ISSUE TITLE
VKontakte KEY_ID may be 'id' or 'user_id' but get response['uid']

### ISSUE THREAD

**Issue by Konjkov** [omab/python-social-auth#618]
VKontakte KEY_ID may be 'id' or 'user_id'

but def get_user_id(self, details, response) try to get response['uid']
https://github.com/omab/python-social-auth/blob/master/social/backends/vk.py#L88

KeyError: 'uid' raised.

**Comment by Atorich** [comment]
+1

**Comment by Amareis** [comment]
-1. Now KEY_ID must be 'uid', else you get user with 'None' UID, and this is very bad.
API response does not contain field `user_id`, used by psa by default. I made simple workaround for this issue in my settings.py

```python
# monkeypathing social vk api
from social.backends.vk import VKOAuth2
VKOAuth2.ID_KEY = 'uid'
```

**Comment by Amareis** [comment]
Ok, if set `SOCIAL_AUTH_VK_OAUTH2_API_VERSION` to '5.52' (current API version), then KEY_ID must be 'id'. But anyway, response from default version API (3.0) doesn't contains field `user_id`, it's contain `uid` field.
It's need to be fixed.

**Comment by omab** [comment]
VK ID_KEY was updated to `id`.
