### ISSUE TITLE
django_app/default: Migration 0003_alter_email_max_length wrong for Django 1.7

### ISSUE THREAD

**Issue by shaib** [omab/python-social-auth#622]
Hi,

Django 1.8 changed the default `max_length` for `EmailField` to 254. In response, python-social-auth added migration 0003_alter_email_max_length, which sets its own email field's length to 254. However, the email field itself does not have an explicit max_length specified, so on Django 1.7 (where the default `max_length` is still 75) Django issues this message (when running `migrate` and there are no other migrations to run):
```
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```
Of course, if you follow that advice, you get an automatic migration.

Proper fix, probably, is setting the `Code.email`'s length to 75 explicitly as long as Django 1.7 is supported (254 is also an option, but may be a problem if the value is then copied into other, default-lengthed, email fields).

**Comment by nickcatal** [comment]
FYI, this was solved in 663a174db194b1cc46effcaa4a2dc45d41d0d8e3

**Comment by shaib** [comment]
No, this was **introduced** in 663a174. Before that commit, migrations create a field that doesn't work well with Django 1.8. With it, migrations create a field which works well with Django 1.8, but not Django 1.7.

**Comment by nickcatal** [comment]
Ouch. Misread that. You're right. Hmm.....

**Comment by koterpillar** [comment]
Specify the length on the `EmailField` manually to fix this.

**Comment by hwkns** [comment]
@omab could you maybe release this fix to PyPI?  This is currently breaking my builds, so I've had to downgrade `python-social-auth`.

**Comment by omab** [comment]
@hwkns, ``v0.2.13`` released to pypi.
