### ISSUE TITLE
Cannot add foreign key constraint during initial migration

### ISSUE THREAD

**Issue by jasonwaters** [omab/python-social-auth#624]
I'm adding python-social-auth to an existing django 1.8 app with a vanilla user model.  But when I do the initial migration I get a foreign key constraint error during the initial migration when it tries to add the foreign key to the auth.User table.  here's the details:

The generated SQL:

```
BEGIN;
CREATE TABLE `social_auth_association` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `server_url` varchar(255) NOT NULL, `handle` varchar(255) NOT NULL, `secret` varchar(255) NOT NULL, `issued` integer NOT NULL, `lifetime` integer NOT NULL, `assoc_type` varchar(64) NOT NULL);
CREATE TABLE `social_auth_code` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `email` varchar(75) NOT NULL, `code` varchar(32) NOT NULL, `verified` bool NOT NULL);
CREATE TABLE `social_auth_nonce` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `server_url` varchar(255) NOT NULL, `timestamp` integer NOT NULL, `salt` varchar(65) NOT NULL);
CREATE TABLE `social_auth_usersocialauth` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `provider` varchar(32) NOT NULL, `uid` varchar(255) NOT NULL, `extra_data` longtext NOT NULL, `user_id` integer NOT NULL);
ALTER TABLE `social_auth_usersocialauth` ADD CONSTRAINT `social_auth_usersocialauth_provider_2f763109e2c4a1fb_uniq` UNIQUE (`provider`, `uid`);
ALTER TABLE `social_auth_code` ADD CONSTRAINT `social_auth_code_email_75f27066d057e3b6_uniq` UNIQUE (`email`, `code`);
ALTER TABLE `social_auth_nonce` ADD CONSTRAINT `social_auth_nonce_server_url_36601f978463b4_uniq` UNIQUE (`server_url`, `timestamp`, `salt`);
CREATE INDEX `social_auth_code_c1336794` ON `social_auth_code` (`code`);
ALTER TABLE `social_auth_usersocialauth` ADD CONSTRAINT `social_auth_usersociala_user_id_193b2d80880502b2_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`);
CREATE INDEX `social_auth_usersocialauth_e8701ad4` ON `social_auth_usersocialauth` (`user_id`);

COMMIT;
```

The output from the failed migration:

```
Operations to perform:
  Target specific migration: 0001_initial, from default
Running migrations:
  Rendering model states... DONE
  Applying default.0001_initial...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/waters/Development/smcov/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/waters/Development/smcov/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/waters/Development/smcov/env/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/waters/Development/smcov/env/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/waters/Development/smcov/env/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Users/waters/Development/smcov/env/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/Users/waters/Development/smcov/env/lib/python2.7/site-packages/django/db/migrations/executor.py", line 147, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/waters/Development/smcov/env/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 91, in __exit__
    self.execute(sql)
  File "/Users/waters/Development/smcov/env/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/Users/waters/Development/smcov/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/waters/Development/smcov/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/waters/Development/smcov/env/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/waters/Development/smcov/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/waters/Development/smcov/env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/Users/waters/Development/smcov/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/Users/waters/Development/smcov/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.IntegrityError: (1215, 'Cannot add foreign key constraint')
```

I'm not sure if I'm doing something wrong or if it's a bug.  Any help is appreciated.

**Comment by timrc** [comment]
I have the same issue. My user model is defined as:

    class User(auth_models.AbstractUser):
        class Meta:
            db_table = 'auth_user'

and I have set `AUTH_USER_MODEL` to that model.

sql generated by `sqlall` command is:

    BEGIN;
    CREATE TABLE `auth_user_groups` ( `id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `group_id` integer NOT NULL, UNIQUE (`user_id`, `group_id`));
    ALTER TABLE `auth_user_groups` ADD CONSTRAINT `group_id_refs_id_274b862c` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`);
    CREATE TABLE `auth_user_user_permissions` ( `id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `permission_id` integer NOT NULL, UNIQUE (`user_id`, `permission_id`));
    ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `permission_id_refs_id_35d9ac25` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`);
    CREATE TABLE `auth_user` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `password` varchar(128) NOT NULL, `last_login` datetime(6), `is_superuser` bool NOT NULL, `username` varchar(30) NOT NULL UNIQUE, `first_name` varchar(30) NOT NULL, `last_name` varchar(30) NOT NULL, `email` varchar(254) NOT NULL, `is_staff` bool NOT NULL, `is_active` bool NOT NULL, `date_joined` datetime(6) NOT NULL);
    ALTER TABLE `auth_user_groups` ADD CONSTRAINT `user_id_refs_id_40c41112` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`);
    ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `user_id_refs_id_4dc23c39` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`);
    CREATE INDEX `auth_user_groups_6340c63c` ON `auth_user_groups` (`user_id`);
    CREATE INDEX `auth_user_groups_5f412f9a` ON `auth_user_groups` (`group_id`);
    CREATE INDEX `auth_user_user_permissions_6340c63c` ON `auth_user_user_permissions` (`user_id`);
    CREATE INDEX `auth_user_user_permissions_83d7f98b` ON `auth_user_user_permissions` (`permission_id`);
    COMMIT;
    
and you can see that at that point the table `auth_group` doesn't exists but yet it tries to add constraint to it.

**Comment by garryqian** [comment]
I got similar issue with other app refer to user module in django 1.8. 
But it only happens after I upgrade MySQL from 5.1 to 5.7.9.
I find out that the auth_user table is not created at this time, passed after re-run migrate.
I have not figure out the root cause. Just for your reference.@jasonwaters

**Comment by jduyon** [comment]
I've ran into this issue also, and seem to have fixed it by "starting from scratch" while using django 1.9.1 and mysql 5.6.23. My steps that seemed to work were:
(first setup a test that reproduces the issue)

- Backup mysql database
- Remove migrations folders from all apps (including auth and admin in site-packages/django/contrib/<auth or admin>}/migrations/)
- Remove auto_created=True from class Meta of one of my models (unrelated to this specific issue)
- Drop testing and production database
- Run makemigrations for 'default', 'admin','auth' and then each of my other installed apps
- Run migrate 
- Rerun the tests and hopefully works again.
