### ISSUE TITLE
Use Python_Spcial_Auth without any Framework

### ISSUE THREAD

**Issue by Gocht** [omab/python-social-auth#627]
Is it possible to use python_social_auth package without using any framework?

**Comment by dcmoore-gd** [comment]
@Gocht Did you get anywhere with this?

**Comment by omab** [comment]
Currently there's no implemented way, but with the recent split into smaller modules, it should be easier to accomplish this since the [core component](https://github.com/python-social-auth/social-core) doesn't depend on any framework.
