### ISSUE TITLE
Could not find required distribution python-social-auth

### ISSUE THREAD

**Issue by nemesisdesign** [omab/python-social-auth#638]
Using `python setup.py develop` on a project.

eg:

```bash
git clone https://github.com/ninuxorg/nodeshot.git
cd nodeshot
mkvirtualenv nodeshot
python setup.py develop
```
returns:

    No eggs found in /.../python-social-auth-0.2.10/egg-dist-tmp-VceTwJ (setup script problem?)
    error: Could not find required distribution python-social-auth==0.2.10

Anyone else getting this?

**Comment by nemesisdesign** [comment]
It seems it's possible to replicate the issue with doind just:

    easy_install python-social-auth==0.2.10

pip works fine though ...

**Comment by nemesisdesign** [comment]
@omab do you know how to workaround this issue?

**Comment by nemesisdesign** [comment]
oh well, I found out this is a duplicate of #640 and #635, so I can close this issue while renovating the request to please release a fixed version on pypi.

**Comment by omab** [comment]
@nemesisdesign, version on pypi updated

**Comment by nemesisdesign** [comment]
@omab thank you very much
