### ISSUE TITLE
HTTPError at /complete/facebook

### ISSUE THREAD

**Issue by citmusa** [omab/python-social-auth#639]
Occasionally I get the error: Server Error 500: Internal Server Error, without further explanation.
_(Using python-social-auth==0.2.6)_

**Django Version:** 1.7.7
**Exception Type:** HTTPError
**Exception Value:**    500 Server Error: Internal Server Error
**Exception Location:** /data/web/mysite.com/virtualenv/local/lib/python2.7/dist-packages/requests/models.py in raise_for_status, line 834
**Python Executable:**  /usr/local/bin/uwsgi
**Python Version:** 2.7.9
## traceback

_/data/web/mysite.com/virtualenv/local/lib/python2.7/dist-packages/django/core/handlers/base.py in get_response_

```
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
```
### Local Vars

| Variable | Value |
| --- | --- |
| e | HTTPError('500 Server Error: Internal Server Error',) |
| callback_args | () |
| resolver_match | ResolverMatch(func=< function complete at 0x7fb1007d6578>, args=(), kwargs={'backend': u'facebook'}, url_name='complete', app_name='None', namespace='social') |
| middleware_method | < bound method SocialAuthExceptionMiddleware.process_exception of < social.apps.django_app.middleware.SocialAuthExceptionMiddleware object at 0x7fb1013e5a90>> |
| self | < django.core.handlers.wsgi.WSGIHandler object at 0x7fb103069050> |
| request | "<WSGIRequest\npath:/complete/facebook,\nGET:<QueryDict: {u'state': [u'294NFN5ZV37b9RcvnUeBUWq8e46iLjMc'], u'code': [u'AQDugVJPK8MPEwzVDk4eYxJkKl-qxu_gRYterRQjbng_CoPNR4vfq5a9ry-gDo_7LwbFiwDSkFc635MV5PeOiasAhORgiUYDiZ7AUcq7oMsQh96CdAWuVMkhd_hKsTlX52RfmiDgmh7Bpj1-Q0t3KIbhYHFlVnmkWivX95PpkBXPBOl3ebzdab-KTDaV83V1R-FgVPR4RCSNjkD5fU6HMXqydDkQffRvUsIc-tLZCUKxXWxKsvq6Ea2g91X_oW_3HYD2L8BJ6nmK3l1NnmLjtPY_OFVAk6qEER0Ko5OzWf3QUj8A92MDkM6KxO7egNY8Vc8'], u'redirect_state': [u'294NFN5ZV37b9RcvnUeBUWq8e46iLjMc']}>,\nPOST:<QueryDict: {}>,\nCOOKIES:{'csrftoken': 'f3HrigECHvFPTob4yeO4jBqegfVtkfvb',\n 'sessionid': '8ikdo3fn54f4kmhov4kecbfq4j8vpx8n'},\nMETA:{'CONTENT_LENGTH': '',\n 'CONTENT_TYPE': '',\n u'CSRF_COOKIE': u'f3HrigECHvFPTob4yeO4jBqegfVtkfvb',\n 'DOCUMENT_ROOT': '/data/web/mysite.com/www',\n 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8',\n 'HTTP_ACCEPT_ENCODING': 'gzip',\n 'HTTP_ACCEPT_LANGUAGE': 'es-ES,es;q=0.8',\n 'HTTP_COOKIE': 'csrftoken=f3HrigECHvFPTob4yeO4jBqegfVtkfvb; sessionid=8ikdo3fn54f4kmhov4kecbfq4j8vpx8n',\n 'HTTP_HOST': 'www.mysite.com',\n 'HTTP_REFERER': 'https://www.facebook.com/v2.3/dialog/oauth?scope=email&state=294NFN5ZV37b9RcvnUeBUWq8e46iLjMc&redirect_uri=https%3A%2F%2Fwww.mysite.com%2Fcomplete%2Ffacebook%3Fredirect_state%3D294NFN5ZV37b9RcvnUeBUWq8e46iLjMc&client_id=1448952605425580',\n 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36',\n 'HTTP_X_FORWARDED_FOR': 'SOME.IP.ADD.SS, 127.0.0.1',\n 'HTTP_X_FORWARDED_PROTO': 'https', \n'HTTP_X_REAL_IP': 'SOME.IP.ADD.SS',\n 'HTTP_X_SOURCE_IP': '127.0.0.1',\n 'HTTP_X_VARNISH': '415941402',\n 'PATH_INFO': u'/complete/facebook',\n 'QUERY_STRING': 'redirect_state=294NFN5ZV37b9RcvnUeBUWq8e46iLjMc&code=AQDugVJPK8MPEwzVDk4eYxJkKl-qxu_gRYterRQjbng_CoPNR4vfq5a9ry-gDo_7LwbFiwDSkFc635MV5PeOiasAhORgiUYDiZ7AUcq7oMsQh96CdAWuVMkhd_hKsTlX52RfmiDgmh7Bpj1-Q0t3KIbhYHFlVnmkWivX95PpkBXPBOl3ebzdab-KTDaV83V1R-FgVPR4RCSNjkD5fU6HMXqydDkQffRvUsIc-tLZCUKxXWxKsvq6Ea2g91X_oW_3HYD2L8BJ6nmK3l1NnmLjtPY_OFVAk6qEER0Ko5OzWf3QUj8A92MDkM6KxO7egNY8Vc8&state=294NFN5ZV37b9RcvnUeBUWq8e46iLjMc',\n 'REMOTE_ADDR': '127.0.0.1',\n 'REMOTE_PORT': '',\n 'REQUEST_METHOD': 'GET',\n 'REQUEST_URI': '/complete/facebook?redirect_state=294NFN5ZV37b9RcvnUeBUWq8e46iLjMc&code=AQDugVJPK8MPEwzVDk4eYxJkKl-qxu_gRYterRQjbng_CoPNR4vfq5a9ry-gDo_7LwbFiwDSkFc635MV5PeOiasAhORgiUYDiZ7AUcq7oMsQh96CdAWuVMkhd_hKsTlX52RfmiDgmh7Bpj1-Q0t3KIbhYHFlVnmkWivX95PpkBXPBOl3ebzdab-KTDaV83V1R-FgVPR4RCSNjkD5fU6HMXqydDkQffRvUsIc-tLZCUKxXWxKsvq6Ea2g91X_oW_3HYD2L8BJ6nmK3l1NnmLjtPY_OFVAk6qEER0Ko5OzWf3QUj8A92MDkM6KxO7egNY8Vc8&state=294NFN5ZV37b9RcvnUeBUWq8e46iLjMc',\n u'SCRIPT_NAME': u'',\n 'SERVER_NAME': 'www.mysite.com',\n 'SERVER_PORT': '80',\n 'SERVER_PROTOCOL': 'HTTP/1.0',\n 'UWSGI_SCHEME': 'https',\n 'uwsgi.node': 'ip-10-0-0-184',\n 'uwsgi.version': '2.0.10',\n 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x7fb1014b79c0>,\n 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,\n 'wsgi.input': <uwsgi._Input object at 0x7fb1006f3390>,\n 'wsgi.multiprocess': True,\n 'wsgi.multithread': False,\n 'wsgi.run_once': False,\n 'wsgi.url_scheme': 'https',\n 'wsgi.version': (1, 0)}>" |
| callback | < function complete at 0x7fb1007d6578> |
| wrapped_callback | < function complete at 0x7fb1007d6578> |
| resolver | < RegexURLResolver 'mysite.urls' (None:None) ^/> |
| callback_kwargs | {'backend': u'facebook'} |
| response | None |
| urlconf | 'mysite.urls' |

Can sombody help me? What is causing this error?

**Comment by adheus** [comment]
did you find a solution?

**Comment by citmusa** [comment]
no, while the project was active, this error appeared some times
