### ISSUE TITLE
Algorithm for jwt_decode in OpenIDConnectAuth backend should be configurable

### ISSUE THREAD

**Issue by gabrielhurley** [omab/python-social-auth#641]
https://github.com/omab/python-social-auth/blob/master/social/backends/open_id.py#L334

That value is hard-coded to HS256 which is not the only possible option. It should be a trivial matter to allow a user-configurable value there (in my case RS256).

**Comment by omab** [comment]
Recent changes to OpenIdConnect porting it to use `jwkest` lib, properly take care of the signing algorithm.
