### ISSUE TITLE
Instagram: Missing needed parameter state

### ISSUE THREAD

**Issue by qasimalbaqali** [omab/python-social-auth#643]
I am trying to add instagram login. I first had problems with the REDIRECT_URI giving me a REDIRECT URI whenever I tried to press on the log in via instagram link. 
```
{
    "code": 400,
    "error_type": "OAuthException",
    "error_message": "Redirect URI does not match registered redirect URI"
}
```
I read around Stackoverflow and needed to add http://localhost:8000/complete/instagram as a redirect uri in my settings an on Instagram redirect URI developer page. So I tried going to the link via my browser to check if it's working or not and when I try to go on it it gives me the following error

```
AuthMissingParameter at /complete/instagram/

Missing needed parameter state

Request Method: 	GET
Request URL: 	http://localhost:8000/complete/instagram/
Django Version: 	1.8.2
Exception Type: 	AuthMissingParameter
Exception Value: 	

Missing needed parameter state
```

**Comment by vaibhav-m** [comment]
Explaining what the error message says: PSA expects certain data to be included along with the URL call, which would be absent when you call it manually. So, you will have to have Instagram call the redirect uri to see if everything works fine

**Comment by trojanware** [comment]
Explaining what the error message says: PSA expects certain data to be included along with the URL call, which would be absent when you call it manually. So, you will have to have Instagram call the redirect uri to see if everything works fine
