### ISSUE TITLE
TypeError at /complete/facebook

### ISSUE THREAD

**Issue by chrismaille** [omab/python-social-auth#646]
Request Method: GET
Request URL:    http://127.0.0.1:8000/complete/facebook/?redirect_state=AtY4qsW9RJpNlJS9b0tiLri7NhHi5Kum&code=AQCZhSjAxWGJSLXgH3HyAEWk3UVQ4R3m3lQ9YkFuSe_jaYgYct60qQtzUWAPWVHh0l1Oc2MNQsMGvziqs35OPlPGIuRA5IvNPw82ROzMv-feE30GWWojCkhFXN4YFNqOFwTan9-yWmEcPIA2ku0jziDNniDR8PXHlANcrRlmcwK9Zw_uOKyc9P43kOJodHHGapJ-TiakzS5RsKbDHuMt0Ac7TfD1p4mnf6fu4T3uXMdrsCw-IjtfCgU-4aPWND_4goniq0O4XTBMbC_VUlRc_XSemPemjPbIoAhrztVmWXUnY5hdHQ1HhK-tucfPET2FG4k997z57YUmsyo9LW2qX6lK8IuKx86CwkZXgeKC-7hj0w&state=AtY4qsW9RJpNlJS9b0tiLri7NhHi5Kum
Django Version: 1.8.1
Exception Type: TypeError
Exception Value:    expected string or buffer
Python Version: 3.4.0

**Comment by mascot6699** [comment]
@chrismaille You found any solution to your problem?
