### ISSUE TITLE
Google Identity platform: support for g-signin2?

### ISSUE THREAD

**Issue by stephenmcgruer** [omab/python-social-auth#651]
Does python-social-auth support Google's newer 'g-signin2' flow, rather than the older 'g-signin' approach? (Alternatively put, gapi.auth2 vs the older gapi.auth). See https://developers.google.com/identity/sign-in/web/ .

All the examples in the repo seem to based on g-signin, and use access_token and code vs the newer 'id_token'.

Also see http://codingwithgerwin.blogspot.co.at/2015/04/google-sign-in-20-server-side.html for an overview of 'Google Sign-In 2.0'.

**Comment by bwest87** [comment]
+1 on this. the access_token is extremely weird to find with the new gsignin2. And the docs don't really show you how to find it. It's in these weird two letter properties (like "po" or "wc") that appear to change over time. However, there's a nice clean method for getting the "id_token".

**Comment by anujism** [comment]
Any update on this?

**Comment by omab** [comment]
This should be supported by now, check any of the example apps at [social-examples](https://github.com/python-social-auth/social-examples).
