### ISSUE TITLE
azuread-oauth2 backend: Drop default scope

### ISSUE THREAD

**Issue by shaib** [omab/python-social-auth#654]
The current azuread-oauth2 speicfies a default scope of `['openid', 'profile', 'user_impersonation']`. This is significantly more than many apps require, and places unnecessary limitations on the use (since when configuring scope, the configured scope is added to the default scope rather than replace it).

~~As a specific issue: If you go to authenticate with Azure and enter a `@live.com` email, microsoft will redirect you to the live.com authentication page, but since that does not support these scopes, you will get an obscure error message and the user will never be returned to your site. However, if you do not ask for them, the user is redirected back and (with some hacking) if you enable the Live backend you can even log them in.~~ (there's more to that than I thought, forget this example)

**Comment by omab** [comment]
Set `SOCIAL_AUTH_AZUREAD_OAUTH2_SCOPE = [...]` and `SOCIAL_AUTH_AZUREAD_OAUTH2_IGNORE_DEFAULT_SCOPE = True`.
