### ISSUE TITLE
Connect additional social account to current user

### ISSUE THREAD

**Issue by po5i** [omab/python-social-auth#659]
I didn't find any documentantion or use case anywhere so I had to ask it here.

I am using python-social-auth with django and everytime an user do a login in the app, it creates a new account, which is great.

But I want this use case:

```
The user logs in with a social backend (i.e. Facebook)
The user goes to his/her edit profile page I had created
In that page he/she finds buttons to assocciate or connect additional accounts to the current django user account (i.e. a Twitter or Google button) so next time he wants to login, could use the Twitter account instead the Facebook (which was the first).
```

How which is the best way to develop these connect buttons funcionality? I think it will end up by adding a new object to UserSocialAuth model, but how I contact the backend and get the keys using the PSA engine?

Thanks

**Comment by po5i** [comment]
Is there no way? Anybody?

**Comment by codeboy** [comment]
Yep, i need it to.

**Comment by maxsocl** [comment]
> Is there no way? Anybody?

Look at [django_example](https://github.com/omab/python-social-auth/tree/master/examples/django_example) app to get a hint.

**Comment by omab** [comment]
PSA wil automatically associate new social-account to the current logged in user, if there's no logged-in user, then a new one is created. The URLs are the same for create and associate.
