### ISSUE TITLE
Backend specific USER_FIELDS setting

### ISSUE THREAD

**Issue by inancsevinc** [omab/python-social-auth#661]
The default implementation of `create_user` pipeline method is reading settings via strategy not backend. (https://github.com/omab/python-social-auth/blob/b53e4dd48116e255f0a1e145f4e9d2bd21cd3722/social/pipeline/user.py#L63) 
This makes it impossible to give backend specific settings. Is this behavior intentional?

**Comment by vsobolmaven** [comment]
Same thing with pipeline configuration per backend - not possible with current implementation of authenticate() in social.backends.base

**Comment by omab** [comment]
Per-backend PIPELINE setting was added some time ago, per-backend USER_FIELDS was added here https://github.com/python-social-auth/social-core/commit/1690dd66aeb361f8fc0265c5e45035215f28d2d2.
