### ISSUE TITLE
django rest framework support

### ISSUE THREAD

**Issue by f3r3nc** [omab/python-social-auth#665]
Is there a chance that Django Rest Framework will get support.
For me https://gist.github.com/f3r3nc/3b6ac37c681b49d75159#file-django_strategy-py does the trick but probably needs some more serious work.

**Comment by omab** [comment]
If a PR is proposed I would be willing to review and approve it in, but I don't have any plan to implement a custom strategy to improve the integration with django-rest-framework.

I'm closing the issue, reopen in [social-app-django](https://github.com/python-social-auth/social-app-django) module if still relevant.
