### ISSUE TITLE
No expires in extra_data for linkedin

### ISSUE THREAD

**Issue by skarap** [omab/python-social-auth#666]
Is there a particular reason expires data is not stored for linkedin?
The linkedin doc states it's returned as "expires_in" https://developer.linkedin.com/docs/oauth2 when exchanging the auth code for a request token.

**Comment by kaflesudip** [comment]
I am experiencing the same issue. Any reason for that?

**Comment by kaflesudip** [comment]
Found out a solution for this. You need to add `expires_in` to the list of extra_data. Example:

```
SOCIAL_AUTH_LINKEDIN_OAUTH2_EXTRA_DATA = [
    ('id', 'id'),
    ('firstName', 'first_name'),
    ('lastName', 'last_name'),
    ('emailAddress', 'email_address'),
    ("expires_in", "expires_in")
]
```

**Comment by omab** [comment]
Fixed by https://github.com/python-social-auth/social-core/commit/4e33457813c63f6b1d7979cf2bdc30c5095c0ddf
