### ISSUE TITLE
Lack of proper support for Facebook Canvas Apps?

### ISSUE THREAD

**Issue by Nopik** [omab/python-social-auth#669]
The codebase is having some canvas app support (apparently inherited from django-social-auth), but it doesnt seem to be usable anymore. Or at least I am misunderstanding how it should be done :)

With regular oauth login buttons, button is redirecting to `/login/<backend>`, which usually redirects to oauth provider page, then return to `/complete/<backend>` and then redirects to `/` or whatever is configured.

With FB Canvas apps it looks like PSA is requiring `/login/facebook-app` and `/complete/facebook-app` to be called in proper moments, but FB dashboard is allowing to set only single canvas URL. So, if I understand correctly, I have following options:
1. Set canvas url to `/login/facebook-app`, and provide html template like the one in docs, with some redirect URI. But:
   1. if the redirect URI is my canvas URL, I'm getting infinite login loop
   2. I'm not sure if I can redirect to some URL other than my canvas URL (not checked yet), and trick FB to load that in its canvas iframe (after all I'm overriding window.top). Maybe yes.
   3. Regardless, even if the above will work, I will have extra 2 redirects for users who are already authenticated and just want to re-visit my app. Not cool.
2. Set canvas_url to `/complete/facebook-app`:
   1. this works well if user already allowed to share his info with the app, so `complete` might create user record and use it
   2. but of course will work only once, and of course there is no place where user can share profile data with the app in the first place, since in this scenario nobody displays permission dialog
   3. I can try to write my own backend (basically copied from FacebookAppOAuth2) and inside having some smarter `complete` which optionally tries to redirect to login, if necessary. Yet, after short code inspection it seems that it will be extremely hacky at best.
3. Provide my own `/login/fb` kind of view, which can check whether we need to ask for permission or not, and then call login or complete from social auth. Yet, that is extremely tricky, since we have POST data which basically means that we cannot redirect, or we lose the data. So, apparently importing the view methods from PSA django app and calling them directly would be the way...
4. Something else?

FB Canvas app and its associated POST is done in such way that if user is already authenticated, it allows app to continue with zero redirects. Just the response to initial POST will contain HTML for the specific user. I hope that with PSA it is possible to reach the same situation, with no redirects. If user had not shared personal info with the app yet, single redirect to permission dialog and back is unavoidable. In this case, however, PSA requires third redirect after `/complete/..`, it would be great to be able to avoid it as well.

Now, am I missing something obvious? Is there a way to get current code cooperate properly with canvas app? Or I'm first user in years who is trying to do so, only to discover that the code is badly outdated? Any hints appreciated ;)

**Comment by zergu** [comment]
+1

**Comment by omab** [comment]
I've raised https://github.com/python-social-auth/social-core/issues/8 to properly track this issue in the new components.
