### ISSUE TITLE
Django setup documentation 'makemigrations' instead of 'migrate'

### ISSUE THREAD

**Issue by fafaman** [omab/python-social-auth#679]
Hi,

It seams http://psa.matiasaguirre.net/docs/configuration/django.html should state:
./manage.py migrate
Instead of 
./manage.py makemigrations 
The former produces 'no change detected message' (django 1.8)

Best regards,
Fabrice.

**Comment by pirax** [comment]
Migrate doesn't work either on Django 1.8. Nor makemigrations.
