### ISSUE TITLE
Problem porting from django-social-auth to python-social-auth

### ISSUE THREAD

**Issue by laginha** [omab/python-social-auth#682]
I'm migrating to django 1.8 and I took this change to port from django-social-auth to python-social-auth. 

However I'm having problems with python-social-auth's migrations. It seems its initial migration does not match with the latest `models.py` in django-social-auth. The difference is, python-social-auth adds a new model `Code`. Which means:

- if I fake the initial migration, migrating 0003 will not work 

        django.db.utils.ProgrammingError: relation "social_auth_code" does not exist`

- if I don't fake the initial migration, I immediately get an error 
    
        django.db.utils.ProgrammingError: relation "social_auth_association" already exists`

Any suggestion on how to solve this problem?
Thanks

**Comment by laginha** [comment]
I solved the problem.

While in django 1.6:

1. `pip install python-social-auth`
2. remove `"social_auth"` from the `INSTALLED_APPS`.
2. add `"social.apps.django_app.default"` to the `INSTALLED_APPS`.
3. add  `SOUTH_MIGRATION_MODULES = { "default": "social_auth.migrations"}` to `settings.py`.
5. Create and empty migration to freeze the app: `python manage.py schemamigration --freeze default default freeze --empty`
5. Create a migration to add the `Code` model: `python manage.py schemamigration default --auto`
6. Apply both migrations: `python manage.py migrate default`

When that is done, you have django-social-auth's and python-social-auth's migrations in sync. Thus after you upgrade to django 1.7 or higher:

1. remove from `settings.py` the previously added `SOUTH_MIGRATION_MODULES` option.
2. remove `"south"` from the `INSTALLED_APPS` (you may also need to uninstall it)
2. apply python-social-auth migrations:
    1. `python manage.py migrate default 0001 --fake`
    2. `python manage.py migrate default`

**Comment by dbrgn** [comment]
I had the same problem. Apparently my database was in an inconsistent state, probably due to switching to Django 1.7 and PSA at the same time.

I ended up fixing it in the database directly, by using the output from `python manage.py sqlmigrate default 0001` and comparing it with the state of the live database.

In my case these changes were missing:

```
BEGIN;
CREATE TABLE "social_auth_code" ("id" serial NOT NULL PRIMARY KEY, "email" varchar(75) NOT NULL, "code" varchar(32) NOT NULL, "verified" boolean NOT NULL);
ALTER TABLE "social_auth_code" ADD CONSTRAINT "social_auth_code_email_75f27066d057e3b6_uniq" UNIQUE ("email", "code");
ALTER TABLE "social_auth_nonce" ADD CONSTRAINT "social_auth_nonce_server_url_36601f978463b4_uniq" UNIQUE ("server_url", "timestamp", "salt");
CREATE INDEX "social_auth_code_c1336794" ON "social_auth_code" ("code");
CREATE INDEX "social_auth_code_code_32d820bdeaa954bc_like" ON "social_auth_code" ("code" varchar_pattern_ops);
CREATE INDEX "social_auth_usersocialauth_e8701ad4" ON "social_auth_usersocialauth" ("user_id");
COMMIT;
```

After that, the migrations would apply cleanly.
