### ISSUE TITLE
Reddit OAuth2 backend creates invalid auth header

### ISSUE THREAD

**Issue by TheEnigmaBlade** [omab/python-social-auth#688]
Attempting to retrieve the access token when auth_complete is called results in a 401 returned by the reddit servers. The reddit backend creates an invalid header due to byte strings being unsupported with `.format()`. Here's an example of the resulting header:

```
{'Authorization': "Basic b'BASE64-AUTH-STRING'"}
```

The replacement I have working is:

``` python

def auth_headers(self):
    return {
        'Authorization': b'Basic ' + base64.urlsafe_b64encode(
            ('{0}:{1}'.format(*self.get_key_and_secret()).encode())
        )
    }
```

**Comment by contracode** [comment]
+1 I can confirm the bug and that this fixes it.

**Comment by contracode** [comment]
Submitted Pull Request #745 to fix.

**Comment by jackfischer** [comment]
+1 on the bug. Would be great to have this merged

**Comment by omab** [comment]
PR was merged and issue is fixed.
