### ISSUE TITLE
No email address in details (facebook backend)

### ISSUE THREAD

**Issue by SomethingWrong** [omab/python-social-auth#692]
Hello everyone.
While I was building my REST API on DRF I faced problem with retrieving details from facebook profile, or more precisely email address. I'm getting a NonType object. 
I've specified the scope ( SOCIAL_AUTH_FACEBOOK_SCOPE = ['email'] in my settings.py ), checked documentation and tried everything it told.
Here is the traceback: http://dpaste.com/1C80SDG
Thank you.

**Comment by SomethingWrong** [comment]
Okay, as I understood it's known problem for Facebook. For many reasons, not everyone on Facebook have Email address registered. The simplest solution I've found is to use user's Facebook email:
user_name@facebook.com / user_id@facebook.com
If necessary, you can modify a little omab's **[require_email](https://github.com/omab/python-social-auth/blob/master/examples/django_example/example/app/pipeline.py)** function, so under the last else statement will be something like this:
```python
email = kwargs['response']['id']
details['email'] = str(email) + '@facebook.com'
```

**Comment by scottlow** [comment]
See #675 for more information on this. It looks like a Facebook API problem, as this used to work.
