### ISSUE TITLE
Documentation doesn't mention backend names

### ISSUE THREAD

**Issue by antonagestam** [omab/python-social-auth#694]
I found it hard to figure out how to get the correct URL for the LinkedIn OAuth2 backend. I couldn't find it mentioned anywhere in the documentation but found my answer on this Stackoverflow question http://stackoverflow.com/questions/25732954/python-social-auth-backend-not-found-for-linkedin-oauth2. A comment also mentions you can find the correct name by looking at the backend class's `name` attribute but I find that not to be the best user experience for developers using this package.

Would you accept a pull request with added examples for how to generate the URL for the different authentication backends?

**Comment by omab** [comment]
Yes, I would accept such PR, the documentation location is now at [social-docs](https://github.com/python-social-auth/social-docs).

Thanks.
