### ISSUE TITLE
Do I have to set redirect url in my local files?

### ISSUE THREAD

**Issue by woonchao** [omab/python-social-auth#695]
Hello, I'm a developer of open-edx. I'm trying to add third party auth for my website. When I add qq-auth to my project, I have some problems. Where can I set the redirect_url? Do I have to set redirect url in my project files?

**Comment by omab** [comment]
`redirect_url` is an option in OAuth2 providers when creating the application on their end, it's meant to be used to send the user to that location once approved the access, when configuring PSA, the value usually has the form `http://yousite.com/complete/qq`.
