### ISSUE TITLE
Deprecated Google Scopes

### ISSUE THREAD

**Issue by Oza94** [omab/python-social-auth#697]
Hello, [the scopes used foor Google auth are deprecated](https://developers.google.com/+/web/api/rest/oauth). You need to replace it with a shorter alias.

| Deprecated | Current |
| :-- | :-- |
| `https://www.googleapis.com/auth/userinfo.profile` | `profile` |
| `https://www.googleapis.com/auth/userinfo.email` | `email` |

This is not a problem for the moment, I have spotted it while opening another issue for zestedesavoir/zds-site#2941.

**Comment by omab** [comment]
This got addressed.
