### ISSUE TITLE
Missing needed parameter state

### ISSUE THREAD

**Issue by a1Gupta** [omab/python-social-auth#702]
I am using python social auth with django app. In email validation, the link received on the mail works fine in the same browser from which authentication was initiated but it show Missing needed parameter state in different browser.Its because the other browser doesn't have session for partial pipeline. I tried this https://gist.github.com/SaneMethod/b30156a3705ce9e944cd#file-django-python-social-auth-monkey-py for partial_pipeline_data but it didn't work. How to resume the pipeline in other browser after retrieving the session from django-session table or any other suggestions ?

**Comment by robert-osborne** [comment]
I having a similar issue with the source; using the validate email link for an email login in a new browser session causes the following error:

    Missing needed parameter email

Looking at the code, this doesn't look easy to fix.

**Comment by a1Gupta** [comment]
You can follow Step 3 of this blog, http://artandlogic.com/2015/07/email-validation-with-django-and-python-social-auth/ .Even though this is not perfect solution , this will work until session_key is not deleted/changed in the database. Django updates session_key each time the session data changes. So in case any other user logs in the same browser the session_key gets changed and user can't verify with the email link. I am looking for some solution to fix this.

**Comment by omab** [comment]
Currently there's no easy way to resume a pipeline from another browser since it heavily depends on the session which also usually depends on the browser cookies. I've created https://github.com/python-social-auth/social-core/issues/7 to start working on a solution to this common problem.
