### ISSUE TITLE
How to solve Authentication process canceled error?

### ISSUE THREAD

**Issue by rajasimon** [omab/python-social-auth#708]
Now I try to setup python-social-app

In facebook login after the username/password redirect to error page I don't know why this happen...

In my setting I have 'social.backends.facebook.FacebookOAuth2' and I correctly set SOCIAL_AUTH_FACEBOOK_KEY and Secret so Really where to look the error.?

The thing is i didn't cancel anything ...!

``` Environment:
Request Method: GET
Request URL: http://website.com:8000/complete/facebook/?redirect_state=IuQDEiyX2bbS8Uhk7MR3hpRFLNZlW2Y5&code=AQDH5kqBibfy9bi21M9tTieujRAqvJVYdAb2UPFvfH6DVXoCWrrtamRA99Ze5-6cC6qHPiNq-a3XbGh2Gg4pbdFfM4OTpCEpWkPID6SZrHfAoEan8Q68cV17LDgsryX_M45QoXd0knpbE0x-QwAPwdoFmKQGHLw7xomCHeN5pCtrWhtoYQIrsFE1UQZZaxt4qtLzAmfmCRjDO7Et_S75fngLiomM0PfevTChLbHJHMYaqy6DBkgGZqZK-bXrqLaNFnBEoZ3M956DwCg4ZtTnvxulR4sXH9ZV3IoxVhL0JxMVsGnT2H_0wdKujIDPKcdPKZc&state=IuQDEiyX2bbS8Uhk7MR3hpRFLNZlW2Y5

Django Version: 1.8.3
Python Version: 2.7.6
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'frontend',
 'social.apps.django_app.default')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')


Traceback:
File "/Users/simon/Freelancer/env/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/simon/Freelancer/env/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)
File "/Users/simon/Freelancer/env/lib/python2.7/site-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)
File "/Users/simon/Freelancer/env/lib/python2.7/site-packages/social/apps/django_app/utils.py" in wrapper
  51.             return func(request, backend, *args, **kwargs)
File "/Users/simon/Freelancer/env/lib/python2.7/site-packages/social/apps/django_app/views.py" in complete
  28.                        redirect_name=REDIRECT_FIELD_NAME, *args, **kwargs)
File "/Users/simon/Freelancer/env/lib/python2.7/site-packages/social/actions.py" in do_complete
  43.         user = backend.complete(user=user, *args, **kwargs)
File "/Users/simon/Freelancer/env/lib/python2.7/site-packages/social/backends/base.py" in complete
  41.         return self.auth_complete(*args, **kwargs)
File "/Users/simon/Freelancer/env/lib/python2.7/site-packages/social/utils.py" in wrapper
  232.                 raise AuthCanceled(args[0])

Exception Type: AuthCanceled at /complete/facebook/
Exception Value: Authentication process canceled
```

Asked similer question in StackOverFlow too [How to solve Authentication process canceled error?](http://stackoverflow.com/questions/31958246/how-to-solve-authentication-process-canceled-error?noredirect=1#comment51827045_31958246)

**Comment by tkajtoch** [comment]
AuthCancelled can also occur when one of pipelines raises an exception.
Paste your full python-social-auth configuration from settings.py (without api keys of course).

**Comment by LRPalacios** [comment]
@rajasimon  did you solve this? i am having the same issue

**Comment by LRPalacios** [comment]
Well. i saw [this stackoverflowquestion](http://stackoverflow.com/questions/31077965/django-python-social-auth-authentication-canceled-by-facebook-app) and it worked for me too strange i had the right ip of the server but for some reason it did not work when i leave the server ip white list empty it works great

**Comment by shubh3794** [comment]
Has this issue been solved? I am having the same issue

**Comment by johnfosborneiii** [comment]
I finally just solved this. I am not 100% sure what I did to fix but these were some of the things I did.
1. I deleted the faebook app and created a new one.
2. When I was putting the new SOCIAL_AUTH_FACEBOOK_SECRET in settings. I noticed the old one had a the string "reset" at the end of the string. This is what the old secret looked like: 'd9e316e4c67d5a45198cf58ecb0efc10Reset'
The new one just has the String. I am thinking that there may be an issue with the facebook website the way it was copied in the first place? I obviously never added the Reset string there.
3. For the redirect URLs I added /complete/facebook/ since that's the URL that the framework redirects you to before the user then gets redirected to SOCIAL_AUTH_LOGIN_REDIRECT_URL

I am guessing it was either 2 or 3 that fixed. Probably the 3rd one.

**Comment by shubh3794** [comment]
Yep changing the redirect URL solved it for me too.

**Comment by shubh3794** [comment]
I think it would be safe to close the issue now.

**Comment by johnfosborneiii** [comment]
Awesome, good to get to the bottom of it. It took me about too long to figure out!

**Comment by rudyryk** [comment]
I get this error in totally valid case when a user decides to cancel authentication process.

```/complete/vk-oauth2/?redirect_state=xxx&error=access_denied&error_reason=user_denied&error_description=User+denied+your+request&state=xxx```

**Comment by hlrossato** [comment]
I'm getting this error on Facebook when user cancel the authentication process:
/oauth/complete/facebook/?redirect_state=xxxxxx&error=access_denied&error_code=200&error_description=Permissions+error&error_reason=user_denied&state=xxxxxxx

**Comment by omab** [comment]
When the user cancels the auth, the project needs to properly deal with the exception and render/return/etc a proper notification since PSA only deals with the flow, doesn't do rendering or integrates with the project styles, when using Django, there's a [middleware](http://psa.matiasaguirre.net/docs/configuration/django.html#exceptions-middleware) to ease the process.

It's quite common for the APIs to drop errors when not configured properly, on many cases the errors are treated as `AuthCanceled`, on some cases probably wrongly.

**Comment by francescortiz** [comment]
The link @omab posted does not work anymore. I think this is where it should point to:

[Exceptions middleware](http://python-social-auth.readthedocs.io/en/latest/configuration/django.html#exceptions-middleware)

**Comment by deepak1725** [comment]
Detected in 2015, This bug still exists in version available on April, 2018. v 0.3.6

**Comment by theanhvo** [comment]
/oauth/complete/facebook/?redirect_state=xxxxxx&error=access_denied&error_code=200&error_description=Permissions+error&error_reason=user_denied&state=xxxxxxx
Is there any solution to fix it, thanks!!

**Comment by cleder** [comment]
Did you set the `LOGIN_ERROR_URL`?

**Comment by klimuntowskirafal** [comment]
Hi guys, I've been digging for so long on this problem with authentication process cancelled, maybe some of you might help. 

I have another issue with fb login app that I try to implement on my Django project. 

Facebook login is working properly on localhost, but (i dont know why) authentication process is being cancelled on live web application. After clicking on 'Login in facebook' user is being redirected to FB page and is asked to give access to application. User is clicking 'Continue as 'user'' and then it redirects user back to the domain with the displayed message 'Authentication process canceled'. And again those same steps are working on localhost but not on my domain.


With a debug=True I can see more detailed error message which looks like this:

/***

Environment:

Request Method: GET
Request URL: http://www.sellspot.pl/oauth/complete/facebook/?granted_scopes=email%2Cpublic_profile&denied_scopes&code=SOME_CODE

Django Version: 2.2.17
Python Version: 3.7.4

Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'crispy_forms',
 'django.contrib.humanize',
 'bootstrap_pagination',
 'storages',
 'social_django',
 'auctions',
 'users',
 'data',
 'contact_us',
 'report']

Installed Middleware:
('whitenoise.middleware.WhiteNoiseMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware')


Traceback:

File "/app/.heroku/python/lib/python3.7/site-packages/social_core/utils.py" in wrapper
  248.             return func(*args, **kwargs)

File "/app/.heroku/python/lib/python3.7/site-packages/social_core/backends/facebook.py" in auth_complete
  101.             'code': self.data['code']

File "/app/.heroku/python/lib/python3.7/site-packages/social_core/backends/base.py" in request
  237.         response.raise_for_status()

File "/app/.heroku/python/lib/python3.7/site-packages/requests/models.py" in raise_for_status
  940.             raise HTTPError(http_error_msg, response=self)

During handling of the above exception (400 Client Error: Bad Request for url: https://graph.facebook.com/v2.10/oauth/access_token?client_id=***MYAPP_ID***&redirect_uri=http%3A%2F%2Fwww.sellspot.pl%2Foauth%2Fcomplete%2Ffacebook%2F&client_secret=***MYAPP_SECRET***&code=***SOME_CODE***), another exception occurred:

File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/app/.heroku/python/lib/python3.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  44.         response = view_func(request, *args, **kwargs)

File "/app/.heroku/python/lib/python3.7/site-packages/django/views/decorators/csrf.py" in wrapped_view
  54.         return view_func(*args, **kwargs)

File "/app/.heroku/python/lib/python3.7/site-packages/social_django/utils.py" in wrapper
  49.             return func(request, backend, *args, **kwargs)

File "/app/.heroku/python/lib/python3.7/site-packages/social_django/views.py" in complete
  33.                        *args, **kwargs)

File "/app/.heroku/python/lib/python3.7/site-packages/social_core/actions.py" in do_complete
  45.         user = backend.complete(user=user, *args, **kwargs)

File "/app/.heroku/python/lib/python3.7/site-packages/social_core/backends/base.py" in complete
  40.         return self.auth_complete(*args, **kwargs)

File "/app/.heroku/python/lib/python3.7/site-packages/social_core/utils.py" in wrapper
  251.                 raise AuthCanceled(args[0], response=err.response)

Exception Type: AuthCanceled at /oauth/complete/facebook/
Exception Value: Authentication process canceled

***/

**Comment by Jony-softdeveloper** [comment]
I have the same problem described by @klimuntowskirafal. If some know something about it, it will be helpful.

**Comment by benslaney** [comment]
I have the same problem as @Jony-softdeveloper and @klimuntowskirafal  if anyone has found a workaround... 
`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.github.com/user?access_token=censored
`
it's missing the access token in the header of the request it seems?

**Comment by Nathan-Yinka** [comment]
how do i solve this in django 
AuthCanceled
social_core.exceptions.AuthCanceled: Authentication process canceled: Permissions error
when every a user cancel the login using is social media account

**Comment by Nathan-Yinka** [comment]
i have tried all possible methods
none works
