### ISSUE TITLE
HTTPError: 401 Client Error: Authorization Required

### ISSUE THREAD

**Issue by jimmyislive** [omab/python-social-auth#713]
I am trying the first step to get the request token from twitter.

When i use curl with my key/secret, I get back the request token form twitter.

But with the PSA code, I throws the above error. I traced it and it looks like the auth kwargs is a OAuth1 object:

{'headers': {}, 'params': {}, 'timeout': None, 'auth': &lt;requests_oauthlib.oauth1_auth.OAuth1 object at 0x10df68190&gt;}

This is in social/backends/base.py when it is making this call:

response = request(method, url, _args, *_kwargs)

has anyone else encountered this?

**Comment by jimmyislive** [comment]
If I change the code in backends/oauth.py to:

```
'''
        response = self.request(
            self.REQUEST_TOKEN_URL,
            params=params,
            auth=OAuth1(key, secret, callback_uri=self.get_redirect_uri(state),
                        decoding=decoding),
            method=self.REQUEST_TOKEN_METHOD
        )
        '''
        #######
        import requests
        response = requests.post(url=self.REQUEST_TOKEN_URL, auth=OAuth1(key, secret, callback_uri=self.get_redirect_uri(state),
                        decoding=decoding))
        #######
```

**Comment by jimmyislive** [comment]
FYI, the versions I am using are:

django = 1.8.3
requests = 2.7.0
requests_oauthlib = 0.5.0
python_social_auth = 0.2.12

**Comment by vyscond** [comment]
Hi! If note the __README.rst__ on the line 120 the twitter is flag as __OAuth1__. This is why _"it and it looks like the auth kwargs is a OAuth1 object"_

**Comment by ismailsunni** [comment]
hi @jimmyislive I tried to change like your suggestion, but it still doesn't work :(

**Comment by jimmyislive** [comment]
FYI, this has been resolved for me and is no longer an issue. Thx.

**Comment by tisdall** [comment]
I got this error when I didn't put in a "Callback URL" in the settings at https://apps.twitter.com .  The docs mention this but it's not obvious from the error message you get.
