### ISSUE TITLE
CodersClan support button does not lead to support forum

### ISSUE THREAD

**Issue by martey** [omab/python-social-auth#721]
The "getSupport()" button in the README links to http://codersclan.net/forum/index.php?repo_id=8, but this redirects to https://www.codersclan.net/?repo_id=8 (the CodersClan homepage).

This is confusing for people looking for a support discussion group who instead find [a website where they are expected to pay for coding "tasks"](https://www.codersclan.net/faq/#when-to-pay).

I can submit a pull request either removing the button or updating the language in the README to make things more clear, but I am not certain what you would prefer.

**Comment by dcmoore-gd** [comment]
@martey If you don't, I may submit a PR for this...

**Comment by martey** [comment]
I didn't submit a pull request because I was hoping for clarification from @omab whether removing the button was okay, or whether he would prefer to have the README's language updated.

**Comment by omab** [comment]
The button was removed since it wasn't used anymore.
