### ISSUE TITLE
no social.utils module error

### ISSUE THREAD

**Issue by dotcomarmy** [omab/python-social-auth#723]
when i run the code it gives this error:

  File "facebook.py", line 11, in <module>
    from social.utils import parse_qs, constant_time_compare, handle_http_errors
ImportError: No module named social.utils

**Comment by tkajtoch** [comment]
Looks like Python cannot find `social` module. Are you using virtualenv?
For test you can run interpreter inside your environment and check python-social-auth version:
```
import social
social.__version__
```
