### ISSUE TITLE
400 Client Error: Bad Request on backend.do_auth (facebook)

### ISSUE THREAD

**Issue by ghost** [omab/python-social-auth#726]
Getting error:

> Django Version:    1.8.2
> Exception Type:    HTTPError
> Exception Value:   
> 
> 400 Client Error: Bad Request
> 
> Exception Location:    /usr/local/lib/python2.7/dist-packages/requests/models.py in raise_for_status, line 851

I'm getting the correct backend (facebook) and then calling:

`backend.do_auth(token, user=user)`

it always throws that error...

using: python-social-auth==0.2.12

I have a custom User model (although I'm not exactly sure if this ties into the issue), I've looked through the source code but can't pinpoint exact issue.

I'm also using Django Rest Framework with a custom endpoint.

Before it hits the requests module at 
`return self.get_json(self.USER_DATA_URL, params=params)`

params is {'access_token': u'XXXXXXXXXXXXXX, 'appsecret_proof': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'}

Any response appreciated.

**Comment by lcplusplus** [comment]
looking into the issue further, it seems problem maybe with the API version. v2.3 -> v2.4

**Comment by aethemba** [comment]
+1 Im running into a similar issue. Apps that have an API version prior to 2.4 are working correctly but new apps break. The call to backend.do_auth(access_token) does not return me a User but None.

**Comment by aethemba** [comment]
Please ignore my previous message. The FB API changes caused my own code to break, not python-social-auth.

**Comment by omab** [comment]
Facebook API is now at 2.8 and the lib was updated to support it.
