### ISSUE TITLE
Documentation gives regex for CLEAN_USERNAMES that isn't the one that's coded

### ISSUE THREAD

**Issue by TeckFA** [omab/python-social-auth#732]
The docs say, in [Username generation](https://python-social-auth.readthedocs.org/en/latest/configuration/settings.html#username-generation), that the regex for CLEAN_USERNAME is `r'[^\w.@+-_]+'`, whereas the code has (in `social.storage.base`)

``` python
CLEAN_USERNAME_REGEX = re.compile(r'[^\w.@+_-]+', re.UNICODE)
```

The documented regex creates an interesting range, viz. '+-_'. The actual Python text puts '-' at the end, which is good; also, it has the `re.UNICODE` option, which, I think, is worth mentioning in the docs, as it provides guidance when thinking about locales for `\w`.

**Comment by omab** [comment]
Updated https://github.com/python-social-auth/social-docs/commit/551123cc61a545ef79b683592a0931f1a313cca5.
