### ISSUE TITLE
Fitbit oauth2

### ISSUE THREAD

**Issue by spruzzer** [omab/python-social-auth#733]
I would like to ask you if you have the intention to support oauth2 authentication for fitbit.

Best regards,
David

**Comment by robbiet480** [comment]
Fitbit will be retiring OAuth1.0a soon (as yet undefined date though) and OAuth2 is required for heartrate & location access.

**Comment by awidgery** [comment]
Fitbit OAuth 1 retirement is now set for Mar/Apr 2016:

https://dev.fitbit.com/docs/oauth2/

Is there any plan to support oauth2?
