### ISSUE TITLE
Error 'Response' object has no attribute 'has_header' when backend.do_auth

### ISSUE THREAD

**Issue by lgavinho** [omab/python-social-auth#740]
It seems a bug. I don't know what happen.

You can see more detail here http://stackoverflow.com/questions/32659923/i-get-a-response-error-when-trying-to-make-a-request-to-my-tastypie-rest-api-usi

**Comment by PaulGregor** [comment]
Hi there! I faced the same problem. 
Django: 1.8.5
PSA: 0.2.13
