### ISSUE TITLE
example/django_example twitter error

### ISSUE THREAD

**Issue by jcda** [omab/python-social-auth#742]
hi, 
I just cloned psa in a fresh virtualenv with python 3.4.2 django 1.8.4 and also python_social_auth-0.2.12-py3-none-any.whl  , did a ./manage.py migrate and ./manage runserver . after getting on the front page I pushed the twitterOAuth button, get redirected to the api page and then get back to the loopback page. 
here is the error message I have on the http://127.0.0.1:8000/login/twitter/ .

<snip>
ValueError at /login/twitter/
Only unicode objects are escapable. Got None of type <class 'NoneType'>.
Request Method:	GET
Request URL:	http://127.0.0.1:8000/login/twitter/
Django Version:	1.8.4
Exception Type:	ValueError
Exception Value:	
Only unicode objects are escapable. Got None of type <class 'NoneType'>.
Exception Location:	/Users/jcda/django/python-social-auth/lib/python3.4/site-packages/oauthlib/oauth1/rfc5849/utils.py in escape, line 56
Python Executable:	/Users/jcda/django/python-social-auth/bin/python
Python Version:	3.4.2
Python Path:	
['../..',
 '/Users/jcda/django/python-social-auth/src/python-social-auth/examples/django_example',
 '/Users/jcda/django/python-social-auth/lib/python3.4/site-packages/setuptools-18.3.2-py3.4.egg',
 '/Users/jcda/django/python-social-auth/lib/python3.4/site-packages/pip-7.1.2-py3.4.egg',
 '/Library/Frameworks/Python.framework/Versions/3.4/lib/python34.zip',
 '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4',
 '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin',
 '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/lib-dynload',
 '/Users/jcda/django/python-social-auth/lib/python3.4/site-packages']
Server time:	Thu, 24 Sep 2015 06:27:15 -0300

</snip>

**Comment by maxsocl** [comment]
@jcda You should set at least empty strings for TWITTER OAUTH KEY/SECRET params in settings.py

**Comment by jcda** [comment]
thanks, that was exactly it
