### ISSUE TITLE
To override user agent need override request method

### ISSUE THREAD

**Issue by tbicr** [omab/python-social-auth#752]
Now user_agent get from `utils.user_agent` when `SEND_USER_AGENT` is `True`. To override it I need override whole `request` method: https://github.com/omab/python-social-auth/blob/master/social/backends/base.py#L215.

Propose add overridable `user_agent` method instead direct `utils.user_agent` usage.

**Comment by omab** [comment]
Support added at [social-core](https://github.com/python-social-auth/social-core/commit/b20feb4ffef6dfcb2c171b9d04cfa65f405d1578).
