### ISSUE TITLE
RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10

### ISSUE THREAD

**Issue by lorddaedra** [omab/python-social-auth#754]
Please, check your /site-packages/social/apps/django_app/urls.py and replace 'auth', 'complete', 'disconnect', 'disconnect' to view.

Tested on Django1.9a1, Python 3.5

**Comment by yprez** [comment]
Can be closed I think, not sure why github didn't close this automatically...

**Comment by omab** [comment]
This got solved.
