### ISSUE TITLE
Django create_user fails if USERNAME_FIELD is not set to default 'username'

### ISSUE THREAD

**Issue by maryokhin** [omab/python-social-auth#762]
I have a problem of python-social-auth failing on Django if [USERNAME_FIELD](https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#django.contrib.auth.models.CustomUser) is set to anything other than `'username'`, i.e. `'email'`. 

I have debugged to understand that the cause of the problem is due to `create_user()` in `django_orm.py` [popping out](https://github.com/omab/python-social-auth/blob/master/social/storage/django_orm.py#L59) `username` kwarg and replacing it with, in my case, `email` kwarg before calling the model manager's [create_user](https://docs.djangoproject.com/en/1.8/ref/contrib/auth/#django.contrib.auth.models.UserManager.create_user) method.

To me that is completely unexpectant, as I don't understand why this is done, and why `USERNAME_FiELD` is taken into account on user creation, when it's supposed to be used only by authentication backends.

**Comment by yaniv14** [comment]
Same happened to me, I just created my own create_user and replace the one in the pipeline.

def create_user(strategy, details, user=None, *args, **kwargs):
    if user:
        return {'is_new': False}

    return {
        'is_new': True,
        'user': strategy.create_user(email=details['email'])
    }

**Comment by omab** [comment]
The pipeline was updated to a more generic version that will fetch the needed fields to create a user from the setting `SOCIAL_AUTH_USER_FIELDS`, defaults to `['username', 'email']`.
