### ISSUE TITLE
Using Social auth to create a local user

### ISSUE THREAD

**Issue by monk8800** [omab/python-social-auth#765]
Is it possible to create a local django user using the soical auth framework. I dont see any examples that illustrate this. I have a rest api that creates users just fine but i would like to consolidate and use social auth for local registration as well. 

The kinda data would like to pass into social auth to create a user profile 
{  
   "groups":[34],
   "first_name":"mike",
   "email":"mike@bizz.com",
   "confirm_email":"mike@bizz.com",
   "password":"secret77",
   "confirm_password":"secret77",
   "accept_terms_conditions":true,
   "username":"mike@bizz.com"
}

Still new to the social auth would appreciate if anyone can point me in the right direction.

**Comment by omab** [comment]
PSA focus on social athentication/authorization, it also has support for "legacy" backends (email and username), you could extend any of those with the desired behavior. Check the docs for them here http://psa.matiasaguirre.net/docs/backends/index.html#non-social-backends
