### ISSUE TITLE
403 Response (instead of 500) for accounts outside of whitelist

### ISSUE THREAD

**Issue by kevinharvey** [omab/python-social-auth#766]
I'm using the GoogleOAuth2 backend and I've got `SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS` set to only allow accounts from a specific domain [as described in the docs](http://psa.matiasaguirre.net/docs/configuration/settings.html?highlight=redirect#whitelists). 

Everything works as expected, except I get a 500 Internal Server Error when I try to log in with an account outside of the specified domain. I would have expected the response to have been a 403 Forbidden.

I'm using Django, and can see from the traceback that the 500 error results from an unhandled `AuthForbidden` exception. Would it be possible for the pipeline to catch that exception and redirect to the default 403 view?

I'd be interested in working on this, but would need a little direction as to how the fix could be framework-agnostic (still work for Flask, Tornado, etc.)

**Comment by cage1016** [comment]
Here is my solution to solve this problem

> django + python-social-auth

1.  modify `MIDDLEWARE_CLASSES`
MIDDLEWARE_CLASSES = (
  ...
  'social.apps.django_app.middleware.SocialAuthExceptionMiddleware',
)

2. setup login error url
ex: SOCIAL_AUTH_LOGIN_ERROR_URL = '/accounts/login-error/'

3. setup login error view what you want
4. as [Exceptions Middleware](https://goo.gl/cgBvqk) mention. Exception processing is disabled if any of this settings is defined with a True value:

```
<backend name>_SOCIAL_AUTH_RAISE_EXCEPTIONS = True
SOCIAL_AUTH_RAISE_EXCEPTIONS = True
RAISE_EXCEPTIONS = True
DEBUG = True
```
