### ISSUE TITLE
SOCIAL_AUTH_UID_LENGTH not being applied for mysql utf8mb4?

### ISSUE THREAD

**Issue by abepark01** [omab/python-social-auth#777]
I set SOCIAL_AUTH_UID_LENGTH = 191 in my settings.py file for my Django project, but it looks like get the following error still: _mysql_exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

When I search for SOCIAL_AUTH_UID_LENGTH it does not look like, the code is referencing this, but just wanted to double check.

Thank you and appreciate the help!

Here's my setup:
Ubuntu 14.04.3/Python 3.4.3
mysql 5.5.46
Django==1.8.6
mysqlclient==1.3.6
python-social-auth==0.2.13

**Comment by tkajtoch** [comment]
Did you migrated changes into the database after modifying UID_LENGTH?

**Comment by abepark01** [comment]
Yes, I made the changes in the settings.py of my Django project and then ran
```
python manage.py migrate
```
Before that I created an empty mysql database.

**Comment by abepark01** [comment]
Perhaps it wasn't ported over from the [django-social-auth](https://github.com/omab/django-social-auth) project?
I did notice the following references in the codebase:

https://github.com/omab/django-social-auth/blob/699571a3b6d84aa2c25ffce59daa4c7f3559a0e4/social_auth/migrations/0001_initial.py#L13

https://github.com/omab/django-social-auth/blob/699571a3b6d84aa2c25ffce59daa4c7f3559a0e4/social_auth/migrations/0002_auto__add_unique_nonce_timestamp_salt_server_url__add_unique_associati.py#L13

**Comment by abepark01** [comment]
I did notice that the uid is set to 255 [here](https://github.com/omab/python-social-auth/blob/aa66b83d4848c09defa57384529eca83597a3692/social/apps/django_app/default/migrations/0001_initial.py#L79)
So, it doesn't look like UID_LENGTH is being applied?
I'm relatively new to Python, but perhaps we just need to read the setting variable SOCIAL_AUTH_UID_LENGTH in [0001_initial.py](https://github.com/omab/python-social-auth/blob/aa66b83d4848c09defa57384529eca83597a3692/social/apps/django_app/default/migrations/0001_initial.py#L79)

I also saw [models.py](https://github.com/omab/python-social-auth/blob/aa66b83d4848c09defa57384529eca83597a3692/social/apps/django_app/default/models.py#L34), but this class does read UID_LENGTH.

Would the solution

**Comment by abepark01** [comment]
Here is a more detailed error message, which seems to indicate the first migration fails because it uses 255 as the max length for the uid field:
```
Applying default.0001_initial...Traceback (most recent call last):
  File "/Users/abe.park/.virtualenvs/p3/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/abe.park/.virtualenvs/p3/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/Users/abe.park/.virtualenvs/p3/lib/python3.5/site-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/Users/abe.park/.virtualenvs/p3/lib/python3.5/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/Users/abe.park/.virtualenvs/p3/lib/python3.5/site-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/Users/abe.park/.virtualenvs/p3/lib/python3.5/site-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/Users/abe.park/.virtualenvs/p3/lib/python3.5/site-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/Users/abe.park/.virtualenvs/p3/lib/python3.5/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
```

**Comment by omab** [comment]
Closing since this was fixed a long time ago.
