### ISSUE TITLE
Is the Auth Provider List out of date and is SAML supported?

### ISSUE THREAD

**Issue by conoramurphy** [omab/python-social-auth#778]
For example I used Azure even though it isn't listed anywhere in the github repository.

I also was looking at using a SAML backend OneLogin and even though it's not listed there's tests for it in the code. https://github.com/omab/python-social-auth/search?utf8=✓&q=onelogin Which I assume must be passing.

Are these things officially supported and undocumented, or are they not supported at all? Apologies if I'm duplicating, but the only issue I found for this was open but the code supporting SAML seems to be merged 6 months ago.https://github.com/omab/python-social-auth/issues/388 which then links to this > https://github.com/omab/python-social-auth/pull/616.

I'm assuming it's possible but unofficially supported I just want to clarify to be sure. (Also any examples of anything I might need to do to get this to work?)

**Comment by omab** [comment]
Backends list can be found here http://psa.matiasaguirre.net/docs/backends/index.html, there might be some cases where the documentation file is missing, but if a backend is defined [here](https://github.com/python-social-auth/social-core/tree/master/social_core/backends), the it's officially supported.
