### ISSUE TITLE
Is there a way to use psa to authenticate credentials only?

### ISSUE THREAD

**Issue by lmaloney** [omab/python-social-auth#781]
I'd like to add additional credentials to for my users in my app, without creating/changing the existing django user....

The work flow would be like this:  
1.) Use PSA to establish user (new, or current login),  creates django user, logs into app.
2.) Use PSA for existing logged in user, to obtain credentials in pipeline, BUT keep current user logged in, and don't change anything in django for that user.

Is there an easy way to do this without changing the pipeline?  I've got my pipeline setup, and I've tried
to save off the user object at the start of the authentication process, and then reassign it back... I seem to be able to keep the same django user.id, but the e-mail address changes on me.

Am I making sense on this?

**Comment by yprez** [comment]
> but the e-mail address changes on me

I have a similar setup, sounds like you need the `SOCIAL_AUTH_PROTECTED_USER_FIELDS` setting to protect the email field.

http://psa.matiasaguirre.net/docs/configuration/settings.html#miscellaneous-settings
