### ISSUE TITLE
Facebook Friends email

### ISSUE THREAD

**Issue by rajanshah** [omab/python-social-auth#790]
Hi,

This is a question rather than issue.

I would like to access Friend's email address via Facebook. Assuming that, my application is still in beta I would like to find out:

a. Whether, if someone approves access to (email, user_profile and user_friends) by accessing application - does it cover user's email scope?

b. Does python-social-auth allow retrieval of Friend's email address? If yes, what scope needs to be used?

c. If above requires extended permission, does it require application review process?

With best,
Rajan

**Comment by se0kjun** [comment]
I think you cannot access friend's email address. 

But, if possible, only access a friends installed your apps. You can get friend's name and id using [graph API](https://developers.facebook.com/docs/graph-api/reference/v2.5/user/friends). And then you can get email address using friend's id.

Good luck!

**Comment by rajanshah** [comment]
Thanks for the reply as I am searching for correct answer since last several days.

So, suppose at least couple friends have installed app and if I can get their id, name via user_friends scope. How can I use friend's id to access their email address using Graph API?
