### ISSUE TITLE
This doesn't support oauth2/v3 right? 

### ISSUE THREAD

**Issue by shahzaibmuneeb** [omab/python-social-auth#791]
https://developers.google.com/identity/sign-in/android/backend-auth

I get the 403 forbidden error, with a token I am generating on my frontend app. The python-social-auth backend was working fine initially and now doesn't work with this new token so I am guessing this library doesn't support the new v3 endpoints?

I may be completely off. Any more information on this?

**Comment by rithi** [comment]
Encountered the same issue - This is a workaround. 

Had to take an extra measure to convert the **serverAuthCode** (from android application) to an access token which can then be used to get the user profile or access other APIs.

See: https://developers.google.com/identity/protocols/OAuth2InstalledApp
Using: https://github.com/PhilipGarnero/django-rest-framework-social-oauth2

I would imagine a similar approach for PSA (convert auth code to access token).

```python
class ConvertTokenViewCustom(ConvertTokenView):
    """
     Transform Google Token request to access token.
    """

    GOOGLE_BACKEND_KEY = "google-oauth2"
    GOOGLE_TOKEN_URL = "https://www.googleapis.com/oauth2/v3/token"
    # should match configured redirect URL on Google Developer console
    GOOGLE_REDIRECT_URL = "<REDIRECT-URL>"

    def get_google_token(self, server_token):
        params = dict(code=server_token,
                      client_id=settings.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY,
                      client_secret=settings.SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET,
                      redirect_uri=self.GOOGLE_REDIRECT_URL,
                      grant_type="authorization_code")
        response = requests.post(self.GOOGLE_TOKEN_URL, data=params)
        response_json = response.json()
        return response_json.get("access_token", server_token)

    def post(self, request, *args, **kwargs):
        request.POST = request.POST.copy()
        backend = request.POST.get("backend")
        if backend == self.GOOGLE_BACKEND_KEY:
            request.POST["token"] = self.get_google_token(request.POST.get("token"))
        return super(ConvertTokenViewCustom, self).post(request, *args, **kwargs)

```

**Comment by ZuSe** [comment]
Are their any plans to support google-oauth v3? Otherwise every android app struggles with authentication. 
@rithi Thanks for the workaround, gonna to try it out for our application.

**Comment by anujism** [comment]
Is there any plan to support this?

**Comment by DavidJFelix** [comment]
+1 in support for adding support for login with google from android app. It seems like this MAY be a similar situation for IOS, but I'm not quite sure yet. Android apps seem to keep the client secret tied to the publishing of the app, which makes it annoying to manage from a server, especially in the current google-oauth2 model.

**Comment by pnagle** [comment]
Is google-auth v4 supporting now ?

**Comment by alexandcote** [comment]
@omab Same question here ? Can I help you with that ?

**Comment by omab** [comment]
Version updated https://github.com/python-social-auth/social-core/commit/54e245c58366d513d3b02e0b5ea18146be04ea16.
