### ISSUE TITLE
Django 1.9.0 Deprecation Warning

### ISSUE THREAD

**Issue by swainn** [omab/python-social-auth#804]
I get the following deprecation warnings when starting the django development server with Python Social Auth app installed:

/usr/lib/tethys/local/lib/python2.7/site-packages/social/apps/django_app/urls.py:19: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got auth). Pass the callable instead.
  name='begin'),

/usr/lib/tethys/local/lib/python2.7/site-packages/social/apps/django_app/urls.py:21: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got complete). Pass the callable instead.
  name='complete'),

/usr/lib/tethys/local/lib/python2.7/site-packages/social/apps/django_app/urls.py:24: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got disconnect). Pass the callable instead.
  name='disconnect'),

/usr/lib/tethys/local/lib/python2.7/site-packages/social/apps/django_app/urls.py:26: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got disconnect). Pass the callable instead.
  .format(extra), 'disconnect', name='disconnect_individual'),

/usr/lib/tethys/local/lib/python2.7/site-packages/social/apps/django_app/urls.py:26: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  .format(extra), 'disconnect', name='disconnect_individual'),

**Comment by hellvix** [comment]
Yeah, me too. I think we will need to wait until the next update appears.

**Comment by liminspace** [comment]
+1

**Comment by bemall** [comment]
Hi, Is this fixed in python-social-auth==0.2.13. I am still getting this error in this version

**Comment by liminspace** [comment]
I'm too :(

**Comment by omab** [comment]
``v0.2.14`` released with this fix.

**Comment by Yobra** [comment]
Thanks Omab..
