### ISSUE TITLE
Yahoo ssl cert issue

### ISSUE THREAD

**Issue by jimmyislive** [omab/python-social-auth#805]
I am using Yahoo for OAuth2. When I use it, I get the error:

ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

However, if I set the option:

SOCIAL_AUTH_YAHOO_VERIFY_SSL = False

it works ! It seems to be a cert issue at the Yahoo end, but was wondering if anyone else has run into it.

**Comment by tkajtoch** [comment]
Hello, Jimmy!

I've just looked in a code and done some research about your issue.
python-social-auth uses the `requests` module to make a HTTP(S) requests. Requests module is based on `curl` and openssl to make secured connections.

Run the following command on your OS and check the result:

    echo | openssl s_client -showcerts -connect api.login.yahoo.com:443 2>/dev/null | openssl x509 -inform pem -noout -text

Look at `Certificate -> Validity` section and compare the dates with the proper ones:

    Not Before: Jun 17 00:00:00 2015 GMT
    Not After : Jun 16 23:59:59 2016 GMT

If the dates are different or the certificate is already expired you must update the CA certificates on your system.

**Updating CA certificates:**

    # apt-get update
    # apt-get install ca-certificates
    # update-ca-certificates

**Comment by jimmyislive** [comment]
Thanks. I checked it and they all look ok:
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            03:d6:0a:f7:3a:3a:69:da:16:c2:7b:8c:4e:63:57:c1
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 Secure Server CA - G4
        Validity
            Not Before: Jun 17 00:00:00 2015 GMT
            Not After : Jun 16 23:59:59 2016 GMT
...
...
...
```

**Comment by tkajtoch** [comment]
Okay. Let's start finding the problem somewhere else.

Run the Python interpreter inside your environment and execute this script:

    import ssl
    from social.utils import SSLHttpAdapter
    
    session = SSLHttpAdapter.ssl_adapter_session(ssl.PROTOCOL_TLSv1)
    response = session.request("GET", "https://api.login.yahoo.com/oauth/v2/request_auth")

    print(response.status_code)

The code above will make a request to Yahoo API in the same way as python-social-auth does.
Certificate verification is performed by default. Script should print `200` as response status code.

**Comment by jimmyislive** [comment]
Thanks for looking but I don't think the issue is at the source end. The issue is at the target cert. If I choose not to verify the cert i.e. verify=False, it works.

I suspect something may be off at the Yahoo end i.e. their cert may have expired or something like that.

FYI, even on the command line when I try I get the same exception:
```
requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

I have tried this on three totally distinct and separate environments.

I googled around and it seems folks have run into the same issue:

e.g. https://developer.yahoo.com/forum/Social-Directory-API/CURL-ERROR/1231422511000-94719244-877b-310e-a995-c8a2975043d6/

Several other forums on YDN talk of the same cert error on some endpoints....

Curious....r u getting a 200 OK for the above?

**Comment by tkajtoch** [comment]
Hello, Jimmy

Yeah, I'm getting 200 OK every time I make the request. I also launched test scripts on my servers located in Poland, Germany, France and UK and 100% of the requests were passed.

Some time ago I saw a post that informs the yahoo load balancer doesn't work properly and certain IPs are redirected to the yahoo development servers, not the production ones.

Can you make a simple mtr to yahoo endpoint? Maybe we'll find the bug...

**Comment by tkajtoch** [comment]
Can you compare the curl output for these requests from my server with yours?

    # curl -vvv https://api.login.yahoo.com/oauth/v2/request_auth
    * Hostname was NOT found in DNS cache
    *   Trying 188.125.80.138...
    * Connected to api.login.yahoo.com (188.125.80.138) port 443 (#0)
    * successfully set certificate verify locations:
    *   CAfile: none
      CApath: /etc/ssl/certs
    * SSLv3, TLS handshake, Client hello (1):
    * SSLv3, TLS handshake, Server hello (2):
    * SSLv3, TLS handshake, CERT (11):
    * SSLv3, TLS handshake, Server key exchange (12):
    * SSLv3, TLS handshake, Server finished (14):
    * SSLv3, TLS handshake, Client key exchange (16):
    * SSLv3, TLS change cipher, Client hello (1):
    * SSLv3, TLS handshake, Finished (20):
    * SSLv3, TLS change cipher, Client hello (1):
    * SSLv3, TLS handshake, Finished (20):
    * SSL connection using ECDHE-RSA-AES128-GCM-SHA256
    * Server certificate:
    [...]

**Comment by omab** [comment]
Thanks @tkajtoch for that investigation, this looks clearly like a server outdated ca certificates. Reopen in [social-core](https://github.com/python-social-auth/social-core) if this still relevant.
