### ISSUE TITLE
Unit Test Django Client Login?

### ISSUE THREAD

**Issue by meconlin** [omab/python-social-auth#81]
How can I unit test authentication on my Django app using python-social-auth?

I attempted this:

```
    self.c = Client()
    self.u = User.objects.create(username="testuser", password="password", is_staff=True, is_active=True, is_superuser=True)
    self.u.save()
    self.auth = UserSocialAuth(user=self.u, provider="Facebook")
    self.auth.save()
    self.c.login(username=self.u.username, password=self.u.password) 
```

but this call to login returns False and the user is not authenticated

**Comment by alexfalcucc** [comment]
Thanks man!

**Comment by gonvaled** [comment]
@omab what if I really want to make sure that the integration of python social auth with my django project is working? I do not need to test that the social endpoints are working, but at least I would like to know that my site is doing right the request/reply cycle. How to go about this? Is there any example available?

**Comment by idchlife** [comment]
@gonvaled +1
