### ISSUE TITLE
Django 1.10 module 'django.db.models' has no attribute 'SubfieldBase'

### ISSUE THREAD

**Issue by sysint64** [omab/python-social-auth#811]
In Django 1.10. not working, throw an error

```
class JSONField(six.with_metaclass(models.SubfieldBase, models.TextField)):
AttributeError: module 'django.db.models' has no attribute 'SubfieldBase'
```

[Source](https://github.com/omab/python-social-auth/blob/master/social/apps/django_app/default/fields.py#L14)

**Comment by blueyed** [comment]
Dupe of / fixed by #813.

**Comment by webjunkie** [comment]
Also dupe of #755

**Comment by omab** [comment]
Fix already merged.

**Comment by czarina** [comment]
Hello,

I experienced this issue today. Suggestions?

  File "/Library/Python/2.7/site-packages/social/apps/django_app/default/fields.py", line 14, in <module>
    class JSONField(six.with_metaclass(models.SubfieldBase, models.TextField)):
AttributeError: 'module' object has no attribute 'SubfieldBase'
