### ISSUE TITLE
Django 1.9 depreciation issue 

### ISSUE THREAD

**Issue by Eclogesh** [omab/python-social-auth#812]
C:\w>manage.py makemigrations
C:\Python27\lib\site-packages\django\db\models\fields\subclassing.py:22: Removed
InDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value in
stead.
  RemovedInDjango110Warning)

No changes detected

pip freeze environment is Python 2.7.9 and django 1.9

**Comment by liminspace** [comment]
+1

**Comment by blueyed** [comment]
Duplicate of / fixed by #813.

**Comment by omab** [comment]
Fix already merged.
