### ISSUE TITLE
Using request.data in django strategy

### ISSUE THREAD

**Issue by xeor** [omab/python-social-auth#817]
Djangos request.GET is fine, but request.POST is not necessary populated with the data sent in a POST request. See https://github.com/omab/python-social-auth/blob/aa66b83d4848c09defa57384529eca83597a3692/social/strategies/django_strategy.py#L40 for the problem and http://www.django-rest-framework.org/api-guide/requests/#data for the django docs.
The idea is that POST is only populated if it's form-data.

Would it be an idea to change out the logic in the strategy to use .data if the request.method != 'GET'?

I'm submitting this as an issue now because I'm unsure if this is something you guys want or not. Is there any reason not to use .data? Have this only been biting me?

**Comment by yprez** [comment]
I think that `request.data` exists only in the `request` wrapper object in django-rest-framework, not in Django itself...

**Comment by xeor** [comment]
I am using a strategy like this now;

```
class SocialAuthDjangoStrategy(DjangoStrategy):
    def request_data(self, merge=True):
        if not self.request:
            return {}

        if self.request.method == 'POST':
            return self.request.data
        else:
            return self.request.GET
```

and it works as it should. It is simplified a little compared to the original since this is all I need, but it works..
