### ISSUE TITLE
Facebook auth should include return_scopes to see which requested permissions have been granted

### ISSUE THREAD

**Issue by seawolf42** [omab/python-social-auth#818]
When the user approves FB login, they may grant all, some, or none of the scopes requested by the application. By passing `"return_scopes": true` as a parameter to the login URL, the data returned includes a list of scopes that were actually granted by the user.

I am happy to do the work to make this work, but I'm not entirely sure where this should go. It appears to be a parameter on the call to the `AUTHORIZATION_URL`, though when I add it to `SOCIAL_AUTH_FACEBOOK_EXTRA_ARGUMENTS` in settings it is not being picked up.

An alternate way to retrieve this info is calling the Facebook SDK (using facebook-sdk, for instance), but it seems this belongs in the authentication pipeline as that's where I am populating the database with the user's preferences and settings.

**Comment by omab** [comment]
Support added https://github.com/python-social-auth/social-core/commit/4e832808f9db9fa94d228a159f8af960bd7a10ae

**Comment by seawolf42** [comment]
Awesome, thanks!
