### ISSUE TITLE
Tests: Session value state missing

### ISSUE THREAD

**Issue by PabloVallejo** [omab/python-social-auth#827]
We're trying to unit test social authentication, this is our approach:

``` python
self.client.get(
    '/complete/facebook/',
    {
        'state': '...',
        'redirect_state': '...',
        'code': '...',
    }
)

...
```

However, we're getting this error.

``` bash
line 88, in validate_state
    raise AuthStateMissing(self, 'state')
AuthStateMissing: Session value state missing.
```

Is there a way to unit test a strategy calling the complete URL directly?

Thanks!

**Comment by manideepm** [comment]
I don't know whether this will solve your problem, but i hope this might help you.

I was getting the same error with the code:

class TestGoogleLogin(unittest.TestCase):
    
    def setUp(self):
        self.client = Client()
    
    def fake_social_complete(request, backend=None, *args, **kwargs):
        return HttpResponseRedirect('.')

    @mock.patch('something.views.login', side_effect=fake_social_complete)
    def test_login(self, mock_social):
        self.user = User.objects.create_user(email="test@test.com", username="test", password="test")
        self.client.login(username="test", password="test")
        self.factory = RequestFactory()
        request = self.factory.get('/')
        request.user = self.user
        middleware = SessionMiddleware()
        middleware.process_request(request)
        request.session.save()
        response = self.client.get('/complete/google-oauth2')
        self.assertTrue(response.client)


-----------------------
I have changed the unittest.TestCase to django.test.testcases.LiveServerTestCase and it stopped throwing the error and started working
