### ISSUE TITLE
Email Confirmation from different browser, Missing needed parameter email

### ISSUE THREAD

**Issue by a1Gupta** [omab/python-social-auth#830]
Python Social Auth is undoubtedly one of the best plugin for Social Authentication and I expect a lot of people are using it in production. But I see a major bug here in email Authentication while adding a new email during new account creation.

The case can be replicated as follows -
1. Create a new user account using email. An Email confirmation link will be sent to user.
2. Confirm the link from other browser
3. This will give Missing needed parameter email error.

This is because there's dependency on the session for the mail validation partial, which is not an expected behavior. User should be able to confirm his email from any browser.

This issue was raised here #577. @omab  told that -

**I see the problem now, and even if I think that this could be solved with a re-write of the email validation pipeline, this affects all the pipeline functions that use the partial mechanism, so, I'm already working on a restructure of the pipeline serialization functionality that will improve this behavior. Basically the pipeline data will be dumped to a DB table and a hash code will be used to identify the processes which can be stopped and continue later, removing the dependency of the session.**

But I see no updates on this after that, even after the new version is out now. @omab can you please update regarding this.
1. When are you going to fix this issue ?
2. If you are not working on this, what should be the workaround to fix this issue.
   
   I don't want to play with this pipeline mechanism as any change can lead to serious issues in authentication. Currently I am using this [monkey patch](https://gist.github.com/SaneMethod/b30156a3705ce9e944cd#file-django-python-social-auth-monkey-py) which is not perfect.

@omab it seems like a serious issue as many users will not be able to sign up leading to a weird user experience. Everyone who is using psa in production will be facing this issue. **Please give urgent attention on this.**

**Comment by kemar** [comment]
:+1:

**Comment by hartym** [comment]
:+1:

**Comment by franlu** [comment]
:+1:

**Comment by danielskun** [comment]
:+1:

**Comment by tomislater** [comment]
👍

**Comment by omab** [comment]
I've created this issue https://github.com/python-social-auth/social-core/issues/7 to track the work needed to support this scenario.
