### ISSUE TITLE
Redirect url always ends with /#_=_

### ISSUE THREAD

**Issue by FaBay89** [omab/python-social-auth#833]
The urls resolves right, to `SOCIAL_AUTH_LOGIN_REDIRECT_URL` or `?next=` attribute if set. 

But they are always ending with `/#_=_`. I have no idea where this come from.

Backendname: facebook
python-social-auth 0.2.14
django 1.9.1
python 3.4.3

**Comment by a1Gupta** [comment]
There nothing wrong in this. Read this https://developers.facebook.com/blog/post/552/

> 
> Change in Session Redirect Behavior
> This week, we started adding a fragment #_=_ to the redirect_uri when this field is left blank. Please ensure that your app can handle this behavior.

**Comment by FaBay89** [comment]
Ok so sorry for that, seems to be a fb issue...

http://stackoverflow.com/questions/7131909/facebook-callback-appends-to-return-url
