### ISSUE TITLE
PIPLINE variable conflict in Django's settings.py

### ISSUE THREAD

**Issue by towhidi** [omab/python-social-auth#838]
I use django-pipeline and in it's new version it needs a dictionary named PIPLINE in settings.py. python-social-auth seems to pickup this variable as it's own pipeline.  
django-pipeline's PIPLINE looks like this:  

```
PIPELINE = {
    'STYLESHEETS': {
        'base': {  
        ...
```

The error is in social/utils.py line 55, when it tries to split "STYLESHEETS":  

```
def module_member(name):
    mod, member = name.rsplit('.', 1)
    module = import_module(mod)
    return getattr(module, member)
```

**Comment by frafra** [comment]
Same issue here.

**Comment by frafra** [comment]
```
    def get_pipeline(self):
        return self.setting('PIPELINE', DEFAULT_AUTH_PIPELINE)
```
Source: https://github.com/omab/python-social-auth/blob/master/social/strategies/base.py#L97

I changed PIPELINE with SOCIAL_AUTH_PIPELINE and it seems to work.

There's another file which tries to read PIPELINE, but it's under social/tests.
```
$ grep -ri "'PIPELINE'" .
./social/strategies/base.py:        return self.setting('PIPELINE', DEFAULT_AUTH_PIPELINE)
./social/tests/strategy.py:        return self.setting('PIPELINE', (
```

**Comment by omab** [comment]
PSA setting should be named `SOCIAL_AUTH_PIPELINE`, the lib will attempt the following names in this order when trying to fetch the setting:

1. SOCIAL_AUTH_<BACKEND NAME>_PIPELINE
2. SOCIAL_AUTH_PIPELINE
3. PIPELINE

First one to match is returned.
