### ISSUE TITLE
added associate_by_email to pipeline but still adding new account when i login with a social account

### ISSUE THREAD

**Issue by tunavargi** [omab/python-social-auth#84]
I have the following pipeline settings

```
SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    'social.pipeline.user.create_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.associate_by_email',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details'
)
```

I have the email address as tunav@gmail.com as registered and i have the google  plus account as tunav@gmail.com. 
When i log out and try to signup with google plus account, it creates a new account with same email address even  `'social.pipeline.social_auth.associate_by_email'` is added. Any ideas?

**Comment by aroraprince** [comment]
Will this method work if I have a user registered on my webiste manually( i.e not using python- social-auth) using simple forms , and then he tries to register user some social login using same email address.

**Comment by omab** [comment]
@aroraprince, yes, that will work if the user has the same email address.

**Comment by aroraprince** [comment]
@omab I am using the following pipeline:

    DEFAULT_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.social_auth.associate_by_email',
    'social.pipeline.user.get_username',
    'social.pipeline.user.create_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details'
    )

but it does not seem to work in the above scenario.A new user gets registered when I try to register using OAuth.

**Comment by omab** [comment]
@aroraprince, which OAuth backend? Is email being sent by that backend?

**Comment by aroraprince** [comment]
@omab Gmail

**Comment by omab** [comment]
Are you testing with a clean db?

**Comment by aroraprince** [comment]
@omab Yes, I think there isn't any problem

**Comment by omab** [comment]
@aroraprince, not sure if I follow, it's working fine now?

**Comment by aroraprince** [comment]
Yes, I think there isn't any problem with the database

**Comment by omab** [comment]
I was asking about the DB because sometimes users left the account created by python-social-auth in place, so second attempts are actually getting that account again.

**Comment by aroraprince** [comment]
@omab I tried logging in using OAuth after manually registering myself.
