### ISSUE TITLE
implement openid connect authentication / authorisation with OP

### ISSUE THREAD

**Issue by okyere** [omab/python-social-auth#840]
I'm using flask to create an app that will need to authentication / authorize users with openid connect. My openid provider is within my company (not one of the externally listed ones in the docs). Can I still use this package? How will I do it? I have my client_id, authorization, and token endpoints from my OP. (If possible), how can I use this package to facilitate enabling authentication with my flask application? Thanks.

**Comment by omab** [comment]
Implement a backend for your custom provider, point it to the internal URLs for it and add the backend to `AUTHENTICATION_BACKENDS` setting.
