### ISSUE TITLE
Use python-saml 2.1.6

### ISSUE THREAD

**Issue by pitbulk** [omab/python-social-auth#846]
[python-saml 2.1.6 release](https://github.com/onelogin/python-saml/releases/tag/v2.1.6)
includes a security fix, please use it instead of 2.1.3

Some documents reference old version:
- social/tests/requirements.txt
- docs/backends/saml.rst

**Comment by pitbulk** [comment]
There is a new release with security improvements [2.2.0](https://github.com/onelogin/python-saml/releases/tag/v2.2.0).

I highly recommended to use it instead previous versions.

**Comment by omab** [comment]
Dependency updated and enabled Python 3 integration in [social-core](https://github.com/python-social-auth/social-core/commit/4c9623dbf13bafeca506f4434ad8ec5f8347bd6c).
