### ISSUE TITLE
Backend not found error for google oauth2 after two weeks of inactivity

### ISSUE THREAD

**Issue by bigsandy** [omab/python-social-auth#849]
I tried to log in using google oauth2 with python-social-auth after two weeks and suddenly, seeing this error : Backend Not Found. 
Errors is at https://example.com/login/google/

My domain name is correct for my local. I don't understand what's causing this error suddenly as google did not complain earlier with the exact domain name. 

Anyone aware of this issue, please let me know what could be a possible reason. I tried changing the Google App and set a new pair of keys for the Google OAuth2 backend. Still, the same error occurred.

**Comment by omab** [comment]
Google OAuth2 backend is accessible at `/login/google-oauth2`.
