### ISSUE TITLE
Is login with office365 supported?

### ISSUE THREAD

**Issue by jpatel3** [omab/python-social-auth#854]
I see lot of sites now using login with office365, similar to signin with google, facebook or tweeter (though very low amount of sites.). Is it yet supported in python-social-auth or planning to support?

**Comment by LucasRoesler** [comment]
We have implemented it, but it takes some weird effort on the Azure side when setting up your application.   I used the AzureAD Backend in Python Social Auth.

**Comment by jpatel3** [comment]
@LucasRoesler Can you share some details?

**Comment by IOException722** [comment]
After using above configuration with  oauth2_key and oauth2_secret and adding python social auth app ('social_django') in INSTALLED_APPS . Login with Office365 page doen't show while running the proeject after migrating.

Is above configuration settings correct ? Or do i need to add any thing more in it ? Thanks

**Comment by IOException722** [comment]
Generated oauth2_key and oauth2_secret using link provided above after register app on azure app registration page
