### ISSUE TITLE
Yahoo OpenID doesn't follow custom login redirect url

### ISSUE THREAD

**Issue by riklaunim** [omab/python-social-auth#855]
I'm trying to add Yahoo OpenID login to my existing python-social-auth login options in a Django application. 

I have a login url like:

```
/social-auth/login/yahoo/?next=https://localhost/login/DYNAMIC_UUID_HERE/
```

The process goes through, hits /social-auth/complete/yahoo/ and then goes to SOCIAL_AUTH_LOGIN_REDIRECT_URL instead of the _next_ url. Other backends I use (all oauth actually) don't have that problem. What can be the cause of this?

I tried yahoo oauth2, but I get "ups something went wrong" type message on Yahoo - either by trying to test from localhost or they have a problem.

**Comment by alx377** [comment]
I got this same problem except with steam. what was the problem here?
