### ISSUE TITLE
AuthStateForbidden: Wrong state parameter given.

### ISSUE THREAD

**Issue by jishnunandkozhisseri** [omab/python-social-auth#857]
Can anyone help with "AuthStateForbidden: Wrong state parameter given." issue? I don't know how to reproduce this issue but getting this error occasionally.

Internal Server Error: /sso/social/complete/linkedin-oauth2/
Traceback (most recent call last):
  File
"/virtualenvs/pyappd/lib/python2.7/site-packages/django/core/handlers/base.py",
line 132, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File
"/virtualenvs/pyappd/lib/python2.7/site-packages/django/utils/decorators.py",
line 145, in inner
    return func(_args, *_kwargs)
  File
"/virtualenvs/pyappd/lib/python2.7/site-packages/django/views/decorators/csrf.py",
line 58, in wrapped_view
    return view_func(_args, *_kwargs)
  File
"/virtualenvs/pyappd/lib/python2.7/site-packages/social/apps/django_app/utils.py",
line 52, in wrapper
    return func(request, backend, _args, *_kwargs)
  File
"/virtualenvs/pyappd/lib/python2.7/site-packages/social/apps/django_app/views.py",
line 20, in complete
    redirect_name=REDIRECT_FIELD_NAME, _args, *_kwargs)
  File
"/virtualenvs/pyappd/lib/python2.7/site-packages/social/actions.py",
line 43, in do_complete
    user = backend.complete(user=user, _args, *_kwargs)
  File
"/virtualenvs/pyappd/lib/python2.7/site-packages/social/backends/base.py",
line 40, in complete
    return self.auth_complete(_args, *_kwargs)
  File
"/virtualenvs/pyappd/lib/python2.7/site-packages/social/backends/oauth.py",
line 357, in auth_complete
    state = self.validate_state()
  File
"/virtualenvs/pyappd/lib/python2.7/site-packages/social/backends/oauth.py",
line 83, in validate_state
    raise AuthStateForbidden(self)
AuthStateForbidden: Wrong state parameter given.

**Comment by merutak** [comment]
I also get this frequently.

**Comment by amigo00678** [comment]
I had this issue. Put domain name in nginx and django settings, not IP of server. That error gone.

**Comment by merutak** [comment]
@amigo00678  Can you be more specific? Where to put it?

I think I eventually got this solved, by NOT passing a "scope" parameter to Linkedin's auth.

**Comment by Keda87** [comment]
I also had this issue when using twitter, but not all my users got this error.
@amigo00678 could you give a snippet for django settings of yours to fix this?

**Comment by amigo00678** [comment]
The setting that fixed that for me was BASE_URL = 'mydomain.com' instead of BASE_URL = '212.x.x.x'.
