### ISSUE TITLE
Flask/Django examples mostly not working?

### ISSUE THREAD

**Issue by deeplook** [omab/python-social-auth#858]
I'm trying to use `examples/flask_example` and run `python manage.py run server` after pip-installing everything, but for most auth providers I'm getting errors, e.g. this one for Twitter: **“ValueError: Only unicode objects are escapable. Got None of type <type 'NoneType'>."** 

So far I'm getting only a login window for Instagram, Yandex, Podio, Mined and (maybe) Persona, where I don't have an account. It looks like most sites barf at some client or app ID being wrong.

I think I've read the docs about configuration etc. but it looks like this example should work as-is, or isn't that the case?

I just retested with `examples/django_example` and apparently I'm getting exactly the same results. So it's not a matter of flask...

**Comment by omab** [comment]
Example apps were revamped as part of the split [social-examples](https://github.com/python-social-auth/social-examples/blob/master).
