### ISSUE TITLE
Facebook refresh_token comes to empty results.

### ISSUE THREAD

**Issue by root-shkim** [omab/python-social-auth#866]
I'm using **python 3.4, django 1.9.4**.
I check #592 and Facebook returns access token by  **json format**, since Facebook v2.3.

However FacebookOAuth2 `process_refresh_token_response` still returns `parse_qs` so it returns empty resutls.

Instead of FacebookOAuth2 `process_refresh_token_response(self, response, *args, **kwargs)`, it's parents(BaseOAuth2)'s code works. 

```
def process_refresh_token_response(self, response, *args, **kwargs):
        return response.json()
```

**Comment by omab** [comment]
Fixed by https://github.com/python-social-auth/social-core/commit/dd9897c62cf36aab74eb97a1730d28cadee314a9
