### ISSUE TITLE
Xing backend broken

### ISSUE THREAD

**Issue by Chronial** [omab/python-social-auth#871]
It breaks here:
https://github.com/omab/python-social-auth/blob/b07708efe7d19b75009771aa97ddf821e59ec08e/social/backends/xing.py#L35

Xing doesn't like that we transmit the oauth parameters `oauth_callback` and `oauth_verifier` in the request (set here: https://github.com/omab/python-social-auth/blob/b07708efe7d19b75009771aa97ddf821e59ec08e/social/backends/oauth.py#L289). These are actually not needed anymore in this request (auth is done) and Xing fails this request with a `400`.

**Comment by Chronial** [comment]
Note: I fixed this locally for my project – all that is required is to generate the `OAuth1` for this one call without the two problematic parameters.

**Comment by Andygmb** [comment]
@chronial - if you fixed it locally you should submit a pull request with that fix.

**Comment by Chronial** [comment]
@Andygmb In general I agree, but I think this change is more about architecture. My local fix feels to dirty for the actual library, as it only fixes Xing.

I think this should be fixed for every Oauth provider. `oauth_callback` and `aouth_verifier` should only be send on the first call, not all subsequent api calls. Xing is just the only provider that complains, but it's just as wrong for every other one.

**Comment by omab** [comment]
Fixed by https://github.com/python-social-auth/social-core/commit/b78159cbd45ff1c281e92d7756ab03c22f7ded8f.
