### ISSUE TITLE
can anyone add wechat support for python-social-auth

### ISSUE THREAD

**Issue by ChateauXiao** [omab/python-social-auth#872]
hi folks

WeChat, also have a common name WeiXin in chinese, along with QQ (supported already), is  made by Tencent. 

now it become the most hitest molibe app in China.

so i'm wandering if someone can go with me to add wechat to the Auth providers list

feel free to reply me if you are facing any problem.

thx

**Comment by ZhiweiWang** [comment]
please check backend/weixin.py
