### ISSUE TITLE
django error middleware

### ISSUE THREAD

**Issue by tisdall** [omab/python-social-auth#873]
The docs at http://psa.matiasaguirre.net/docs/configuration/django.html#exceptions-middleware state that if there's an error that the `message` and `backend` are attached to the redirect url as GET variables.  However, the middleware tries to use the Django messaging system first and only does the GET variables if the messaging fails.  There's no mention of django.contrib.messages in the docs here.

**Comment by omab** [comment]
Docs added https://github.com/python-social-auth/social-docs/commit/c733a4f12c7e691a520b49643703725883a09080
