### ISSUE TITLE
django login_redirect context processor's value needs escaping

### ISSUE THREAD

**Issue by tisdall** [omab/python-social-auth#875]
The `value` retrieved in `login_redirect` is automatically un-escaped and needs to be re-escaped in order to be used in a querystring.   Currently if the redirect url is something like "/page/?this=that" then the `REDIRECT_QUERYSTRING` will be "next=/page/?this=that" when it should be "next=/page/%3Fthis%3Dthat".

The way to work around this bug is to use `{{ REDIRECT_FIELD_NAME }}={{ REDIRECT_FIELD_VALUE|urlencode }}` in templates.

**Comment by tisdall** [comment]
correction...  My workaround doesn't work if there's nothing to redirect to.  It needs to be instead `{% if REDIRECT_FIELD_VALUE %}{{ REDIRECT_FIELD_NAME }}={{ REDIRECT_FIELD_VALUE|urlencode }}{% endif %}`

**Comment by omab** [comment]
Fixed at https://github.com/python-social-auth/social-app-django/commit/d79d8bde9f4b49a1406683f0731bf1719987695d.
