### ISSUE TITLE
AttributeError: 'str' object has no attribute 'update'

### ISSUE THREAD

**Issue by agersoncgps** [omab/python-social-auth#876]
When I iniciate a login I get the Google account picker and then I am forwarded back to my website with AttributeError: 'str' object has no attribute 'update'. Sure enough if I

`print(type(self.extra_data))
print(self.extra_data)`

I get

`<class 'str'>
"{}"`

Exception Location: /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/social/storage/base.py in set_extra_data, line 87

**Comment by omab** [comment]
This got addressed in the last changes to the JSONField in `social-app-django`.
