### ISSUE TITLE
Warning with dependency six

### ISSUE THREAD

**Issue by mapeveri** [omab/python-social-auth#885]
When I run my application, with django 1.9.5, show this warning:

.../lib/python3.4/site-packages/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

**Comment by hellvix** [comment]
I believe it has been fixed already. However it may have not been reflected to pip repository yet. Try downloading directly from git. pip install git+https://github.com/omab/python-social-auth.git

**Comment by mapeveri** [comment]
One question, when will reflected in pip repository?. Any idea?.

Thanks!

**Comment by hellvix** [comment]
Should come soon if not there already.

**Comment by mapeveri** [comment]
@hellvix thanks!

**Comment by jonobrien** [comment]
pypi not updated yet? Still seeing version 1.10.0 from pip.
