### ISSUE TITLE
How to translate exceptions messages to other languages with django?

### ISSUE THREAD

**Issue by Frenk1** [omab/python-social-auth#891]
I using django with multilanguage supports. Now I need to translate exceptions messages to other languages. How I can do it properly?

**Comment by nuklea** [comment]
Can I use python [gettext module](https://docs.python.org/2/library/gettext.html) for translate?

**Comment by omab** [comment]
I've opened a new ticket in https://github.com/python-social-auth/social-core/issues/6 to track this request.
