### ISSUE TITLE
Facebook and email permissions

### ISSUE THREAD

**Issue by liminspace** [omab/python-social-auth#893]
I have some problem. I will try explain by steps:
1. User click "facebook login".
2. Redirect to fb page where user uncheck email permission and click ok.
3. Redirect to site and show error because email is empty.
4. User try again and click "facebook login" but he cant see fb popup with connection permissions and see only error.

What can I do for set email as required in first fb connection or what can I do for remove old connection without email permission for make new one?
Thanks!

**Comment by creimers** [comment]
@liminspace I'm experiencing something similar, if not the same. Have you been able to solve this?

**Comment by creimers** [comment]
@liminspace Never mind, I solved it with this answer: https://github.com/omab/python-social-auth/issues/675#issuecomment-124964058

**Comment by liminspace** [comment]
@creimers No, I haven't solved this issue yet.

**Comment by netoxico** [comment]
Hi @liminspace I had the same problem and just solved it adding a partial pipeline, added 

settings.py
```.py
SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    'users.pipeline.require_email', # Added my pipeline after get_username
    '...' # Rest of needed pipelines
)
```

users/pipeline.require_email.py
```.py
from django.shortcuts import redirect

from social.pipeline.partial import partial


@partial
def require_email(strategy, details, user=None, is_new=False, *args, **kwargs):
    if kwargs.get('ajax') or user and user.email:
        return
    elif is_new and not details.get('email'):
        email = strategy.request_data().get('email')
        if email:
            details['email'] = email
        else:
            return redirect('require_email')
```

urls.py
```.py
urlpatterns = [
    url(r'^email/$', views.require_email, name='require_email'),
]
```

views.py
```.py
@render_to('home.html')
def require_email(request):
    backend = request.session['partial_pipeline']['backend']
    return {'email_required': True, 'backend': backend}
```

I hope this can help
