### ISSUE TITLE
ImportError: No module named loading in Django 1.9+

### ISSUE THREAD

**Issue by arsavard** [omab/python-social-auth#902]
I'm trying to use python-social-auth to login with github, but I keep getting ImportError: No module named loading when it reaches Django, because loading doesn't exist anymore.

I'm using Django 1.9.5 and python-social-auth 0.2.16.

Any help with this issue would be appreciated.

**Comment by addodelgrossi** [comment]
I am having the same error, but another library
ImportError: No module named django_app

**Comment by ddehghan** [comment]
@addodelgrossi @arsavard Are you guys still having this issue? I am trying to document the PSA compatibility with different Django version. 

This is probably a none issue.

**Comment by snznaota** [comment]
You should change your import to 
`from django.apps.apps import get_model`

**Comment by omab** [comment]
There's no `loading` reference in the application, that has to be something else in the project. `django_app` is not the right app to include, it should be `social.apps.django_app.default`.
