### ISSUE TITLE
@app.route decorator should be outermost in Flask example

### ISSUE THREAD

**Issue by ddoskind** [omab/python-social-auth#906]
In the Flask example app (but not the Flask ME one), the `done` route is defined like this

``` python
@login_required
@app.route('/done/')
def done():
    return render_template('done.html')
```

In order for the `login_required` decorator to work, it must be "inside" of the `app.route` decorator. Currently the `done` route is accessible for non-authenticated users as well.

**Comment by omab** [comment]
Fixed at [social-exampes](https://github.com/python-social-auth/social-examples/commit/e95eaa1cae1c179d1351f97aa2c9ccff5bba0ebe).
