### ISSUE TITLE
Drop support for Django 1.7 and below

### ISSUE THREAD

**Issue by clintonb** [omab/python-social-auth#909]
Django 1.8 is the current long-term support version of Django. There is some code that mentions Django 1.6; but, the South migrations haven't been update along with the standard Django migrations. This could probably fixed; but, it would be simpler to drop support for older versions and remove the cruft from the codebase.

**Comment by omab** [comment]
I've created https://github.com/python-social-auth/social-app-django/issues/5 to properly track this work.
