### ISSUE TITLE
Tornado + mongoengine

### ISSUE THREAD

**Issue by alekseyl1992** [omab/python-social-auth#914]
This project is awesome!
But I would like to know, is it possible to store data in MongoDB while using Tornado?
If not - what steps should I take to implement this? Or is it better to use MySQL instead?

**Comment by BurkovBA** [comment]
There [is a Mongoengine ORM](https://github.com/omab/python-social-auth/blob/master/social/storage/mongoengine_orm.py) in repo, so I don't see any problems to use it with Tornado. For instance, both Flask and Django guys use Mongoengine, so I don't think there should be muchproblem with Tornado.

**Comment by alekseyl1992** [comment]
Tornado is asynchronous in contrast to Djando and Flask, that's the main difference.
I guess one should use motorengine instead of mongoengine.
Anyways i'm not interested in this issue anymore.

But I think it would be good if that case will be covered in examples in that repo.

**Comment by BurkovBA** [comment]
Ah, you're right. Motorengine probably works by making Tornado's io_loop listen to pymongo sockets.

**Comment by omab** [comment]
If this is still relevant, please reopen on the corresponding component at [python-social-auth](https://github.com/python-social-auth).
