### ISSUE TITLE
username with accent not cleaned

### ISSUE THREAD

**Issue by alexislg2** [omab/python-social-auth#917]
Hey, I'm using 0.2.13 of your plugin and I have the following issue: I set `SOCIAL_AUTH_CLEAN_USERNAMES` to True (default) but when a users signs up with a Facebook account with an accent in the name, then the username generated has an accent. The space is removed but not the accent eg if Facebook name is `Paul Leddé` generated username is `PaulLeddé` which is not the expected behaviour I think

**Comment by omab** [comment]
I've improved the regular expressions used in [social-core](https://github.com/python-social-auth/social-core/commit/315aef3c42caa1d4be508411c48ec4e6cf054d90), also added an option to override the default behavior by defining a setting pointing to a function that will be invoked to do the cleanup.
