### ISSUE TITLE
ImportError: No module named 'example.local_settings' with pyramid_example

### ISSUE THREAD

**Issue by pinkeshdarji** [omab/python-social-auth#919]
I am trying to run pyramid_example and it gives 
'ImportError: No module named 'example.local_settings' error.
Kindly Help me.

**Comment by hellvix** [comment]
It is an import issue. Go in the folder and rename the file (from local_settings.py.template to local_settings.py).

**Comment by pinkeshdarji** [comment]
Yes I tried it and its working now.
Thanks @hellvix
