### ISSUE TITLE
VK API requests

### ISSUE THREAD

**Issue by artinnok** [omab/python-social-auth#922]
How to use PSA for requests to VK API? Suppose, I want retrieve an profile picture - can I do this, using PSA?

**Comment by LennyLip** [comment]
I think, no. PSA is auth, not API backend. I think, you can just use access_token of PSA (stored in db) to make new query to vk API using custom python sdk.

**Comment by omab** [comment]
That's correct, PSA just focus on authentication and basic user details retrieval, if the picture is already part of the VK data exchange, then it an be fetched by adding a custom pipeline to process it, if not, then a new request must be done to their API by using the access token stored in the DB.
