### ISSUE TITLE
Facebook url versions should be configurable

### ISSUE THREAD

**Issue by troygrosfield** [omab/python-social-auth#926]
The facebook url [1] version should be configurable since most users will eventually want to upgrade:

```
class FacebookOAuth2(BaseOAuth2):
    """Facebook OAuth2 authentication backend"""
    AUTHORIZATION_URL = 'https://www.facebook.com/v2.3/dialog/oauth'
    ACCESS_TOKEN_URL = 'https://graph.facebook.com/v2.3/oauth/access_token'
    REVOKE_TOKEN_URL = 'https://graph.facebook.com/v2.3/{uid}/permissions'
    USER_DATA_URL = 'https://graph.facebook.com/v2.3/me'
```

Should be something like:

```
fb_api_version = settings.SOCIAL_AUTH_FACEBOOK_API_VERSION

class FacebookOAuth2(BaseOAuth2):
    """Facebook OAuth2 authentication backend"""
    AUTHORIZATION_URL = 'https://www.facebook.com/{0}/dialog/oauth'.format(fb_api_version)
    ACCESS_TOKEN_URL = 'https://graph.facebook.com/{0}/oauth/access_token'.format(fb_api_version)
    REVOKE_TOKEN_URL = 'https://graph.facebook.com/{0}/{uid}/permissions'.format(fb_api_version)
    USER_DATA_URL = 'https://graph.facebook.com/{0}/me'.format(fb_api_version)
```

I guess the problem here is that the code handling of the api responses might need to change as well though.

**UPDATE**: the comments below were related to changing my email in facebook, then trying to login via facebook which was linked to another account.  The error I was seeing was my fault.

Also, I came across an issues where a single facebook user can have multiple facebook uids if auth is handled across multiple apps:
- http://stackoverflow.com/questions/28181769/multiple-facebook-ids-for-the-same-user
- https://developers.facebook.com/docs/graph-api/reference/v2.6/user/ids_for_business

IE, a facebook UID is not always the same.  I ran into an issue where my fb user id that was stored was different when I released a mobile app so I could no longer authenticate my facebook user.  I was unaware that a single facebook user could have multiple facebook user ids until today.

[1] https://github.com/omab/python-social-auth/blob/master/social/backends/facebook.py

**Comment by c-bata** [comment]
+1

**Comment by omab** [comment]
I've added support for it in [social-core](https://github.com/python-social-auth/social-core/commit/35c267fbf84757bc4ec64b278a0edac040bb3309), and documented in [social-docs](https://github.com/python-social-auth/social-docs/commit/7d06053182e5ae4ae4f68e390c9af47889c138bb).
