### ISSUE TITLE
Multiples accounts for the same user

### ISSUE THREAD

**Issue by lerrua** [omab/python-social-auth#927]
Hi guys,

I have many Instagram accounts, Can i connect these different Instagram accounts for a same User?

**Comment by moorchegue** [comment]
I think you can, but you'd have to log out of your current account in Instagram each time before adding another one. Otherwise you'll just get something like "this account is already assiciated".

**Comment by webjunkie** [comment]
Yes, that's what this library will do. You can associate any number of OAuth identities to a user account, including multiple identities from the same provider. But as @moorchegue said, the user has to be logged out, otherwise the provider will not authenticate the right user of course.

**Comment by omab** [comment]
The answers given are correct.
