### ISSUE TITLE
OpenStreetMap OAuth1 failing with python 3 (.4)

### ISSUE THREAD

**Issue by cleder** [omab/python-social-auth#930]
with python 2.7 everything works as expected, with python 3.4. it fails with a 

`requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://www.openstreetmap.org/oauth/request_token`

from the api side:

' I see requests from the same IP you are connected from with no arguments
 just "GET /oauth/request_token HTTP/1.1"' `

I am using 
python-social-auth==0.2.18
requests-oauthlib==0.6.1
with 
Django==1.9.6

**Comment by omab** [comment]
I can't reproduce this, the backend is working as expected once the settings are properly set, ensure to have `SOCIAL_AUTH_OPENSTREETMAP_KEY` and `SOCIAL_AUTH_OPENSTREETMAP_SECRET` defined.
