### ISSUE TITLE
VK auth using access token failed. Unable to retrieve email address.

### ISSUE THREAD

**Issue by deniskrishna** [omab/python-social-auth#943]
I just make this simple call, passing access token, that im retrieving using Vk OpenApi js library.
Email in scope permissions is defined, as an integer.

`if backend == 'vk-oauth2':  
    user = request.backend.do_auth(access_token)`

But on pipeline `associate_by_email` the process of creating a new user fails, because there is no email address.
When using this pure library with redirection, everything works fine.
Could somebody help me to solve this?

Same process with registration by access token for Facebook works fine.

**Comment by LennyLip** [comment]
Work fine for me. Please, paste full stack trace error.

**Comment by LennyLip** [comment]
@deniskrishna please, close issue if it works

**Comment by LennyLip** [comment]
@deniskrishna ну куда пропал. Что, думаешь в опен сорсе тебе все должны помогать?  а вот не фига. Я, когда использую опен сорс либу, обязательно пробегусь по последним тикетам. И если чем могу - отвечаю.
