### ISSUE TITLE
make custom user to retrieve extra data

### ISSUE THREAD

**Issue by vvirads** [omab/python-social-auth#944]
Hello,
I'm Beginner . please what is the best method to create a custom user and retrieve extra data from Linkedin Auth. Import succeded in social_auth_usersocial_auth. But you didn't mention simply and clearly how to retrieve these information. examples please

**Comment by Christopher2K** [comment]
Hi ! 
I'm in the same situation. I'm looking for a way to retrieve informations, save it into my db & link local account and FB account !

**Comment by omab** [comment]
Assuming LinkedIn OAuth2 and Django, the access token is stored in the `UserSocialAuth` instance corresponding to `linkedin-oauth2`, to get it you can do:

```python
access_token = user.social_auth.filter(provider='linkedin-oauth2')[0].access_token
```

With that token you can call any of the LinkedIn APIs that the scope allows you to do.
