### ISSUE TITLE
Import not working when using django, pip folder naming is wrong

### ISSUE THREAD

**Issue by hovi** [omab/python-social-auth#949]
Hey, 

I tried using python-social-auth with django and I was getting error:
No module named social.apps.django_app

After some digging, I found out that folder was actually named Social, not social and that was causing the trouble (in lib/python2.7/site-packages of my virtualenv).
I am no python expert, but I would guess something is wrong with your pip configuration.

**Comment by LennyLip** [comment]
you must add 'social.apps.django_app.default' into your INSTALLED_APPS in django settings.
