### ISSUE TITLE
SocialAuthExceptionMiddleware needs updating to work with Django 1.10

### ISSUE THREAD

**Issue by simonwiles** [omab/python-social-auth#953]
If `social.apps.django_app.middleware.SocialAuthExceptionMiddleware` is added to Django 1.10's new (default) `MIDDLEWARE` setting (as opposed to `MIDDLEWARE_CLASSES`), Django will fail to start.  Ideally the middleware should be updated (using `django.utils.deprecation.MiddlewareMixin` in the short-term), and the documentation should be updated too.

Ref: https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-middleware

**Comment by RevolutionTech** [comment]
+1

**Comment by xgt001** [comment]
+1, faced the same issue

**Comment by felipe3dfx** [comment]
+1

**Comment by jschneier** [comment]
I just opened #1031 can you verify if it works for you?

**Comment by RevolutionTech** [comment]
#1031 works for me, all tests now passing using the `MIDDLEWARE` setting.
