### ISSUE TITLE
Redirect to fail url from steam.

### ISSUE THREAD

**Issue by maxim1989** [omab/python-social-auth#958]
Hello, I got a problem. I make site, I try to log via Steam, but when I log in steam I redirect to my fail view - I logged in Steam and not logged in my site. Please help me solve this problem.

**Comment by maxim1989** [comment]
I added this variables in settings.py, when I deleted them my site start working as I expect.
Why did it happen?

SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details',
)

SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details',
)

**Comment by maxim1989** [comment]
Sorry, secon var is
SOCIAL_AUTH_DISCONNECT_PIPELINE = (
    # Verifies that the social association can be disconnected from the current
    # user (ensure that the user login mechanism is not compromised by this
    # disconnection).
    'social.pipeline.disconnect.allowed_to_disconnect',

    # Collects the social associations to disconnect.
    'social.pipeline.disconnect.get_entries',

    # Revoke any access_token when possible.
    'social.pipeline.disconnect.revoke_tokens',

    # Removes the social associations.
    'social.pipeline.disconnect.disconnect',
)

**Comment by omab** [comment]
This is hard to debug with little details, error tracebacks are very useful to help with this. Steam seems to work fine, I guess the problem was related with the key/secret settings.

I'm closing it, please reopen in the [social-core](https://github.com/python-social-auth/social-core) component if this is still relevant.
