### ISSUE TITLE
Pyramid auth (login) view doesn't accept POST requests while OpenID forms rely on that

### ISSUE THREAD

**Issue by moorchegue** [omab/python-social-auth#959]
Should I make a PR out of this https://github.com/moorchegue/python-social-auth/commit/b836001a4382de684d3c503ab4293e54ff961dd9 ?

**Comment by moorchegue** [comment]
Anyway, https://github.com/omab/python-social-auth/pull/963

**Comment by omab** [comment]
PR already merged.
