### ISSUE TITLE
Django 1.10 RemovedInDjango20Warning: Importing from django.core.urlresolvers is deprecated in favor of django.urls.

### ISSUE THREAD

**Issue by RevolutionTech** [omab/python-social-auth#979]
In some locations, `reverse` is imported from `django.core.urlresolvers` which in Django 1.10 has been deprecated in favour of `django.urls`:
https://github.com/omab/python-social-auth/blob/b07708efe7d19b75009771aa97ddf821e59ec08e/social/apps/django_app/utils.py#L6

This causes a warning in Django 1.10 and will cease to work in Django 2.0.

Ref: https://docs.djangoproject.com/en/1.10/ref/urlresolvers/#module-django.urls

**Comment by omab** [comment]
I've created https://github.com/python-social-auth/social-app-django/issues/6 to track the needed work for this.
