### ISSUE TITLE
Trying to do login via facebook oauth2 (getting AttributeError: type object 'UserSocialAuth' has no attribute 'app_session')

### ISSUE THREAD

**Issue by dotpot** [omab/python-social-auth#985]
`AttributeError: type object 'UserSocialAuth' has no attribute 'app_session'`

Any ideas of where the problem is ?

**Comment by omab** [comment]
Can't help with this little details, `app_session` seems to be defined in Pyramid or Tornado frameworks.

I'm closing it, please reopen in the corresponding component in the [splitted social auth](https://github.com/python-social-auth).
