### ISSUE TITLE
retrieving values from FIELDS_STORED_IN_SESSION

### ISSUE THREAD

**Issue by tisdall** [omab/python-social-auth#987]
I tried adding a GET arg to `SOCIAL_AUTH_FIELDS_STORED_IN_SESSION` and the value is properly added to the session.  However, the docs seem to be wrong about retrieving that data:  https://github.com/omab/python-social-auth/blob/v0.2.19/docs/developer_intro.rst#interrupting-the-pipeline-and-communicating-with-views

The docs say to use `request.get('local_password', None)` (in the example in the docs), however the value is actually at `strategy.session_get('local_password')`.  I'm using Django so I'm unsure about other setups/strategies.

**Comment by Tatsh** [comment]
Thank you. I was so confused and spent at least an hour debugging what was going on. We really need the documentation updated for this.

**Comment by omab** [comment]
[Docs updated](https://github.com/python-social-auth/social-docs/blob/master/docs/developer_intro.rst#L131)

**Comment by tisdall** [comment]
uh..  it seems you changed one instance of getting `'local_password'` from the `request` and left the rest.  The comment above that mentions `request['local_password']` and below that is `user.set_password(request['local_password'])`.

**Comment by omab** [comment]
[Done](https://github.com/python-social-auth/social-docs/commit/29985ce439d35cbd71457b0799fef41bae68ff8a).

Thanks
