### ISSUE TITLE
Django Migrations Broken

### ISSUE THREAD

**Issue by clintonb** [omab/python-social-auth#991]
#916 changed the app name from "default" to "social_auth". Users running the app prior this change will have migrations registered under the old name, resulting in Django thinking it should apply migrations from scratch.

These existing migrations should be faked with the following command:

```bash
python manage.py migrate social_auth 0004 --fake
```

**Comment by clintonb** [comment]
It may also be possible to use the `replaces` functionality normally reserved for squashed migrations.

**Comment by clintonb** [comment]
FYI @omab @cclay

**Comment by rlucioni** [comment]
@omab would you mind releasing v0.2.21 with this change?

**Comment by omab** [comment]
@rlucioni , `v0.2.21` released

**Comment by rlucioni** [comment]
@omab thank you!

**Comment by beaugunderson** [comment]
Noting that fixtures with `"default.usersocialauth"` need to be manually updated to `"social_auth.usersocialauth"` as well.
