### ISSUE TITLE
Email auth without initial redirection

### ISSUE THREAD

**Issue by tremby** [omab/python-social-auth#998]
Is there a way to use the `EmailAuth` backend without the initial redirection before email address and password are entered?

At present I'm offering various social auth methods or email auth, and I want the required fields for the email auth to appear on the same page as the social options. I don't want the user to have to click something to say "email auth" first, which would mean a trip to the server and the redirection. Instead, if the fields are filled out and submitted I want to start the email auth pipeline without having to redirect to a form (since they've already filled in this form).

The [docs](http://psa.matiasaguirre.net/docs/backends/email.html) mention that if I submit the form to my own view that I should call `social.actions.do_complete`, so I'm hoping there's some other method I need to call before that.

Any guidance would be appreciated.

**Comment by omab** [comment]
Your guess is correct, you just need to present the form to the user, no need to go to `/login/email` first, that form needs to `POST` to `/complete/email` and a custom pipeline function will be responsible of taking the form data and storing it were needed.
